# CARBAMYLATION ANALYSIS TOOL

This Jupyter notebook enables selecting and curating protein atomic structures for the analysis of their lysines. The aim, is to identify the subset of lysines that may be carbamylated. The pipeline is divided in the following steps.

* 1. [Data Gathering](#gather)
  - 1.1. [Mine UNIPROT database](#uniprot)
  - 1.2. [Mine PDB and AlphaFold databases](#pdb)
* 2. [Feature Extraction](#measure)
* 3. [Data Analysis](#analysis)

Further explanations about each of these steps are provided in the individual sections below.
Now, start by executing the cell below (press Shift+ENTER keys) to imports all the Python packages required.

In [1]:
import os

#data handling
import numpy as np
import pandas as pd
pd.set_option("display.max_rows", None, "display.max_columns", None)

#plotting
import plotly.express as px
import plotly.graph_objects as go
import nglview as nv
from ipywidgets import HBox, VBox

# atomic structures manipulation
import biobox as bb

#carbamylation analysis procedures
import postprocessing as postproc
from uniprot import Uniprot
from protein import PDB
from measure import Measure

C:\Users\xdzl45\Anaconda3\lib\site-packages\blessed\terminal.py:186: UserWarning: Failed to setupterm(kind='xterm-color'): Could not find terminal xterm-color
  warnings.warn(msg)

## 1. Data Gathering  <a class="anchor" id="gather"></a>

### 1.1. Mine UNIPROT database  <a class="anchor" id="uniprot"></a>

Load data from UNIPROT database. The commands below can be launched multiple times, to compile a database saved in a pandas DataFrame (`Uniprot.df`).

In [2]:
UP = Uniprot()
#UP.get_protein_data("P09167") # example: load structures for a single UNIPROT
UP.from_csv_file("inputs\\input_codes_4.csv") # add structures from a .csv file
UP.df

.csv file successfully opened

  Uniprot Entry               PDB Code     Method Resolution   Chains
0        P62987                   2MBH        NMR          -        A
1        P04406                   1U8F      X-ray       1.75  O/P/Q/R
2        Q9HB71  AF-Q9HB71-F1-model_v1  Predicted        NaN      NaN
3        P15311                   1NI2      X-ray       2.30      A/B

### 1.2. Mine PDB and AlphaFold databases  <a class="anchor" id="pdb"></a>

Load and curate all proteins described in a Uniprot DataFrame (`Uniprot.df`). For each entry in the database:
* raw files are downloaded from the PDB in a working folder (defined by `PDB.raw_dir`)
* each raw file is cleaned: heteroatoms, hydrogens and non-protein and non-ion atoms removed, non-standard aminoacids are amended
* different conformations (usually from NMR ensembles) are saved in different files
* if multiple aminoacid rotamers exist, multiple files are produced
* all produced files are patched, i.e. missing parts in the sequence are added using Modeller
* all files correctly patched are saved in a different folder (defined by `PDB.curated_dir`)

This process will generate a new DataFrame, `PDB.df`, containing information on all the structures that have been correctly curated.

<div class="alert alert-warning">
<b>Warning:</b> depending on how many proteins have to be downloaded and curated, this operation may take a long time. AlphaFold and PDB files not needing curation are processed in few seconds. Large multimers requiring curation can take up to 1 min. Multiple conformations in a single protein structure are individually curated.
</div>

In [3]:
pdb = PDB()
pdb.gather_proteins(UP.df)

UNIPROT: P62987, PDB: 2MBH
> downloading PDB 2MBH
> downloading FASTA for 2MBH
> Alternate model(s) found. Splitting...
>> Patching failed for conformer 0: large gap detected (21 residues)
>> Patching failed for conformer 1: large gap detected (21 residues)
>> Patching failed for conformer 2: large gap detected (21 residues)
>> Patching failed for conformer 3: large gap detected (21 residues)
>> Patching failed for conformer 4: large gap detected (21 residues)
>> Patching failed for conformer 5: large gap detected (21 residues)
>> Patching failed for conformer 6: large gap detected (21 residues)
>> Patching failed for conformer 7: large gap detected (21 residues)
>> Patching failed for conformer 8: large gap detected (21 residues)
>> Patching failed for conformer 9: large gap detected (21 residues)
>> Patching failed for conformer 10: large gap detected (21 residues)
>> Patching failed for conformer 11: large gap detected (21 residues)
>> Patching failed for conformer 12: large gap detected (21 residues)
>> Patching failed for conformer 13: large gap detected (21 residues)
>> Patching failed for conformer 14: large gap detected (21 residues)
>> Patching failed for conformer 15: large gap detected (21 residues)
>> Patching failed for conformer 16: large gap detected (21 residues)
>> Patching failed for conformer 17: large gap detected (21 residues)
>> Patching failed for conformer 18: large gap detected (21 residues)
>> Patching failed for conformer 19: large gap detected (21 residues)
>> FAILED: Patching failed for all conformers

UNIPROT: P04406, PDB: 1U8F
> downloading PDB 1U8F
> downloading FASTA for 1U8F
> alternate amino acid conformations found. Splitting...
>> modelling missing residues

                         MODELLER 10.2, 2021/11/15, r12267

     PROTEIN STRUCTURE MODELLING BY SATISFACTION OF SPATIAL RESTRAINTS


                     Copyright(c) 1989-2021 Andrej Sali
                            All Rights Reserved

                             Written by A. Sali
                               with help from
              B. Webb, M.S. Madhusudhan, M-Y. Shen, G.Q. Dong,
          M.A. Marti-Renom, N. Eswar, F. Alber, M. Topf, B. Oliva,
             A. Fiser, R. Sanchez, B. Yerkovich, A. Badretdinov,
                     F. Melo, J.P. Overington, E. Feyfant
                 University of California, San Francisco, USA
                    Rockefeller University, New York, USA
                      Harvard University, Cambridge, USA
                   Imperial Cancer Research Fund, London, UK
              Birkbeck College, University of London, London, UK


Kind, OS, HostName, Kernel, Processor: 4, WinNT 10.0 build 19043, DM-PHY-122, SMP, unknown
Date and time of compilation         : 2021/11/15 19:44:35
MODELLER executable type             : x86_64-w64
Job starting time (YY/MM/DD HH:MM:SS): 2022/04/03 11:56:47


Pairwise dynamic programming alignment (ALIGN):
  Residue-residue metric   : $(LIB)/as1.sim.mat
  Diagonal                 :          100
  Overhang                 :            0
  Local alignment          :            F
  MATRIX_OFFSET (local aln):       0.0000
  N_SUBOPT                 :            0
  SUBOPT_OFFSET            :       0.0000
  Alignment block          :            1
  Gap introduction penalty :    -600.0000
  Gap extension penalty    :    -400.0000
  Break-break bonus        :   10000.0000
  Length of alignment      :          335
  Score                    :  292963.0000

Sequence identity comparison (ID_TABLE):

   Diagonal       ... number of residues;
   Upper triangle ... number of identical residues;
   Lower triangle ... % sequence identity, id/min(length).

         result@11U8F  @1
result@1      333     333
1U8F  @1      100     335
>> patching model...
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:       454931     444.269     0.434

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:       455459     444.784     0.434
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:       504059     492.245     0.481
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:       517359     505.233     0.493
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           trimmed_align.ali

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:       529324     516.918     0.505

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:       530774     518.334     0.506

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:       533674     521.166     0.509

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:       539474     526.830     0.514

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:       668682     653.010     0.638

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:       670010     654.307     0.639

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:       671338     655.604     0.640

Read the alignment from file       : trimmed_align.ali

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     333      1        1U8F
check_a_343_> >> BEGINNING OF COMMAND
openf___224_> Open           .\result\curated\tmp\chainA.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       772963     754.847     0.737

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:       772963     754.847     0.737

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       773134     755.014     0.737

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       773984     755.844     0.738

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       775242     757.072     0.739

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       777146     758.932     0.741

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:       777146     758.932     0.741

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       777236     759.020     0.741

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       780092     761.809     0.744

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:       780092     761.809     0.744

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       780227     761.940     0.744

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       784511     766.124     0.748

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:       784511     766.124     0.748

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       784709     766.317     0.748

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       791135     772.593     0.754

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:       791135     772.593     0.754

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       791432     772.883     0.755

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       801054     782.279     0.764

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:       801054     782.279     0.764

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       801504     782.719     0.764

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       815954     796.830     0.778

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:       815954     796.830     0.778

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       816629     797.489     0.779

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       838287     818.640     0.799

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:       838287     818.640     0.799

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       839295     819.624     0.800

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:       871799     851.366     0.831

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:       871763     851.331     0.831

check_ali___> Checking the sequence-structure alignment.

Implied intrachain target CA(i)-CA(i+1) distances longer than  8.0 angstroms:

ALN_POS  TMPL  RID1  RID2  NAM1  NAM2     DIST
----------------------------------------------
END OF TABLE
check_a_344_> << END OF COMMAND
openf___224_> Open           ${LIB}/top_heav.lib
read_to_681_> topology.submodel read from topology file:        3

openf___224_> Open           ${LIB}/par.lib

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      1011015     987.319     0.964

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      1012615     988.882     0.966

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      1016595     992.769     0.970

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      1018595     994.722     0.971

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      1021595     997.651     0.974

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      1026095    1002.046     0.979

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      1031667    1007.487     0.984

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      1034467    1010.222     0.987

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      1038667    1014.323     0.991

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      1044967    1020.476     0.997

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      1047739    1023.183     0.999

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      1049139    1024.550     1.001
read_pa_232_> parameters    BONDS   ANGLS  DIHEDS IMPROPS    MODE
                              227     561     661     112       0

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      1101263    1075.452     1.050

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      1350281    1318.634     1.288

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      1387993    1355.462     1.324

mkilst______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572      0         0      1071

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      1495625    1460.571     1.426

patch_______> segment topology patched using RTF:  1 ;  LYS  ;  NTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572   3481      4118      1071


Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      1606121    1568.478     1.532
patch_______> segment topology patched using RTF:  333 ;  GLU  ;  CTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072

genseg______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072
transfe_506_> MODEL is an average of all templates.
transfe_511_> Number of templates for coordinate transfer:        1
              After transferring coordinates of the equivalent template atoms,
              there are defined, undefined atoms in MODEL:     2523        0
openf___224_> Open           1U8F.ini
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523
make_re_417_> Restraint type to be calculated:  stereo

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      1713570    1673.408     1.634

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      1721762    1681.408     1.642

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      1738146    1697.408     1.658

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      1770914    1729.408     1.689

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      1803682    1761.408     1.720

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      1869218    1825.408     1.783

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      1901986    1857.408     1.814

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      1934754    1889.408     1.845

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      2000290    1953.408     1.908

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      2131362    2081.408     2.033

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      2196898    2145.408     2.095

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      2262434    2209.408     2.158

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      2393506    2337.408     2.283

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      2655650    2593.408     2.533

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      2786722    2721.408     2.658
r_stere_606_> Stereochemical restraints were constructed from RTF & PRMF.
              Added bond,angle,dihedral,improper restraints  :     2573    3483    3913    1060
              Total number of restraints before, now         :        0    11029
make_re_422_> Number of previous, current restraints         :        0    11029
make_re_423_> Number of previous, current selected restraints:        0    11029
make_re_417_> Restraint type to be calculated:  phi-psi_binormal

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      2974436    2904.723     2.837
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11029    11360
make_re_423_> Number of previous, current selected restraints:    11029    11360
make_re_417_> Restraint type to be calculated:  omega_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      2974452    2904.738     2.837
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
omgdel__425_> Unselected all O C +N +CA dihedrals:      344
              (This is to avoid clashes between STEREO
              and OMEGA_DIHEDRAL restraints)
make_re_422_> Number of previous, current restraints         :    11360    11692
make_re_423_> Number of previous, current selected restraints:    11360    11348
make_re_417_> Restraint type to be calculated:  chi1_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      2974452    2904.738     2.837
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      3105524    3032.738     2.962
make_re_422_> Number of previous, current restraints         :    11692    11962
make_re_423_> Number of previous, current selected restraints:    11348    11618
make_re_417_> Restraint type to be calculated:  chi2_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      3105524    3032.738     2.962
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi2.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11962    12155
make_re_423_> Number of previous, current selected restraints:    11618    11811
make_re_417_> Restraint type to be calculated:  chi3_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      3105524    3032.738     2.962
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi3.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12155    12232
make_re_423_> Number of previous, current selected restraints:    11811    11888
make_re_417_> Restraint type to be calculated:  chi4_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      3105524    3032.738     2.962
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi4.mdt
mdtrsr__446W> A potential that relies on one protein is used, yet you have at
              least one known structure available. MDT, not library, potential is used.
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12232    12268
make_re_423_> Number of previous, current selected restraints:    11888    11924
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at amaxhash_contac [B,KiB,MiB]:      3832112    3742.297     3.655

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      4094256    3998.297     3.905

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      4356400    4254.297     4.155

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      4880688    4766.297     4.655
make_re_422_> Number of previous, current restraints         :    12268    19747
make_re_423_> Number of previous, current selected restraints:    11924    19403
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      5142832    5022.297     4.905
make_re_422_> Number of previous, current restraints         :    19747    27346
make_re_423_> Number of previous, current selected restraints:    19403    27002
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    27346    32678
make_re_423_> Number of previous, current selected restraints:    27002    32334
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      5667120    5534.297     5.405
make_re_422_> Number of previous, current restraints         :    32678    35800
make_re_423_> Number of previous, current selected restraints:    32334    35456
0 atoms in HETATM/BLK residues constrained
to protein atoms within 2.30 angstroms
and protein CA atoms within 10.00 angstroms
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35800    35800
make_re_423_> Number of previous, current selected restraints:    35456    35456
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35800    35800
make_re_423_> Number of previous, current selected restraints:    35456    35456
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35800    35800
make_re_423_> Number of previous, current selected restraints:    35456    35456
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35800    35800
make_re_423_> Number of previous, current selected restraints:    35456    35456
0 atoms in residues without defined topology
constrained to be rigid bodies
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35800    35800
make_re_423_> Number of previous, current selected restraints:    35456    35456
rmdupl__427_>     1971 redundant cosine dihedral restraints were unselected.
condens_443_> Restraints marked for deletion were removed.
              Total number of restraints before, now:    35800    33485
openf___224_> Open           1U8F.rsr
openf___224_> Open           1U8F.rsr

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      5657856    5525.250     5.396

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6444288    6293.250     6.146
rdcsr2__307_> Number of restraints read    :    33485
              Number of excluded pairs read:        0
              Number of pseudo atoms read  :        0
rdcsrs__304_> Restraints in memory, selected restraints:    33485    33485
              Explicitly excluded atom pairs in memory :        0
              Pseudo atoms in memory                   :        0
openf___224_> Open           1U8F.ini

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6444320    6293.281     6.146
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  1:A  333:A     2523
randomi_498_> Atoms,selected atoms,random_seed,amplitude:     2523     2523        1        4.0000
randomi_496_> Amplitude is > 0; randomization is done.
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    16529
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    18694
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    19846
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    21226
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    23213
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    25454
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    27336
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    29633
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    31052

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6797444    6638.129     6.483
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    32464
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33063
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33485
iupac_m_487_> NH1/2 swapped:      175.0126       14  14
iupac_m_487_> NH1/2 swapped:      176.9221       18  18
iupac_m_483_> CD1/2 CE1/2 swapped:      -92.5952       45  45
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_486_> OE1/2 will be swapped:     -125.2352       61  61
iupac_m_485_> OD1/2 will be swapped:      170.3573       87  87
iupac_m_486_> OE1/2 will be swapped:      171.0588      136  136
iupac_m_485_> OD1/2 will be swapped:      116.7387      139  139
iupac_m_487_> NH1/2 swapped:      178.4100      195  195
iupac_m_487_> NH1/2 swapped:     -174.2881      232  232
iupac_m_485_> OD1/2 will be swapped:      163.5433      242  242
iupac_m_487_> NH1/2 swapped:      176.2712      246  246
iupac_m_483_> CD1/2 CE1/2 swapped:       93.7906      312  312
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_483_> CD1/2 CE1/2 swapped:     -100.0788      316  316
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_487_> NH1/2 swapped:     -175.5670      321  321
openf___224_> Open           ${LIB}/atmcls-mf.lib

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6797872    6638.547     6.483

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6797936    6638.609     6.483

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6797994    6638.666     6.483

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6798058    6638.729     6.483

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6798124    6638.793     6.483

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6798188    6638.855     6.483

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6798344    6639.008     6.483

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6798472    6639.133     6.484

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6798766    6639.420     6.484

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6798958    6639.607     6.484

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6799462    6640.100     6.484

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6799718    6640.350     6.485

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6800714    6641.322     6.486

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6801098    6641.697     6.486

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6801674    6642.260     6.487

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6803708    6644.246     6.489

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6804604    6645.121     6.489

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6809056    6649.469     6.494

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6810400    6650.781     6.495

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6820018    6660.174     6.504

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6822002    6662.111     6.506

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6842648    6682.273     6.526

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6845656    6685.211     6.529

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6891622    6730.100     6.572

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6896102    6734.475     6.577

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6997322    6833.322     6.673
openf___224_> Open           ${LIB}/dist-mf.lib

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6997718    6833.709     6.674

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6998514    6834.486     6.674

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      6999310    6835.264     6.675

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7000498    6836.424     6.676

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7000898    6836.814     6.677

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7001498    6837.400     6.677

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7002398    6838.279     6.678

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7003746    6839.596     6.679

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7003946    6839.791     6.679

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7005970    6841.768     6.681

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7006270    6842.061     6.682

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7009306    6845.025     6.685

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7009754    6845.463     6.685

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7014306    6849.908     6.689

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7014978    6850.564     6.690

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7021806    6857.232     6.697

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7022814    6858.217     6.697

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7033058    6868.221     6.707

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7033658    6868.807     6.708

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7034058    6869.197     6.708

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7035570    6870.674     6.710

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7050934    6885.678     6.724

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7051834    6886.557     6.725

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7052434    6887.143     6.726

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7054702    6889.357     6.728

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7077750    6911.865     6.750

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7079094    6913.178     6.751

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7079994    6914.057     6.752

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7083398    6917.381     6.755

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7117970    6951.143     6.788

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7119986    6953.111     6.790

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7121334    6954.428     6.791

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7126438    6959.412     6.796

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7178294    7010.053     6.846

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7181318    7013.006     6.849

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7183342    7014.982     6.851

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7190998    7022.459     6.858

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7268782    7098.420     6.932

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7273318    7102.850     6.936

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7276354    7105.814     6.939

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7287838    7117.029     6.950

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7404514    7230.971     7.061

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7411318    7237.615     7.068

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7415870    7242.061     7.072

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7433098    7258.885     7.089

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7608114    7429.799     7.256

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7618326    7439.771     7.265

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7625154    7446.439     7.272

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7650994    7471.674     7.297

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7913518    7728.045     7.547

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7928830    7742.998     7.562

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7939074    7753.002     7.571

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      7977834    7790.854     7.608

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      8371618    8175.408     7.984

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      8394586    8197.838     8.006

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      8409950    8212.842     8.020

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      8468090    8269.619     8.076

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      9058766    8846.451     8.639

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      9093218    8880.096     8.672

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      9116266    8902.604     8.694

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:      9203478    8987.771     8.777

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:     10089494    9853.021     9.622

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:     10141178    9903.494     9.671

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:     10175750    9937.256     9.704

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:     10306566   10065.006     9.829

Dynamically allocated memory at amaxgroup_restr [B,KiB,MiB]:     11635590   11362.881    11.097
read_pa_232_> parameters    BONDS   ANGLS  DIHEDS IMPROPS    MODE
                                0       0       0       0   12561
>> Model assessment by DOPE potential
iatmcls_286W> MODEL atom not classified:  GLU:OXT  GLU

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11988914   11707.924    11.434

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12110018   11826.189    11.549

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12352226   12062.721    11.780

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12836642   12535.783    12.242

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     13805474   13481.908    13.166

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     15743138   15374.158    15.014

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     19618466   19158.658    18.710


>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33485   33485
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):   505941
Dynamic pairs routine                             : 1, NATM x NATM double loop
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        1    9999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :   15.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       F       F       F       T
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :      -37930.8320




<< end of ENERGY.
DOPE score               : -37930.832031
>> Model assessment by GA341 potential

Surface library          : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/surf5.de
Pair library             : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/pair9.de
Chain identifier         : _
% sequence identity      :   100.000000
Sequence length          :          333
Compactness              :     0.239703
Native energy (pair)     :  -291.558730
Native energy (surface)  :   -16.771286
Native energy (combined) :    -9.507571
Z score (pair)           :   -10.087004
Z score (surface)        :    -7.402704
Z score (combined)       :   -11.647905
GA341 score              :     1.000000



>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33485   33485
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):     5274
Dynamic pairs routine                             : 2, NATM x NATM cell sorting
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        0   99999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :    4.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       T       F       F       F
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :        1914.5333





Summary of the restraint violations:

   NUM     ... number of restraints.
   NUMVI   ... number of restraints with RVIOL > VIOL_REPORT_CUT[i].
   RVIOL   ... relative difference from the best value.
   NUMVP   ... number of restraints with -Ln(pdf) > VIOL_REPORT_CUT2[i].
   RMS_1   ... RMS(feature, minimally_violated_basis_restraint, NUMB).
   RMS_2   ... RMS(feature, best_value, NUMB).
   MOL.PDF ... scaled contribution to -Ln(Molecular pdf).

 #                     RESTRAINT_GROUP      NUM   NUMVI  NUMVP   RMS_1   RMS_2         MOL.PDF     S_i
------------------------------------------------------------------------------------------------------
 1 Bond length potential              :    2573       0      0   0.005   0.005      20.943       1.000
 2 Bond angle potential               :    3483       0      6   1.921   1.921      258.02       1.000
 3 Stereochemical cosine torsion poten:    1598       0     58  48.757  48.757      606.76       1.000
 4 Stereochemical improper torsion pot:    1060       0      0   1.188   1.188      36.842       1.000
 5 Soft-sphere overlap restraints     :    5274       0      0   0.001   0.001      1.0280       1.000
 6 Lennard-Jones 6-12 potential       :       0       0      0   0.000   0.000      0.0000       1.000
 7 Coulomb point-point electrostatic p:       0       0      0   0.000   0.000      0.0000       1.000
 8 H-bonding potential                :       0       0      0   0.000   0.000      0.0000       1.000
 9 Distance restraints 1 (CA-CA)      :    7479       0      0   0.090   0.090      74.885       1.000
10 Distance restraints 2 (N-O)        :    7599       4     17   0.184   0.184      254.78       1.000
11 Mainchain Phi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
12 Mainchain Psi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
13 Mainchain Omega dihedral restraints:     332       0      3   3.873   3.873      58.733       1.000
14 Sidechain Chi_1 dihedral restraints:     270       0      0  46.212  46.212     -3.6380       1.000
15 Sidechain Chi_2 dihedral restraints:     193       0      3  63.069  63.069      65.228       1.000
16 Sidechain Chi_3 dihedral restraints:      77       0      0  65.408  65.408      41.404       1.000
17 Sidechain Chi_4 dihedral restraints:      36       0      0  89.060  89.060      23.993       1.000
18 Disulfide distance restraints      :       0       0      0   0.000   0.000      0.0000       1.000
19 Disulfide angle restraints         :       0       0      0   0.000   0.000      0.0000       1.000
20 Disulfide dihedral angle restraints:       0       0      0   0.000   0.000      0.0000       1.000
21 Lower bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
22 Upper bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
23 Distance restraints 3 (SDCH-MNCH)  :    5332       0      0   0.364   0.364      130.66       1.000
24 Sidechain Chi_5 dihedral restraints:       0       0      0   0.000   0.000      0.0000       1.000
25 Phi/Psi pair of dihedral restraints:     331      12     36  29.875  36.219      149.89       1.000
26 Distance restraints 4 (SDCH-SDCH)  :    3122       0      1   0.669   0.669      195.00       1.000
27 Distance restraints 5 (X-Y)        :       0       0      0   0.000   0.000      0.0000       1.000
28 NMR distance restraints 6 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
29 NMR distance restraints 7 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
30 Minimal distance restraints        :       0       0      0   0.000   0.000      0.0000       1.000
31 Non-bonded restraints              :       0       0      0   0.000   0.000      0.0000       1.000
32 Atomic accessibility restraints    :       0       0      0   0.000   0.000      0.0000       1.000
33 Atomic density restraints          :       0       0      0   0.000   0.000      0.0000       1.000
34 Absolute position restraints       :       0       0      0   0.000   0.000      0.0000       1.000
35 Dihedral angle difference restraint:       0       0      0   0.000   0.000      0.0000       1.000
36 GBSA implicit solvent potential    :       0       0      0   0.000   0.000      0.0000       1.000
37 EM density fitting potential       :       0       0      0   0.000   0.000      0.0000       1.000
38 SAXS restraints                    :       0       0      0   0.000   0.000      0.0000       1.000
39 Symmetry restraints                :       0       0      0   0.000   0.000      0.0000       1.000



openf___224_> Open           1U8F.V99990001
# Heavy relative violation of each residue is written to: 1U8F.V99990001
# The profile is NOT normalized by the number of restraints.
# The profiles are smoothed over a window of residues:    1
# The sum of all numbers in the file:   26927.2520



List of the violated restraints:
   A restraint is violated when the relative difference
   from the best value (RVIOL) is larger than CUTOFF.

   ICSR   ... index of a restraint in the current set.
   RESNO  ... residue numbers of the first two atoms.
   ATM    ... IUPAC atom names of the first two atoms.
   FEAT   ... the value of the feature in the model.
   restr  ... the mean of the basis restraint with the smallest
              difference from the model (local minimum).
   viol   ... difference from the local minimum.
   rviol  ... relative difference from the local minimum.
   RESTR  ... the best value (global minimum).
   VIOL   ... difference from the best value.
   RVIOL  ... relative difference from the best value.


-------------------------------------------------------------------------------------------------

Feature 25                           : Phi/Psi pair of dihedral restraints
List of the RVIOL violations larger than   :       6.5000

    #   ICSR  RESNO1/2 ATM1/2   INDATM1/2    FEAT   restr    viol   rviol   RESTR    VIOL   RVIOL
    1   8722   8G   9F C   N      54   56  -88.24  -63.20   57.04    6.56  -63.20   57.04    6.56
    1          9F   9F N   CA     56   57    6.94  -44.30                  -44.30
    2   8781  67I  68N C   N     522  524   60.23  -63.20  165.30   18.80   55.90  169.51   12.18
    2         68N  68N N   CA    524  525 -151.05  -41.10                   39.50
    3   8782  68N  69G C   N     530  532  -74.45  -62.40   25.15    3.41   82.20  159.07   11.56
    3         69G  69G N   CA    532  533  -19.13  -41.20                    8.50
    4   8809  95E  96S C   N     743  745 -128.55  -64.10   90.32    7.37  -64.10   90.32    7.37
    4         96S  96S N   CA    745  746   28.28  -35.00                  -35.00
    5   8813  99V 100F C   N     767  769  -88.74  -63.20   67.36    7.88  -63.20   67.36    7.88
    5        100F 100F N   CA    769  770   18.02  -44.30                  -44.30
    6   8847 133V 134N C   N    1009 1011 -149.10 -119.90  110.13    5.59  -63.20  112.03   12.88
    6        134N 134N N   CA   1011 1012   30.81  137.00                  -41.10
    7   8861 147N 148A C   N    1126 1128   83.08 -134.00  152.11    3.53  -62.50 -171.32   29.84
    7        148A 148A N   CA   1128 1129 -160.92  147.00                  -40.90
    8   8902 188G 189P C   N    1420 1422  -34.45  -58.70   70.70    4.27  -64.50  119.73   10.57
    8        189P 189P N   CA   1422 1423  -96.91  -30.50                  147.20
    9   8903 189P 190S C   N    1427 1429  115.91 -136.60  158.94    5.25  -64.10 -171.29   25.24
    9        190S 190S N   CA   1429 1430  -91.72  151.20                  -35.00
   10   8904 190S 191G C   N    1433 1435   84.32   82.20   95.66    4.54  -62.40  153.74   25.23
   10        191G 191G N   CA   1435 1436  -87.13    8.50                  -41.20
   11   8982 268L 269K C   N    2012 2014   15.70  -62.90  108.17   13.28  -70.20  135.26   11.29
   11        269K 269K N   CA   2014 2015 -115.12  -40.80                  140.40
   12   8983 269K 270G C   N    2021 2023  -61.34  -62.40   20.34    3.09   82.20  146.52   10.75
   12        270G 270G N   CA   2023 2024  -20.89  -41.20                    8.50

report______> Distribution of short non-bonded contacts:


DISTANCE1:  0.00 2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40
DISTANCE2:  2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40 3.50
FREQUENCY:     0    0    0    0    0   11   32   76  164  183  232  278  360  354  409


<< end of ENERGY.
openf___224_> Open           1U8F.B99990001.pdb
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523

>> Summary of successfully produced models:
Filename                          molpdf     DOPE score    GA341 score
----------------------------------------------------------------------
1U8F.B99990001.pdb            1914.53333   -37930.83203        1.00000

>> modelling missing residues
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainB.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534739    5405.019     5.278

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5534815    5405.093     5.278

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534986    5405.260     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5535836    5406.090     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5537094    5407.318     5.281

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5538998    5409.178     5.282

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5539038    5409.217     5.282

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5539128    5409.305     5.283

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5541984    5412.094     5.285

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5542044    5412.152     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5542179    5412.284     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546463    5416.468     5.290

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546551    5416.554     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546749    5416.747     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553175    5423.022     5.296

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5553307    5423.151     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553604    5423.441     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563226    5432.838     5.306

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5563426    5433.033     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563876    5433.473     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5578326    5447.584     5.320

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5578626    5447.877     5.320

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5579301    5448.536     5.321

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5600959    5469.687     5.341

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5601407    5470.124     5.342

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5602415    5471.108     5.343

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5634919    5502.851     5.374

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      5866791    5729.288     5.595
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  3:B  335:B     2523

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5877400    5739.648     5.605

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6067423    5925.218     5.786
openf___224_> Open           result\curated\tmp\chainB.seq
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainB.fasta

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5526104    5396.586     5.270

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5527554    5398.002     5.271

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5530454    5400.834     5.274

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536254    5406.498     5.280

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5537590    5407.803     5.281

Read the alignment from file       : result\curated\tmp\chainB.fasta

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  1U8F_1|Ch     335      1
openf___224_> Open           result\curated\tmp\chainB.pir
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib

openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5535475    5405.737     5.279

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536925    5407.153     5.280

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5539825    5409.985     5.283

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5545625    5415.649     5.289

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546953    5416.946     5.290

Read the alignment from file       : alignment.seg

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5676161    5543.126     5.413

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5677497    5544.431     5.414

Read the alignment from file       : alignment.seg

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     335      1        1U8F
openf___224_> Open           $(LIB)/as1.sim.mat
rdrrwgh_268_> Number of residue types:       20

Pairwise dynamic programming alignment (ALIGN):
  Residue-residue metric   : $(LIB)/as1.sim.mat
  Diagonal                 :          100
  Overhang                 :            0
  Local alignment          :            F
  MATRIX_OFFSET (local aln):       0.0000
  N_SUBOPT                 :            0
  SUBOPT_OFFSET            :       0.0000
  Alignment block          :            1
  Gap introduction penalty :    -600.0000
  Gap extension penalty    :    -400.0000
  Break-break bonus        :   10000.0000
  Length of alignment      :          335
  Score                    :  292963.0000
openf___224_> Open           alignment.seg.ali

Sequence identity comparison (ID_TABLE):

   Diagonal       ... number of residues;
   Upper triangle ... number of identical residues;
   Lower triangle ... % sequence identity, id/min(length).

         result@11U8F  @1
result@1      333     333
1U8F  @1      100     335
>> patching model...
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724447    5590.280     5.459

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724975    5590.796     5.460
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5773575    5638.257     5.506
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5786875    5651.245     5.519
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           trimmed_align.ali

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5798840    5662.930     5.530

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5800290    5664.346     5.532

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5803190    5667.178     5.534

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5808990    5672.842     5.540

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5938198    5799.021     5.663

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5939526    5800.318     5.664

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5940854    5801.615     5.666

Read the alignment from file       : trimmed_align.ali

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     333      1        1U8F
check_a_343_> >> BEGINNING OF COMMAND
openf___224_> Open           .\result\curated\tmp\chainB.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042650    5901.025     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6043500    5901.855     5.764

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6044758    5903.084     5.765

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046752    5905.031     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049743    5907.952     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054225    5912.329     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060948    5918.895     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6071020    5928.730     5.790

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6086145    5943.501     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6108811    5965.636     5.826

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6141315    5997.378     5.857

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6141279    5997.343     5.857

check_ali___> Checking the sequence-structure alignment.

Implied intrachain target CA(i)-CA(i+1) distances longer than  8.0 angstroms:

ALN_POS  TMPL  RID1  RID2  NAM1  NAM2     DIST
----------------------------------------------
END OF TABLE
check_a_344_> << END OF COMMAND
openf___224_> Open           ${LIB}/top_heav.lib
read_to_681_> topology.submodel read from topology file:        3

openf___224_> Open           ${LIB}/par.lib

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6280531    6133.331     5.990

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6282131    6134.894     5.991

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6286111    6138.780     5.995

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6288111    6140.733     5.997

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6291111    6143.663     6.000

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6295611    6148.058     6.004

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6301183    6153.499     6.009

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6303983    6156.233     6.012

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6308183    6160.335     6.016

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6314483    6166.487     6.022

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6317255    6169.194     6.025

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6318655    6170.562     6.026
read_pa_232_> parameters    BONDS   ANGLS  DIHEDS IMPROPS    MODE
                              227     561     661     112       0

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6370779    6221.464     6.076

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6619797    6464.646     6.313

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6657509    6501.474     6.349

mkilst______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572      0         0      1071

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6765141    6606.583     6.452

patch_______> segment topology patched using RTF:  1 ;  LYS  ;  NTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572   3481      4118      1071


Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6875637    6714.489     6.557
patch_______> segment topology patched using RTF:  333 ;  GLU  ;  CTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072

genseg______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072
transfe_506_> MODEL is an average of all templates.
transfe_511_> Number of templates for coordinate transfer:        1
              After transferring coordinates of the equivalent template atoms,
              there are defined, undefined atoms in MODEL:     2523        0
openf___224_> Open           1U8F.ini
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523
make_re_417_> Restraint type to be calculated:  stereo

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6983086    6819.420     6.660

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6991278    6827.420     6.667

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7007662    6843.420     6.683

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7040430    6875.420     6.714

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7073198    6907.420     6.746

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7138734    6971.420     6.808

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7171502    7003.420     6.839

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7204270    7035.420     6.871

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7269806    7099.420     6.933

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7400878    7227.420     7.058

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7466414    7291.420     7.121

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7531950    7355.420     7.183

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7663022    7483.420     7.308

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7925166    7739.420     7.558

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8056238    7867.420     7.683
r_stere_606_> Stereochemical restraints were constructed from RTF & PRMF.
              Added bond,angle,dihedral,improper restraints  :     2573    3483    3913    1060
              Total number of restraints before, now         :        0    11029
make_re_422_> Number of previous, current restraints         :        0    11029
make_re_423_> Number of previous, current selected restraints:        0    11029
make_re_417_> Restraint type to be calculated:  phi-psi_binormal

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243952    8050.734     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11029    11360
make_re_423_> Number of previous, current selected restraints:    11029    11360
make_re_417_> Restraint type to be calculated:  omega_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
omgdel__425_> Unselected all O C +N +CA dihedrals:      344
              (This is to avoid clashes between STEREO
              and OMEGA_DIHEDRAL restraints)
make_re_422_> Number of previous, current restraints         :    11360    11692
make_re_423_> Number of previous, current selected restraints:    11360    11348
make_re_417_> Restraint type to be calculated:  chi1_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8375040    8178.750     7.987
make_re_422_> Number of previous, current restraints         :    11692    11962
make_re_423_> Number of previous, current selected restraints:    11348    11618
make_re_417_> Restraint type to be calculated:  chi2_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi2.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11962    12155
make_re_423_> Number of previous, current selected restraints:    11618    11811
make_re_417_> Restraint type to be calculated:  chi3_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi3.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12155    12232
make_re_423_> Number of previous, current selected restraints:    11811    11888
make_re_417_> Restraint type to be calculated:  chi4_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi4.mdt
mdtrsr__446W> A potential that relies on one protein is used, yet you have at
              least one known structure available. MDT, not library, potential is used.
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12232    12268
make_re_423_> Number of previous, current selected restraints:    11888    11924
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at amaxhash_contac [B,KiB,MiB]:      9101628    8888.309     8.680

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9363772    9144.309     8.930

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9625916    9400.309     9.180

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10150204    9912.309     9.680
make_re_422_> Number of previous, current restraints         :    12268    19778
make_re_423_> Number of previous, current selected restraints:    11924    19434
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10412348   10168.309     9.930
make_re_422_> Number of previous, current restraints         :    19778    27395
make_re_423_> Number of previous, current selected restraints:    19434    27051
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    27395    32710
make_re_423_> Number of previous, current selected restraints:    27051    32366
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10936636   10680.309    10.430
make_re_422_> Number of previous, current restraints         :    32710    35871
make_re_423_> Number of previous, current selected restraints:    32366    35527
0 atoms in HETATM/BLK residues constrained
to protein atoms within 2.30 angstroms
and protein CA atoms within 10.00 angstroms
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35871    35871
make_re_423_> Number of previous, current selected restraints:    35527    35527
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35871    35871
make_re_423_> Number of previous, current selected restraints:    35527    35527
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35871    35871
make_re_423_> Number of previous, current selected restraints:    35527    35527
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35871    35871
make_re_423_> Number of previous, current selected restraints:    35527    35527
0 atoms in residues without defined topology
constrained to be rigid bodies
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35871    35871
make_re_423_> Number of previous, current selected restraints:    35527    35527
rmdupl__427_>     1971 redundant cosine dihedral restraints were unselected.
condens_443_> Restraints marked for deletion were removed.
              Total number of restraints before, now:    35871    33556
openf___224_> Open           1U8F.rsr
openf___224_> Open           1U8F.rsr

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10927372   10671.262    10.421

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11713804   11439.262    11.171
rdcsr2__307_> Number of restraints read    :    33556
              Number of excluded pairs read:        0
              Number of pseudo atoms read  :        0
rdcsrs__304_> Restraints in memory, selected restraints:    33556    33556
              Explicitly excluded atom pairs in memory :        0
              Pseudo atoms in memory                   :        0
openf___224_> Open           1U8F.ini

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:     11713836   11439.293    11.171
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  1:A  333:A     2523
randomi_498_> Atoms,selected atoms,random_seed,amplitude:     2523     2523        1        4.0000
randomi_496_> Amplitude is > 0; randomization is done.
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    16513
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    18656
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    19822
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    21209
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    23199
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    25446
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    27357
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    29659
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    31083

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12066960   11784.141    11.508
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    32509
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33117
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33556
iupac_m_485_> OD1/2 will be swapped:      115.3087       37  37
iupac_m_483_> CD1/2 CE1/2 swapped:       92.6430       43  43
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_483_> CD1/2 CE1/2 swapped:     -104.8816       45  45
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_483_> CD1/2 CE1/2 swapped:       91.6730       47  47
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_485_> OD1/2 will be swapped:       99.9320       48  48
iupac_m_487_> NH1/2 swapped:      176.5883      116  116
iupac_m_486_> OE1/2 will be swapped:     -170.9388      136  136
iupac_m_487_> NH1/2 swapped:      177.4589      198  198
iupac_m_485_> OD1/2 will be swapped:      163.7524      242  242
iupac_m_487_> NH1/2 swapped:     -175.9494      246  246
iupac_m_485_> OD1/2 will be swapped:      115.2218      254  254
iupac_m_486_> OE1/2 will be swapped:     -150.6813      315  315
iupac_m_487_> NH1/2 swapped:      179.3051      321  321
>> Model assessment by DOPE potential
iatmcls_286W> MODEL atom not classified:  GLU:OXT  GLU

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12420284   12129.184    11.845

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12541388   12247.449    11.960

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12783596   12483.980    12.191

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     13268012   12957.043    12.653

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     14236844   13903.168    13.577

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     16174508   15795.418    15.425

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     20049836   19579.918    19.121


>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33556   33556
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):   507874
Dynamic pairs routine                             : 1, NATM x NATM double loop
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        1    9999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :   15.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       F       F       F       T
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :      -37644.3516




<< end of ENERGY.
DOPE score               : -37644.351562
>> Model assessment by GA341 potential

Surface library          : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/surf5.de
Pair library             : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/pair9.de
Chain identifier         : _
% sequence identity      :   100.000000

Sequence length          :          333
Compactness              :     0.242062
Native energy (pair)     :  -292.978823
Native energy (surface)  :   -16.481480
Native energy (combined) :    -9.383596
Z score (pair)           :   -10.209419
Z score (surface)        :    -7.333526
Z score (combined)       :   -11.868685
GA341 score              :     1.000000



>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33556   33556
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):     5390
Dynamic pairs routine                             : 2, NATM x NATM cell sorting
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        0   99999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :    4.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       T       F       F       F
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :        1912.9177





Summary of the restraint violations:

   NUM     ... number of restraints.
   NUMVI   ... number of restraints with RVIOL > VIOL_REPORT_CUT[i].
   RVIOL   ... relative difference from the best value.
   NUMVP   ... number of restraints with -Ln(pdf) > VIOL_REPORT_CUT2[i].
   RMS_1   ... RMS(feature, minimally_violated_basis_restraint, NUMB).
   RMS_2   ... RMS(feature, best_value, NUMB).
   MOL.PDF ... scaled contribution to -Ln(Molecular pdf).

 #                     RESTRAINT_GROUP      NUM   NUMVI  NUMVP   RMS_1   RMS_2         MOL.PDF     S_i
------------------------------------------------------------------------------------------------------
 1 Bond length potential              :    2573       0      0   0.006   0.006      21.848       1.000
 2 Bond angle potential               :    3483       0     10   1.997   1.997      272.92       1.000
 3 Stereochemical cosine torsion poten:    1598       0     53  48.887  48.887      610.19       1.000
 4 Stereochemical improper torsion pot:    1060       0      0   1.198   1.198      35.807       1.000
 5 Soft-sphere overlap restraints     :    5390       0      0   0.001   0.001      1.0860       1.000
 6 Lennard-Jones 6-12 potential       :       0       0      0   0.000   0.000      0.0000       1.000
 7 Coulomb point-point electrostatic p:       0       0      0   0.000   0.000      0.0000       1.000
 8 H-bonding potential                :       0       0      0   0.000   0.000      0.0000       1.000
 9 Distance restraints 1 (CA-CA)      :    7510       0      0   0.084   0.084      65.603       1.000
10 Distance restraints 2 (N-O)        :    7617       0      5   0.147   0.147      157.56       1.000
11 Mainchain Phi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
12 Mainchain Psi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
13 Mainchain Omega dihedral restraints:     332       0      2   3.977   3.977      61.937       1.000
14 Sidechain Chi_1 dihedral restraints:     270       0      6  53.837  53.837      31.942       1.000
15 Sidechain Chi_2 dihedral restraints:     193       0      3  62.308  62.308      62.863       1.000
16 Sidechain Chi_3 dihedral restraints:      77       0      0  67.900  67.900      51.748       1.000
17 Sidechain Chi_4 dihedral restraints:      36       0      0  87.635  87.635      23.208       1.000
18 Disulfide distance restraints      :       0       0      0   0.000   0.000      0.0000       1.000
19 Disulfide angle restraints         :       0       0      0   0.000   0.000      0.0000       1.000
20 Disulfide dihedral angle restraints:       0       0      0   0.000   0.000      0.0000       1.000
21 Lower bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
22 Upper bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
23 Distance restraints 3 (SDCH-MNCH)  :    5315       0      1   0.374   0.374      142.83       1.000
24 Sidechain Chi_5 dihedral restraints:       0       0      0   0.000   0.000      0.0000       1.000
25 Phi/Psi pair of dihedral restraints:     331       7     31  26.793  31.783      107.26       1.000
26 Distance restraints 4 (SDCH-SDCH)  :    3161       0     13   0.774   0.774      266.13       1.000
27 Distance restraints 5 (X-Y)        :       0       0      0   0.000   0.000      0.0000       1.000
28 NMR distance restraints 6 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
29 NMR distance restraints 7 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
30 Minimal distance restraints        :       0       0      0   0.000   0.000      0.0000       1.000
31 Non-bonded restraints              :       0       0      0   0.000   0.000      0.0000       1.000
32 Atomic accessibility restraints    :       0       0      0   0.000   0.000      0.0000       1.000
33 Atomic density restraints          :       0       0      0   0.000   0.000      0.0000       1.000
34 Absolute position restraints       :       0       0      0   0.000   0.000      0.0000       1.000
35 Dihedral angle difference restraint:       0       0      0   0.000   0.000      0.0000       1.000
36 GBSA implicit solvent potential    :       0       0      0   0.000   0.000      0.0000       1.000
37 EM density fitting potential       :       0       0      0   0.000   0.000      0.0000       1.000
38 SAXS restraints                    :       0       0      0   0.000   0.000      0.0000       1.000
39 Symmetry restraints                :       0       0      0   0.000   0.000      0.0000       1.000



openf___224_> Open           1U8F.V99990001
# Heavy relative violation of each residue is written to: 1U8F.V99990001
# The profile is NOT normalized by the number of restraints.
# The profiles are smoothed over a window of residues:    1
# The sum of all numbers in the file:   27113.7266



List of the violated restraints:
   A restraint is violated when the relative difference
   from the best value (RVIOL) is larger than CUTOFF.

   ICSR   ... index of a restraint in the current set.
   RESNO  ... residue numbers of the first two atoms.
   ATM    ... IUPAC atom names of the first two atoms.
   FEAT   ... the value of the feature in the model.
   restr  ... the mean of the basis restraint with the smallest
              difference from the model (local minimum).
   viol   ... difference from the local minimum.
   rviol  ... relative difference from the local minimum.
   RESTR  ... the best value (global minimum).
   VIOL   ... difference from the best value.
   RVIOL  ... relative difference from the best value.


-------------------------------------------------------------------------------------------------

Feature 25                           : Phi/Psi pair of dihedral restraints
List of the RVIOL violations larger than   :       6.5000

    #   ICSR  RESNO1/2 ATM1/2   INDATM1/2    FEAT   restr    viol   rviol   RESTR    VIOL   RVIOL
    1   8722   8G   9F C   N      54   56  -76.14  -63.20   55.66    6.91  -63.20   55.66    6.91
    1          9F   9F N   CA     56   57    9.83  -44.30                  -44.30
    2   8797  83I  84K C   N     650  652  -76.33  -62.90   69.52    8.39  -62.90   69.52    8.39
    2         84K  84K N   CA    652  653   27.41  -40.80                  -40.80
    3   8809  95E  96S C   N     743  745 -124.61  -64.10   92.99    7.05  -64.10   92.99    7.05
    3         96S  96S N   CA    745  746   35.61  -35.00                  -35.00
    4   8847 133V 134N C   N    1009 1011 -152.27 -119.90  112.58    5.75  -63.20  113.45   13.19
    4        134N 134N N   CA   1011 1012   29.18  137.00                  -41.10
    5   8861 147N 148A C   N    1126 1128   86.59 -134.00  148.33    3.45  -62.50 -167.70   30.46
    5        148A 148A N   CA   1128 1129 -162.35  147.00                  -40.90
    6   8902 188G 189P C   N    1420 1422  -43.31  -58.70   53.03    3.32  -64.50  133.25   11.09
    6        189P 189P N   CA   1422 1423  -81.25  -30.50                  147.20
    7   8947 233V 234P C   N    1746 1748  -66.41  -64.50   53.14    4.07  -58.70  124.83    9.70
    7        234P 234P N   CA   1748 1749   94.09  147.20                  -30.50


report______> Distribution of short non-bonded contacts:

DISTANCE1:  0.00 2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40
DISTANCE2:  2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40 3.50
FREQUENCY:     0    0    0    0    0    7   39   99  167  197  228  301  327  402  422


<< end of ENERGY.
openf___224_> Open           1U8F.B99990001.pdb
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523

>> Summary of successfully produced models:
Filename                          molpdf     DOPE score    GA341 score
----------------------------------------------------------------------
1U8F.B99990001.pdb            1912.91772   -37644.35156        1.00000

>> modelling missing residues
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainC.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534739    5405.019     5.278

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5534815    5405.093     5.278

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534986    5405.260     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5535836    5406.090     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5537094    5407.318     5.281

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5538998    5409.178     5.282

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5539038    5409.217     5.282

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5539128    5409.305     5.283

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5541984    5412.094     5.285

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5542044    5412.152     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5542179    5412.284     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546463    5416.468     5.290

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546551    5416.554     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546749    5416.747     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553175    5423.022     5.296

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5553307    5423.151     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553604    5423.441     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563226    5432.838     5.306

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5563426    5433.033     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563876    5433.473     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5578326    5447.584     5.320

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5578626    5447.877     5.320

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5579301    5448.536     5.321

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5600959    5469.687     5.341

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5601407    5470.124     5.342

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5602415    5471.108     5.343

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5634919    5502.851     5.374

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      5866791    5729.288     5.595
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  3:C  335:C     2523

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5877400    5739.648     5.605

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6067423    5925.218     5.786
openf___224_> Open           result\curated\tmp\chainC.seq
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainC.fasta

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5526104    5396.586     5.270

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5527554    5398.002     5.271

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5530454    5400.834     5.274

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536254    5406.498     5.280

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5537590    5407.803     5.281

Read the alignment from file       : result\curated\tmp\chainC.fasta

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  1U8F_1|Ch     335      1
openf___224_> Open           result\curated\tmp\chainC.pir
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib

openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5535475    5405.737     5.279

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536925    5407.153     5.280

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5539825    5409.985     5.283

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5545625    5415.649     5.289

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546953    5416.946     5.290

Read the alignment from file       : alignment.seg

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5676161    5543.126     5.413

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5677497    5544.431     5.414

Read the alignment from file       : alignment.seg

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     335      1        1U8F
openf___224_> Open           $(LIB)/as1.sim.mat
rdrrwgh_268_> Number of residue types:       20

Pairwise dynamic programming alignment (ALIGN):
  Residue-residue metric   : $(LIB)/as1.sim.mat
  Diagonal                 :          100
  Overhang                 :            0
  Local alignment          :            F
  MATRIX_OFFSET (local aln):       0.0000
  N_SUBOPT                 :            0
  SUBOPT_OFFSET            :       0.0000
  Alignment block          :            1
  Gap introduction penalty :    -600.0000
  Gap extension penalty    :    -400.0000
  Break-break bonus        :   10000.0000
  Length of alignment      :          335
  Score                    :  292963.0000
openf___224_> Open           alignment.seg.ali

Sequence identity comparison (ID_TABLE):

   Diagonal       ... number of residues;
   Upper triangle ... number of identical residues;
   Lower triangle ... % sequence identity, id/min(length).

         result@11U8F  @1
result@1      333     333
1U8F  @1      100     335
>> patching model...
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724447    5590.280     5.459

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724975    5590.796     5.460
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5773575    5638.257     5.506
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5786875    5651.245     5.519
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           trimmed_align.ali

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5798840    5662.930     5.530

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5800290    5664.346     5.532

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5803190    5667.178     5.534

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5808990    5672.842     5.540

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5938198    5799.021     5.663

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5939526    5800.318     5.664

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5940854    5801.615     5.666

Read the alignment from file       : trimmed_align.ali

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     333      1        1U8F
check_a_343_> >> BEGINNING OF COMMAND
openf___224_> Open           .\result\curated\tmp\chainC.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042650    5901.025     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6043500    5901.855     5.764

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6044758    5903.084     5.765

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046752    5905.031     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049743    5907.952     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054225    5912.329     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060948    5918.895     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6071020    5928.730     5.790

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6086145    5943.501     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6108811    5965.636     5.826

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6141315    5997.378     5.857

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6141279    5997.343     5.857

check_ali___> Checking the sequence-structure alignment.

Implied intrachain target CA(i)-CA(i+1) distances longer than  8.0 angstroms:

ALN_POS  TMPL  RID1  RID2  NAM1  NAM2     DIST
----------------------------------------------
END OF TABLE
check_a_344_> << END OF COMMAND
openf___224_> Open           ${LIB}/top_heav.lib
read_to_681_> topology.submodel read from topology file:        3

openf___224_> Open           ${LIB}/par.lib

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6280531    6133.331     5.990

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6282131    6134.894     5.991

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6286111    6138.780     5.995

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6288111    6140.733     5.997

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6291111    6143.663     6.000

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6295611    6148.058     6.004

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6301183    6153.499     6.009

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6303983    6156.233     6.012

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6308183    6160.335     6.016

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6314483    6166.487     6.022

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6317255    6169.194     6.025

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6318655    6170.562     6.026
read_pa_232_> parameters    BONDS   ANGLS  DIHEDS IMPROPS    MODE
                              227     561     661     112       0

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6370779    6221.464     6.076

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6619797    6464.646     6.313

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6657509    6501.474     6.349

mkilst______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572      0         0      1071

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6765141    6606.583     6.452

patch_______> segment topology patched using RTF:  1 ;  LYS  ;  NTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572   3481      4118      1071


Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6875637    6714.489     6.557
patch_______> segment topology patched using RTF:  333 ;  GLU  ;  CTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072

genseg______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072
transfe_506_> MODEL is an average of all templates.
transfe_511_> Number of templates for coordinate transfer:        1
              After transferring coordinates of the equivalent template atoms,
              there are defined, undefined atoms in MODEL:     2523        0
openf___224_> Open           1U8F.ini
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523
make_re_417_> Restraint type to be calculated:  stereo

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6983086    6819.420     6.660

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6991278    6827.420     6.667

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7007662    6843.420     6.683

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7040430    6875.420     6.714

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7073198    6907.420     6.746

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7138734    6971.420     6.808

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7171502    7003.420     6.839

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7204270    7035.420     6.871

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7269806    7099.420     6.933

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7400878    7227.420     7.058

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7466414    7291.420     7.121

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7531950    7355.420     7.183

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7663022    7483.420     7.308

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7925166    7739.420     7.558

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8056238    7867.420     7.683
r_stere_606_> Stereochemical restraints were constructed from RTF & PRMF.
              Added bond,angle,dihedral,improper restraints  :     2573    3483    3913    1060
              Total number of restraints before, now         :        0    11029
make_re_422_> Number of previous, current restraints         :        0    11029
make_re_423_> Number of previous, current selected restraints:        0    11029
make_re_417_> Restraint type to be calculated:  phi-psi_binormal

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243952    8050.734     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainC
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11029    11360
make_re_423_> Number of previous, current selected restraints:    11029    11360
make_re_417_> Restraint type to be calculated:  omega_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainC
getdata_289_> Proteins (all/accepted):        1        1
omgdel__425_> Unselected all O C +N +CA dihedrals:      344
              (This is to avoid clashes between STEREO
              and OMEGA_DIHEDRAL restraints)
make_re_422_> Number of previous, current restraints         :    11360    11692
make_re_423_> Number of previous, current selected restraints:    11360    11348
make_re_417_> Restraint type to be calculated:  chi1_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainC
getdata_289_> Proteins (all/accepted):        1        1

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8375040    8178.750     7.987
make_re_422_> Number of previous, current restraints         :    11692    11962
make_re_423_> Number of previous, current selected restraints:    11348    11618
make_re_417_> Restraint type to be calculated:  chi2_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi2.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainC
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11962    12155
make_re_423_> Number of previous, current selected restraints:    11618    11811
make_re_417_> Restraint type to be calculated:  chi3_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi3.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainC
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12155    12232
make_re_423_> Number of previous, current selected restraints:    11811    11888
make_re_417_> Restraint type to be calculated:  chi4_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi4.mdt
mdtrsr__446W> A potential that relies on one protein is used, yet you have at
              least one known structure available. MDT, not library, potential is used.
getdata_643_> Protein accepted:  result\curated\tmp\chainC
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12232    12268
make_re_423_> Number of previous, current selected restraints:    11888    11924
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at amaxhash_contac [B,KiB,MiB]:      9101628    8888.309     8.680

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9363772    9144.309     8.930

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9625916    9400.309     9.180

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10150204    9912.309     9.680
make_re_422_> Number of previous, current restraints         :    12268    19764
make_re_423_> Number of previous, current selected restraints:    11924    19420
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10412348   10168.309     9.930
make_re_422_> Number of previous, current restraints         :    19764    27366
make_re_423_> Number of previous, current selected restraints:    19420    27022
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    27366    32694
make_re_423_> Number of previous, current selected restraints:    27022    32350
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10936636   10680.309    10.430
make_re_422_> Number of previous, current restraints         :    32694    35883
make_re_423_> Number of previous, current selected restraints:    32350    35539
0 atoms in HETATM/BLK residues constrained
to protein atoms within 2.30 angstroms
and protein CA atoms within 10.00 angstroms
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35883    35883
make_re_423_> Number of previous, current selected restraints:    35539    35539
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35883    35883
make_re_423_> Number of previous, current selected restraints:    35539    35539
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35883    35883
make_re_423_> Number of previous, current selected restraints:    35539    35539
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35883    35883
make_re_423_> Number of previous, current selected restraints:    35539    35539
0 atoms in residues without defined topology
constrained to be rigid bodies
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35883    35883
make_re_423_> Number of previous, current selected restraints:    35539    35539
rmdupl__427_>     1971 redundant cosine dihedral restraints were unselected.
condens_443_> Restraints marked for deletion were removed.
              Total number of restraints before, now:    35883    33568
openf___224_> Open           1U8F.rsr
openf___224_> Open           1U8F.rsr

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10927372   10671.262    10.421

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11713804   11439.262    11.171
rdcsr2__307_> Number of restraints read    :    33568
              Number of excluded pairs read:        0
              Number of pseudo atoms read  :        0
rdcsrs__304_> Restraints in memory, selected restraints:    33568    33568
              Explicitly excluded atom pairs in memory :        0
              Pseudo atoms in memory                   :        0
openf___224_> Open           1U8F.ini

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:     11713836   11439.293    11.171
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  1:A  333:A     2523
randomi_498_> Atoms,selected atoms,random_seed,amplitude:     2523     2523        1        4.0000
randomi_496_> Amplitude is > 0; randomization is done.
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    16538
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    18703
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    19865
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    21253
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    23264
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    25499
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    27397
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    29702
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    31123

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12066960   11784.141    11.508
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    32532
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33140
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33568
iupac_m_487_> NH1/2 swapped:     -175.2090       14  14
iupac_m_485_> OD1/2 will be swapped:      171.5155       37  37
iupac_m_487_> NH1/2 swapped:     -173.0182       78  78
iupac_m_487_> NH1/2 swapped:     -174.4510      232  232
iupac_m_485_> OD1/2 will be swapped:      172.5063      242  242
iupac_m_487_> NH1/2 swapped:     -179.7266      246  246
iupac_m_486_> OE1/2 will be swapped:      176.1358      248  248
iupac_m_485_> OD1/2 will be swapped:      110.0863      255  255
iupac_m_483_> CD1/2 CE1/2 swapped:       97.4038      312  312
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
>> Model assessment by DOPE potential
iatmcls_286W> MODEL atom not classified:  GLU:OXT  GLU

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12420284   12129.184    11.845

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12541388   12247.449    11.960

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12783596   12483.980    12.191

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     13268012   12957.043    12.653

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     14236844   13903.168    13.577

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     16174508   15795.418    15.425

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     20049836   19579.918    19.121


>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33568   33568
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):   506509
Dynamic pairs routine                             : 1, NATM x NATM double loop
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        1    9999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :   15.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       F       F       F       T
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :      -37985.2656




<< end of ENERGY.
DOPE score               : -37985.265625
>> Model assessment by GA341 potential

Surface library          : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/surf5.de
Pair library             : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/pair9.de
Chain identifier         : _
% sequence identity      :   100.000000
Sequence length          :          333
Compactness              :     0.240654
Native energy (pair)     :  -284.248102
Native energy (surface)  :   -16.247874
Native energy (combined) :    -9.173707
Z score (pair)           :   -10.102678
Z score (surface)        :    -7.313092
Z score (combined)       :   -11.602765
GA341 score              :     1.000000



>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33568   33568
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):     5337
Dynamic pairs routine                             : 2, NATM x NATM cell sorting
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        0   99999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :    4.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       T       F       F       F
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :        1702.3469





Summary of the restraint violations:

   NUM     ... number of restraints.
   NUMVI   ... number of restraints with RVIOL > VIOL_REPORT_CUT[i].
   RVIOL   ... relative difference from the best value.
   NUMVP   ... number of restraints with -Ln(pdf) > VIOL_REPORT_CUT2[i].
   RMS_1   ... RMS(feature, minimally_violated_basis_restraint, NUMB).
   RMS_2   ... RMS(feature, best_value, NUMB).
   MOL.PDF ... scaled contribution to -Ln(Molecular pdf).

 #                     RESTRAINT_GROUP      NUM   NUMVI  NUMVP   RMS_1   RMS_2         MOL.PDF     S_i
------------------------------------------------------------------------------------------------------
 1 Bond length potential              :    2573       0      0   0.005   0.005      19.173       1.000
 2 Bond angle potential               :    3483       0      6   1.890   1.890      250.31       1.000
 3 Stereochemical cosine torsion poten:    1598       0     55  48.734  48.734      605.32       1.000
 4 Stereochemical improper torsion pot:    1060       0      0   1.144   1.144      33.336       1.000
 5 Soft-sphere overlap restraints     :    5337       0      0   0.001   0.001     0.50657       1.000
 6 Lennard-Jones 6-12 potential       :       0       0      0   0.000   0.000      0.0000       1.000
 7 Coulomb point-point electrostatic p:       0       0      0   0.000   0.000      0.0000       1.000
 8 H-bonding potential                :       0       0      0   0.000   0.000      0.0000       1.000
 9 Distance restraints 1 (CA-CA)      :    7496       0      0   0.080   0.080      59.989       1.000
10 Distance restraints 2 (N-O)        :    7602       0      1   0.134   0.134      138.14       1.000
11 Mainchain Phi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
12 Mainchain Psi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
13 Mainchain Omega dihedral restraints:     332       0      4   3.936   3.936      60.669       1.000
14 Sidechain Chi_1 dihedral restraints:     270       0      0  45.280  45.280     -2.4476       1.000
15 Sidechain Chi_2 dihedral restraints:     193       0      1  62.404  62.404      55.965       1.000
16 Sidechain Chi_3 dihedral restraints:      77       0      1  68.323  68.323      44.947       1.000
17 Sidechain Chi_4 dihedral restraints:      36       0      0  94.100  94.100      23.440       1.000
18 Disulfide distance restraints      :       0       0      0   0.000   0.000      0.0000       1.000
19 Disulfide angle restraints         :       0       0      0   0.000   0.000      0.0000       1.000
20 Disulfide dihedral angle restraints:       0       0      0   0.000   0.000      0.0000       1.000
21 Lower bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
22 Upper bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
23 Distance restraints 3 (SDCH-MNCH)  :    5328       0      0   0.334   0.334      115.28       1.000
24 Sidechain Chi_5 dihedral restraints:       0       0      0   0.000   0.000      0.0000       1.000
25 Phi/Psi pair of dihedral restraints:     331       8     31  26.548  30.188      121.13       1.000
26 Distance restraints 4 (SDCH-SDCH)  :    3189       0      0   0.626   0.626      176.59       1.000
27 Distance restraints 5 (X-Y)        :       0       0      0   0.000   0.000      0.0000       1.000
28 NMR distance restraints 6 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
29 NMR distance restraints 7 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
30 Minimal distance restraints        :       0       0      0   0.000   0.000      0.0000       1.000
31 Non-bonded restraints              :       0       0      0   0.000   0.000      0.0000       1.000
32 Atomic accessibility restraints    :       0       0      0   0.000   0.000      0.0000       1.000
33 Atomic density restraints          :       0       0      0   0.000   0.000      0.0000       1.000
34 Absolute position restraints       :       0       0      0   0.000   0.000      0.0000       1.000
35 Dihedral angle difference restraint:       0       0      0   0.000   0.000      0.0000       1.000
36 GBSA implicit solvent potential    :       0       0      0   0.000   0.000      0.0000       1.000
37 EM density fitting potential       :       0       0      0   0.000   0.000      0.0000       1.000
38 SAXS restraints                    :       0       0      0   0.000   0.000      0.0000       1.000
39 Symmetry restraints                :       0       0      0   0.000   0.000      0.0000       1.000



openf___224_> Open           1U8F.V99990001
# Heavy relative violation of each residue is written to: 1U8F.V99990001
# The profile is NOT normalized by the number of restraints.
# The profiles are smoothed over a window of residues:    1
# The sum of all numbers in the file:   25347.0586



List of the violated restraints:
   A restraint is violated when the relative difference
   from the best value (RVIOL) is larger than CUTOFF.

   ICSR   ... index of a restraint in the current set.
   RESNO  ... residue numbers of the first two atoms.
   ATM    ... IUPAC atom names of the first two atoms.
   FEAT   ... the value of the feature in the model.
   restr  ... the mean of the basis restraint with the smallest
              difference from the model (local minimum).
   viol   ... difference from the local minimum.
   rviol  ... relative difference from the local minimum.
   RESTR  ... the best value (global minimum).
   VIOL   ... difference from the best value.
   RVIOL  ... relative difference from the best value.

-------------------------------------------------------------------------------------------------

Feature 25                           : Phi/Psi pair of dihedral restraints
List of the RVIOL violations larger than   :       6.5000

    #   ICSR  RESNO1/2 ATM1/2   INDATM1/2    FEAT   restr    viol   rviol   RESTR    VIOL   RVIOL
    1   8722   8G   9F C   N      54   56  -77.51  -63.20   58.30    7.20  -63.20   58.30    7.20
    1          9F   9F N   CA     56   57   12.21  -44.30                  -44.30
    2   8809  95E  96S C   N     743  745 -128.66  -64.10   93.76    7.42  -64.10   93.76    7.42
    2         96S  96S N   CA    745  746   33.00  -35.00                  -35.00
    3   8813  99V 100F C   N     767  769  -89.81  -63.20   66.15    7.69  -63.20   66.15    7.69
    3        100F 100F N   CA    769  770   16.27  -44.30                  -44.30
    4   8847 133V 134N C   N    1009 1011 -150.60  -63.20  103.48   12.54  -63.20  103.48   12.54
    4        134N 134N N   CA   1011 1012   14.30  -41.10                  -41.10
    5   8860 146S 147N C   N    1118 1120 -104.18  -63.20   76.50    8.23  -63.20   76.50    8.23
    5        147N 147N N   CA   1120 1121   23.50  -41.10                  -41.10
    6   8861 147N 148A C   N    1126 1128   66.45  -68.20  144.22   13.70  -62.50  177.62   27.62
    6        148A 148A N   CA   1128 1129 -163.05  145.30                  -40.90
    7   8903 189P 190S C   N    1427 1429 -139.20  -64.10   85.26    8.68 -136.60  145.85    7.46
    7        190S 190S N   CA   1429 1430    5.37  -35.00                  151.20
    8   8904 190S 191G C   N    1433 1435   69.05   82.20  104.76    5.74  -62.40  142.20   22.67
    8        191G 191G N   CA   1435 1436  -95.43    8.50                  -41.20


report______> Distribution of short non-bonded contacts:


DISTANCE1:  0.00 2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40
DISTANCE2:  2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40 3.50
FREQUENCY:     0    0    0    0    0    8   29   98  160  205  194  322  348  378  421


<< end of ENERGY.
openf___224_> Open           1U8F.B99990001.pdb
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523

>> Summary of successfully produced models:
Filename                          molpdf     DOPE score    GA341 score
----------------------------------------------------------------------
1U8F.B99990001.pdb            1702.34692   -37985.26562        1.00000

>> modelling missing residues
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainD.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534739    5405.019     5.278

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5534815    5405.093     5.278

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534986    5405.260     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5535836    5406.090     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5537094    5407.318     5.281

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5538998    5409.178     5.282

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5539038    5409.217     5.282

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5539128    5409.305     5.283

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5541984    5412.094     5.285

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5542044    5412.152     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5542179    5412.284     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546463    5416.468     5.290

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546551    5416.554     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546749    5416.747     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553175    5423.022     5.296

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5553307    5423.151     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553604    5423.441     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563226    5432.838     5.306

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5563426    5433.033     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563876    5433.473     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5578326    5447.584     5.320

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5578626    5447.877     5.320

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5579301    5448.536     5.321

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5600959    5469.687     5.341

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5601407    5470.124     5.342

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5602415    5471.108     5.343

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5634919    5502.851     5.374

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      5866791    5729.288     5.595
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  3:D  335:D     2523

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5877400    5739.648     5.605

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6067423    5925.218     5.786
openf___224_> Open           result\curated\tmp\chainD.seq
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib

openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainD.fasta

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5526104    5396.586     5.270

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5527554    5398.002     5.271

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5530454    5400.834     5.274

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536254    5406.498     5.280

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5537590    5407.803     5.281

Read the alignment from file       : result\curated\tmp\chainD.fasta

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  1U8F_1|Ch     335      1
openf___224_> Open           result\curated\tmp\chainD.pir
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5535475    5405.737     5.279

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536925    5407.153     5.280

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5539825    5409.985     5.283

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5545625    5415.649     5.289

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546953    5416.946     5.290

Read the alignment from file       : alignment.seg

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5676161    5543.126     5.413

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5677497    5544.431     5.414

Read the alignment from file       : alignment.seg

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     335      1        1U8F
openf___224_> Open           $(LIB)/as1.sim.mat
rdrrwgh_268_> Number of residue types:       20

Pairwise dynamic programming alignment (ALIGN):
  Residue-residue metric   : $(LIB)/as1.sim.mat
  Diagonal                 :          100
  Overhang                 :            0
  Local alignment          :            F
  MATRIX_OFFSET (local aln):       0.0000
  N_SUBOPT                 :            0
  SUBOPT_OFFSET            :       0.0000
  Alignment block          :            1
  Gap introduction penalty :    -600.0000
  Gap extension penalty    :    -400.0000
  Break-break bonus        :   10000.0000
  Length of alignment      :          335
  Score                    :  292963.0000
openf___224_> Open           alignment.seg.ali

Sequence identity comparison (ID_TABLE):

   Diagonal       ... number of residues;
   Upper triangle ... number of identical residues;
   Lower triangle ... % sequence identity, id/min(length).

         result@11U8F  @1
result@1      333     333
1U8F  @1      100     335
>> patching model...
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724447    5590.280     5.459

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724975    5590.796     5.460
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5773575    5638.257     5.506
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5786875    5651.245     5.519
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           trimmed_align.ali

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5798840    5662.930     5.530

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5800290    5664.346     5.532

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5803190    5667.178     5.534

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5808990    5672.842     5.540

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5938198    5799.021     5.663

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5939526    5800.318     5.664

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5940854    5801.615     5.666

Read the alignment from file       : trimmed_align.ali

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     333      1        1U8F
check_a_343_> >> BEGINNING OF COMMAND
openf___224_> Open           .\result\curated\tmp\chainD.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042650    5901.025     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6043500    5901.855     5.764

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6044758    5903.084     5.765

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046752    5905.031     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049743    5907.952     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054225    5912.329     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060948    5918.895     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6071020    5928.730     5.790

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6086145    5943.501     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6108811    5965.636     5.826

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6141315    5997.378     5.857

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6141279    5997.343     5.857

check_ali___> Checking the sequence-structure alignment.

Implied intrachain target CA(i)-CA(i+1) distances longer than  8.0 angstroms:

ALN_POS  TMPL  RID1  RID2  NAM1  NAM2     DIST
----------------------------------------------
END OF TABLE
check_a_344_> << END OF COMMAND
openf___224_> Open           ${LIB}/top_heav.lib
read_to_681_> topology.submodel read from topology file:        3

openf___224_> Open           ${LIB}/par.lib

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6280531    6133.331     5.990

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6282131    6134.894     5.991

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6286111    6138.780     5.995

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6288111    6140.733     5.997

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6291111    6143.663     6.000

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6295611    6148.058     6.004

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6301183    6153.499     6.009

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6303983    6156.233     6.012

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6308183    6160.335     6.016

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6314483    6166.487     6.022

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6317255    6169.194     6.025

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6318655    6170.562     6.026
read_pa_232_> parameters    BONDS   ANGLS  DIHEDS IMPROPS    MODE
                              227     561     661     112       0

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6370779    6221.464     6.076

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6619797    6464.646     6.313

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6657509    6501.474     6.349

mkilst______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572      0         0      1071

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6765141    6606.583     6.452

patch_______> segment topology patched using RTF:  1 ;  LYS  ;  NTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572   3481      4118      1071


Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6875637    6714.489     6.557
patch_______> segment topology patched using RTF:  333 ;  GLU  ;  CTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072

genseg______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072
transfe_506_> MODEL is an average of all templates.
transfe_511_> Number of templates for coordinate transfer:        1
              After transferring coordinates of the equivalent template atoms,
              there are defined, undefined atoms in MODEL:     2523        0
openf___224_> Open           1U8F.ini
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523
make_re_417_> Restraint type to be calculated:  stereo

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6983086    6819.420     6.660

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6991278    6827.420     6.667

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7007662    6843.420     6.683

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7040430    6875.420     6.714

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7073198    6907.420     6.746

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7138734    6971.420     6.808

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7171502    7003.420     6.839

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7204270    7035.420     6.871

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7269806    7099.420     6.933

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7400878    7227.420     7.058

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7466414    7291.420     7.121

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7531950    7355.420     7.183

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7663022    7483.420     7.308

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7925166    7739.420     7.558

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8056238    7867.420     7.683
r_stere_606_> Stereochemical restraints were constructed from RTF & PRMF.
              Added bond,angle,dihedral,improper restraints  :     2573    3483    3913    1060
              Total number of restraints before, now         :        0    11029
make_re_422_> Number of previous, current restraints         :        0    11029
make_re_423_> Number of previous, current selected restraints:        0    11029
make_re_417_> Restraint type to be calculated:  phi-psi_binormal

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243952    8050.734     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainD
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11029    11360
make_re_423_> Number of previous, current selected restraints:    11029    11360
make_re_417_> Restraint type to be calculated:  omega_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainD
getdata_289_> Proteins (all/accepted):        1        1
omgdel__425_> Unselected all O C +N +CA dihedrals:      344
              (This is to avoid clashes between STEREO
              and OMEGA_DIHEDRAL restraints)
make_re_422_> Number of previous, current restraints         :    11360    11692
make_re_423_> Number of previous, current selected restraints:    11360    11348
make_re_417_> Restraint type to be calculated:  chi1_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainD
getdata_289_> Proteins (all/accepted):        1        1

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8375040    8178.750     7.987
make_re_422_> Number of previous, current restraints         :    11692    11962
make_re_423_> Number of previous, current selected restraints:    11348    11618
make_re_417_> Restraint type to be calculated:  chi2_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi2.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainD
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11962    12155
make_re_423_> Number of previous, current selected restraints:    11618    11811
make_re_417_> Restraint type to be calculated:  chi3_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi3.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainD
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12155    12232
make_re_423_> Number of previous, current selected restraints:    11811    11888
make_re_417_> Restraint type to be calculated:  chi4_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi4.mdt
mdtrsr__446W> A potential that relies on one protein is used, yet you have at
              least one known structure available. MDT, not library, potential is used.
getdata_643_> Protein accepted:  result\curated\tmp\chainD
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12232    12268
make_re_423_> Number of previous, current selected restraints:    11888    11924
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at amaxhash_contac [B,KiB,MiB]:      9101628    8888.309     8.680

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9363772    9144.309     8.930

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9625916    9400.309     9.180

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10150204    9912.309     9.680
make_re_422_> Number of previous, current restraints         :    12268    19742
make_re_423_> Number of previous, current selected restraints:    11924    19398
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10412348   10168.309     9.930
make_re_422_> Number of previous, current restraints         :    19742    27323
make_re_423_> Number of previous, current selected restraints:    19398    26979
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    27323    32653
make_re_423_> Number of previous, current selected restraints:    26979    32309
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10936636   10680.309    10.430
make_re_422_> Number of previous, current restraints         :    32653    35775
make_re_423_> Number of previous, current selected restraints:    32309    35431
0 atoms in HETATM/BLK residues constrained
to protein atoms within 2.30 angstroms
and protein CA atoms within 10.00 angstroms
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35775    35775
make_re_423_> Number of previous, current selected restraints:    35431    35431
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35775    35775
make_re_423_> Number of previous, current selected restraints:    35431    35431
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35775    35775
make_re_423_> Number of previous, current selected restraints:    35431    35431
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35775    35775
make_re_423_> Number of previous, current selected restraints:    35431    35431
0 atoms in residues without defined topology
constrained to be rigid bodies
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35775    35775
make_re_423_> Number of previous, current selected restraints:    35431    35431
rmdupl__427_>     1971 redundant cosine dihedral restraints were unselected.
condens_443_> Restraints marked for deletion were removed.
              Total number of restraints before, now:    35775    33460
openf___224_> Open           1U8F.rsr
openf___224_> Open           1U8F.rsr

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10927372   10671.262    10.421

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11713804   11439.262    11.171
rdcsr2__307_> Number of restraints read    :    33460
              Number of excluded pairs read:        0
              Number of pseudo atoms read  :        0
rdcsrs__304_> Restraints in memory, selected restraints:    33460    33460
              Explicitly excluded atom pairs in memory :        0
              Pseudo atoms in memory                   :        0
openf___224_> Open           1U8F.ini

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:     11713836   11439.293    11.171
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  1:A  333:A     2523
randomi_498_> Atoms,selected atoms,random_seed,amplitude:     2523     2523        1        4.0000
randomi_496_> Amplitude is > 0; randomization is done.
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    16516
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    18696
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    19847
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    21218
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    23214
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    25432
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    27310
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    29605
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    31019

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12066960   11784.141    11.508
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    32427
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33016
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33460
iupac_m_487_> NH1/2 swapped:      177.7113       14  14
iupac_m_485_> OD1/2 will be swapped:     -167.4757       27  27
iupac_m_485_> OD1/2 will be swapped:      103.4066       37  37
iupac_m_483_> CD1/2 CE1/2 swapped:      -95.3692       45  45
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_486_> OE1/2 will be swapped:       96.7416       95  95
iupac_m_486_> OE1/2 will be swapped:     -175.4149      221  221
iupac_m_487_> NH1/2 swapped:      170.7988      232  232
iupac_m_485_> OD1/2 will be swapped:      149.7225      242  242
iupac_m_486_> OE1/2 will be swapped:      179.8673      248  248
iupac_m_483_> CD1/2 CE1/2 swapped:       97.9020      312  312
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_486_> OE1/2 will be swapped:     -161.4249      315  315
iupac_m_483_> CD1/2 CE1/2 swapped:     -102.3345      316  316
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
>> Model assessment by DOPE potential
iatmcls_286W> MODEL atom not classified:  GLU:OXT  GLU

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12420284   12129.184    11.845

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12541388   12247.449    11.960

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12783596   12483.980    12.191

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     13268012   12957.043    12.653

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     14236844   13903.168    13.577

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     16174508   15795.418    15.425

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     20049836   19579.918    19.121


>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33460   33460
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):   506013
Dynamic pairs routine                             : 1, NATM x NATM double loop
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        1    9999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :   15.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       F       F       F       T
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :      -38168.3320




<< end of ENERGY.
DOPE score               : -38168.332031
>> Model assessment by GA341 potential

Surface library          : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/surf5.de
Pair library             : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/pair9.de
Chain identifier         : _
% sequence identity      :   100.000000
Sequence length          :          333
Compactness              :     0.241360
Native energy (pair)     :  -312.570954
Native energy (surface)  :   -17.385930
Native energy (combined) :   -10.028801
Z score (pair)           :   -10.487349
Z score (surface)        :    -7.720951
Z score (combined)       :   -12.249223
GA341 score              :     1.000000



>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33460   33460
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):     5252
Dynamic pairs routine                             : 2, NATM x NATM cell sorting
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        0   99999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :    4.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       T       F       F       F
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :        1786.5005





Summary of the restraint violations:

   NUM     ... number of restraints.
   NUMVI   ... number of restraints with RVIOL > VIOL_REPORT_CUT[i].
   RVIOL   ... relative difference from the best value.
   NUMVP   ... number of restraints with -Ln(pdf) > VIOL_REPORT_CUT2[i].
   RMS_1   ... RMS(feature, minimally_violated_basis_restraint, NUMB).
   RMS_2   ... RMS(feature, best_value, NUMB).
   MOL.PDF ... scaled contribution to -Ln(Molecular pdf).

 #                     RESTRAINT_GROUP      NUM   NUMVI  NUMVP   RMS_1   RMS_2         MOL.PDF     S_i
------------------------------------------------------------------------------------------------------
 1 Bond length potential              :    2573       0      0   0.005   0.005      21.557       1.000
 2 Bond angle potential               :    3483       0      9   1.954   1.954      267.53       1.000
 3 Stereochemical cosine torsion poten:    1598       0     53  48.669  48.669      606.47       1.000
 4 Stereochemical improper torsion pot:    1060       0      0   1.191   1.191      36.534       1.000
 5 Soft-sphere overlap restraints     :    5252       0      0   0.001   0.001     0.57263       1.000
 6 Lennard-Jones 6-12 potential       :       0       0      0   0.000   0.000      0.0000       1.000
 7 Coulomb point-point electrostatic p:       0       0      0   0.000   0.000      0.0000       1.000
 8 H-bonding potential                :       0       0      0   0.000   0.000      0.0000       1.000
 9 Distance restraints 1 (CA-CA)      :    7474       0      0   0.085   0.085      66.263       1.000
10 Distance restraints 2 (N-O)        :    7581       1      3   0.156   0.156      177.33       1.000
11 Mainchain Phi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
12 Mainchain Psi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
13 Mainchain Omega dihedral restraints:     332       0      3   3.867   3.867      58.541       1.000
14 Sidechain Chi_1 dihedral restraints:     270       0      1  42.899  42.899     -9.8092       1.000
15 Sidechain Chi_2 dihedral restraints:     193       0      2  58.964  58.964      54.976       1.000
16 Sidechain Chi_3 dihedral restraints:      77       0      0  60.502  60.502      43.249       1.000
17 Sidechain Chi_4 dihedral restraints:      36       0      0  86.398  86.398      23.676       1.000
18 Disulfide distance restraints      :       0       0      0   0.000   0.000      0.0000       1.000
19 Disulfide angle restraints         :       0       0      0   0.000   0.000      0.0000       1.000
20 Disulfide dihedral angle restraints:       0       0      0   0.000   0.000      0.0000       1.000
21 Lower bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
22 Upper bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
23 Distance restraints 3 (SDCH-MNCH)  :    5330       0      0   0.366   0.366      135.25       1.000
24 Sidechain Chi_5 dihedral restraints:       0       0      0   0.000   0.000      0.0000       1.000
25 Phi/Psi pair of dihedral restraints:     331       7     33  27.009  31.943      121.81       1.000
26 Distance restraints 4 (SDCH-SDCH)  :    3122       0      0   0.642   0.642      182.56       1.000
27 Distance restraints 5 (X-Y)        :       0       0      0   0.000   0.000      0.0000       1.000
28 NMR distance restraints 6 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
29 NMR distance restraints 7 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
30 Minimal distance restraints        :       0       0      0   0.000   0.000      0.0000       1.000
31 Non-bonded restraints              :       0       0      0   0.000   0.000      0.0000       1.000
32 Atomic accessibility restraints    :       0       0      0   0.000   0.000      0.0000       1.000
33 Atomic density restraints          :       0       0      0   0.000   0.000      0.0000       1.000
34 Absolute position restraints       :       0       0      0   0.000   0.000      0.0000       1.000
35 Dihedral angle difference restraint:       0       0      0   0.000   0.000      0.0000       1.000
36 GBSA implicit solvent potential    :       0       0      0   0.000   0.000      0.0000       1.000
37 EM density fitting potential       :       0       0      0   0.000   0.000      0.0000       1.000
38 SAXS restraints                    :       0       0      0   0.000   0.000      0.0000       1.000
39 Symmetry restraints                :       0       0      0   0.000   0.000      0.0000       1.000



openf___224_> Open           1U8F.V99990001
# Heavy relative violation of each residue is written to: 1U8F.V99990001
# The profile is NOT normalized by the number of restraints.
# The profiles are smoothed over a window of residues:    1
# The sum of all numbers in the file:   25448.6250



List of the violated restraints:
   A restraint is violated when the relative difference
   from the best value (RVIOL) is larger than CUTOFF.

   ICSR   ... index of a restraint in the current set.
   RESNO  ... residue numbers of the first two atoms.
   ATM    ... IUPAC atom names of the first two atoms.
   FEAT   ... the value of the feature in the model.
   restr  ... the mean of the basis restraint with the smallest
              difference from the model (local minimum).
   viol   ... difference from the local minimum.
   rviol  ... relative difference from the local minimum.
   RESTR  ... the best value (global minimum).
   VIOL   ... difference from the best value.
   RVIOL  ... relative difference from the best value.


-------------------------------------------------------------------------------------------------

Feature 25                           : Phi/Psi pair of dihedral restraints
List of the RVIOL violations larger than   :       6.5000

    #   ICSR  RESNO1/2 ATM1/2   INDATM1/2    FEAT   restr    viol   rviol   RESTR    VIOL   RVIOL
    1   8775  61E  62N C   N     478  480   59.11  -63.20  165.57   18.76   55.90  167.83   11.98
    1         62N  62N N   CA    480  481 -152.70  -41.10                   39.50
    2   8776  62N  63G C   N     486  488  -70.44  -62.40   25.19    3.46   82.20  154.82   11.22
    2         63G  63G N   CA    488  489  -17.33  -41.20                    8.50
    3   8813  99V 100F C   N     767  769  -87.74  -63.20   64.54    7.55  -63.20   64.54    7.55
    3        100F 100F N   CA    769  770   15.40  -44.30                  -44.30
    4   8847 133V 134N C   N    1009 1011 -151.42 -119.90  110.70    5.65  -63.20  113.86   13.15
    4        134N 134N N   CA   1011 1012   30.88  137.00                  -41.10
    5   8861 147N 148A C   N    1126 1128   83.74 -134.00  150.97    3.52  -62.50 -169.82   30.04
    5        148A 148A N   CA   1128 1129 -162.48  147.00                  -40.90
    6   8903 189P 190S C   N    1427 1429 -149.28 -136.60   63.68    3.45  -64.10  150.27   10.45
    6        190S 190S N   CA   1429 1430   88.80  151.20                  -35.00
    7   8979 265E 266G C   N    1993 1995  -83.67  -62.40   50.77    8.71  -62.40   50.77    8.71
    7        266G 266G N   CA   1995 1996  -87.30  -41.20                  -41.20


report______> Distribution of short non-bonded contacts:

DISTANCE1:  0.00 2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40
DISTANCE2:  2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40 3.50
FREQUENCY:     0    0    0    0    0   13   30   80  144  184  213  305  325  377  423


<< end of ENERGY.
openf___224_> Open           1U8F.B99990001.pdb
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523

>> Summary of successfully produced models:
Filename                          molpdf     DOPE score    GA341 score
----------------------------------------------------------------------
1U8F.B99990001.pdb            1786.50049   -38168.33203        1.00000

>> modelling missing residues
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainA.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534739    5405.019     5.278

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5534815    5405.093     5.278

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534986    5405.260     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5535836    5406.090     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5537094    5407.318     5.281

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5538998    5409.178     5.282

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5539038    5409.217     5.282

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5539128    5409.305     5.283

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5541984    5412.094     5.285

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5542044    5412.152     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5542179    5412.284     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546463    5416.468     5.290

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546551    5416.554     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546749    5416.747     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553175    5423.022     5.296

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5553307    5423.151     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553604    5423.441     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563226    5432.838     5.306

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5563426    5433.033     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563876    5433.473     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5578326    5447.584     5.320

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5578626    5447.877     5.320

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5579301    5448.536     5.321

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5600959    5469.687     5.341

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5601407    5470.124     5.342

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5602415    5471.108     5.343

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5634919    5502.851     5.374

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      5866791    5729.288     5.595
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  3:A  335:A     2523

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5877400    5739.648     5.605

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6067423    5925.218     5.786
openf___224_> Open           result\curated\tmp\chainA.seq
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainA.fasta

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5526104    5396.586     5.270

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5527554    5398.002     5.271

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5530454    5400.834     5.274

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536254    5406.498     5.280

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5537590    5407.803     5.281

Read the alignment from file       : result\curated\tmp\chainA.fasta

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  1U8F_1|Ch     335      1
openf___224_> Open           result\curated\tmp\chainA.pir
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib

openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5535475    5405.737     5.279

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536925    5407.153     5.280

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5539825    5409.985     5.283

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5545625    5415.649     5.289

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546953    5416.946     5.290

Read the alignment from file       : alignment.seg

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5676161    5543.126     5.413

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5677497    5544.431     5.414

Read the alignment from file       : alignment.seg

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     335      1        1U8F
openf___224_> Open           $(LIB)/as1.sim.mat
rdrrwgh_268_> Number of residue types:       20

Pairwise dynamic programming alignment (ALIGN):
  Residue-residue metric   : $(LIB)/as1.sim.mat
  Diagonal                 :          100
  Overhang                 :            0
  Local alignment          :            F
  MATRIX_OFFSET (local aln):       0.0000
  N_SUBOPT                 :            0
  SUBOPT_OFFSET            :       0.0000
  Alignment block          :            1
  Gap introduction penalty :    -600.0000
  Gap extension penalty    :    -400.0000
  Break-break bonus        :   10000.0000
  Length of alignment      :          335
  Score                    :  292963.0000
openf___224_> Open           alignment.seg.ali

Sequence identity comparison (ID_TABLE):

   Diagonal       ... number of residues;
   Upper triangle ... number of identical residues;
   Lower triangle ... % sequence identity, id/min(length).

         result@11U8F  @1
result@1      333     333
1U8F  @1      100     335
>> patching model...
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724447    5590.280     5.459

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724975    5590.796     5.460
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5773575    5638.257     5.506
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5786875    5651.245     5.519
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           trimmed_align.ali

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5798840    5662.930     5.530

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5800290    5664.346     5.532

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5803190    5667.178     5.534

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5808990    5672.842     5.540

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5938198    5799.021     5.663

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5939526    5800.318     5.664

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5940854    5801.615     5.666

Read the alignment from file       : trimmed_align.ali

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     333      1        1U8F
check_a_343_> >> BEGINNING OF COMMAND
openf___224_> Open           .\result\curated\tmp\chainA.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042650    5901.025     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6043500    5901.855     5.764

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6044758    5903.084     5.765

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046752    5905.031     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049743    5907.952     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054225    5912.329     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060948    5918.895     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6071020    5928.730     5.790

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6086145    5943.501     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6108811    5965.636     5.826

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6141315    5997.378     5.857

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6141279    5997.343     5.857

check_ali___> Checking the sequence-structure alignment.

Implied intrachain target CA(i)-CA(i+1) distances longer than  8.0 angstroms:

ALN_POS  TMPL  RID1  RID2  NAM1  NAM2     DIST
----------------------------------------------
END OF TABLE
check_a_344_> << END OF COMMAND
openf___224_> Open           ${LIB}/top_heav.lib
read_to_681_> topology.submodel read from topology file:        3
openf___224_> Open           ${LIB}/par.lib

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6280531    6133.331     5.990

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6282131    6134.894     5.991

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6286111    6138.780     5.995

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6288111    6140.733     5.997

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6291111    6143.663     6.000

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6295611    6148.058     6.004

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6301183    6153.499     6.009

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6303983    6156.233     6.012

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6308183    6160.335     6.016

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6314483    6166.487     6.022

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6317255    6169.194     6.025

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6318655    6170.562     6.026
read_pa_232_> parameters    BONDS   ANGLS  DIHEDS IMPROPS    MODE
                              227     561     661     112       0

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6370779    6221.464     6.076

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6619797    6464.646     6.313

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6657509    6501.474     6.349

mkilst______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572      0         0      1071

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6765141    6606.583     6.452

patch_______> segment topology patched using RTF:  1 ;  LYS  ;  NTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572   3481      4118      1071


Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6875637    6714.489     6.557
patch_______> segment topology patched using RTF:  333 ;  GLU  ;  CTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072

genseg______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072
transfe_506_> MODEL is an average of all templates.
transfe_511_> Number of templates for coordinate transfer:        1
              After transferring coordinates of the equivalent template atoms,
              there are defined, undefined atoms in MODEL:     2523        0
openf___224_> Open           1U8F.ini
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523
make_re_417_> Restraint type to be calculated:  stereo

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6983086    6819.420     6.660

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6991278    6827.420     6.667

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7007662    6843.420     6.683

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7040430    6875.420     6.714

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7073198    6907.420     6.746

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7138734    6971.420     6.808

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7171502    7003.420     6.839

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7204270    7035.420     6.871

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7269806    7099.420     6.933

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7400878    7227.420     7.058

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7466414    7291.420     7.121

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7531950    7355.420     7.183

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7663022    7483.420     7.308

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7925166    7739.420     7.558

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8056238    7867.420     7.683
r_stere_606_> Stereochemical restraints were constructed from RTF & PRMF.
              Added bond,angle,dihedral,improper restraints  :     2573    3483    3913    1060
              Total number of restraints before, now         :        0    11029
make_re_422_> Number of previous, current restraints         :        0    11029
make_re_423_> Number of previous, current selected restraints:        0    11029
make_re_417_> Restraint type to be calculated:  phi-psi_binormal

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243952    8050.734     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11029    11360
make_re_423_> Number of previous, current selected restraints:    11029    11360
make_re_417_> Restraint type to be calculated:  omega_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
omgdel__425_> Unselected all O C +N +CA dihedrals:      344
              (This is to avoid clashes between STEREO
              and OMEGA_DIHEDRAL restraints)
make_re_422_> Number of previous, current restraints         :    11360    11692
make_re_423_> Number of previous, current selected restraints:    11360    11348
make_re_417_> Restraint type to be calculated:  chi1_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8375040    8178.750     7.987
make_re_422_> Number of previous, current restraints         :    11692    11962
make_re_423_> Number of previous, current selected restraints:    11348    11618
make_re_417_> Restraint type to be calculated:  chi2_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi2.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11962    12155
make_re_423_> Number of previous, current selected restraints:    11618    11811
make_re_417_> Restraint type to be calculated:  chi3_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi3.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12155    12232
make_re_423_> Number of previous, current selected restraints:    11811    11888
make_re_417_> Restraint type to be calculated:  chi4_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi4.mdt
mdtrsr__446W> A potential that relies on one protein is used, yet you have at
              least one known structure available. MDT, not library, potential is used.
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12232    12268
make_re_423_> Number of previous, current selected restraints:    11888    11924
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at amaxhash_contac [B,KiB,MiB]:      9101628    8888.309     8.680

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9363772    9144.309     8.930

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9625916    9400.309     9.180

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10150204    9912.309     9.680
make_re_422_> Number of previous, current restraints         :    12268    19747
make_re_423_> Number of previous, current selected restraints:    11924    19403
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10412348   10168.309     9.930
make_re_422_> Number of previous, current restraints         :    19747    27344
make_re_423_> Number of previous, current selected restraints:    19403    27000
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    27344    32684
make_re_423_> Number of previous, current selected restraints:    27000    32340
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10936636   10680.309    10.430
make_re_422_> Number of previous, current restraints         :    32684    35808
make_re_423_> Number of previous, current selected restraints:    32340    35464
0 atoms in HETATM/BLK residues constrained
to protein atoms within 2.30 angstroms
and protein CA atoms within 10.00 angstroms
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35808    35808
make_re_423_> Number of previous, current selected restraints:    35464    35464
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35808    35808
make_re_423_> Number of previous, current selected restraints:    35464    35464
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35808    35808
make_re_423_> Number of previous, current selected restraints:    35464    35464
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35808    35808
make_re_423_> Number of previous, current selected restraints:    35464    35464
0 atoms in residues without defined topology
constrained to be rigid bodies
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35808    35808
make_re_423_> Number of previous, current selected restraints:    35464    35464
rmdupl__427_>     1971 redundant cosine dihedral restraints were unselected.
condens_443_> Restraints marked for deletion were removed.
              Total number of restraints before, now:    35808    33493
openf___224_> Open           1U8F.rsr
openf___224_> Open           1U8F.rsr

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10927372   10671.262    10.421

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11713804   11439.262    11.171
rdcsr2__307_> Number of restraints read    :    33493
              Number of excluded pairs read:        0
              Number of pseudo atoms read  :        0
rdcsrs__304_> Restraints in memory, selected restraints:    33493    33493
              Explicitly excluded atom pairs in memory :        0
              Pseudo atoms in memory                   :        0
openf___224_> Open           1U8F.ini

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:     11713836   11439.293    11.171
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  1:A  333:A     2523
randomi_498_> Atoms,selected atoms,random_seed,amplitude:     2523     2523        1        4.0000
randomi_496_> Amplitude is > 0; randomization is done.
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    16537
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    18702
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    19854
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    21234
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    23221
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    25455
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    27337
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    29634
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    31065

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12066960   11784.141    11.508
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    32474
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33071
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33493
iupac_m_487_> NH1/2 swapped:      173.5217       14  14
iupac_m_485_> OD1/2 will be swapped:     -178.2486       37  37
iupac_m_483_> CD1/2 CE1/2 swapped:      102.8090       43  43
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_483_> CD1/2 CE1/2 swapped:      -98.4106       45  45
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_485_> OD1/2 will be swapped:     -144.4697       48  48
iupac_m_486_> OE1/2 will be swapped:     -167.8770       77  77
iupac_m_485_> OD1/2 will be swapped:      162.4217       87  87
iupac_m_485_> OD1/2 will be swapped:      117.3975      139  139
iupac_m_487_> NH1/2 swapped:      179.7815      195  195
iupac_m_486_> OE1/2 will be swapped:     -163.2653      221  221
iupac_m_487_> NH1/2 swapped:     -173.3275      232  232
iupac_m_485_> OD1/2 will be swapped:      149.0599      242  242
iupac_m_483_> CD1/2 CE1/2 swapped:       97.4768      312  312
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_483_> CD1/2 CE1/2 swapped:      -91.5925      316  316
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_487_> NH1/2 swapped:      170.9864      321  321
iupac_m_486_> OE1/2 will be swapped:      167.4404      333  333
>> Model assessment by DOPE potential
iatmcls_286W> MODEL atom not classified:  GLU:OXT  GLU

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12420284   12129.184    11.845

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12541388   12247.449    11.960

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12783596   12483.980    12.191

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     13268012   12957.043    12.653

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     14236844   13903.168    13.577

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     16174508   15795.418    15.425

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     20049836   19579.918    19.121


>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33493   33493
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):   506956
Dynamic pairs routine                             : 1, NATM x NATM double loop
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        1    9999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :   15.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       F       F       F       T
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :      -37779.8359




<< end of ENERGY.
DOPE score               : -37779.835938
>> Model assessment by GA341 potential

Surface library          : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/surf5.de
Pair library             : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/pair9.de
Chain identifier         : _
% sequence identity      :   100.000000
Sequence length          :          333
Compactness              :     0.240864
Native energy (pair)     :  -293.366058
Native energy (surface)  :   -16.999445
Native energy (combined) :    -9.404737
Z score (pair)           :    -9.951804
Z score (surface)        :    -7.443137
Z score (combined)       :   -11.739269
GA341 score              :     1.000000



>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33493   33493
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):     5407
Dynamic pairs routine                             : 2, NATM x NATM cell sorting
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        0   99999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :    4.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       T       F       F       F
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :        1902.4468





Summary of the restraint violations:

   NUM     ... number of restraints.
   NUMVI   ... number of restraints with RVIOL > VIOL_REPORT_CUT[i].
   RVIOL   ... relative difference from the best value.
   NUMVP   ... number of restraints with -Ln(pdf) > VIOL_REPORT_CUT2[i].
   RMS_1   ... RMS(feature, minimally_violated_basis_restraint, NUMB).
   RMS_2   ... RMS(feature, best_value, NUMB).
   MOL.PDF ... scaled contribution to -Ln(Molecular pdf).

 #                     RESTRAINT_GROUP      NUM   NUMVI  NUMVP   RMS_1   RMS_2         MOL.PDF     S_i
------------------------------------------------------------------------------------------------------
 1 Bond length potential              :    2573       0      0   0.005   0.005      20.135       1.000
 2 Bond angle potential               :    3483       0      9   1.924   1.924      260.25       1.000
 3 Stereochemical cosine torsion poten:    1598       0     54  48.840  48.840      609.46       1.000
 4 Stereochemical improper torsion pot:    1060       0      0   1.163   1.163      35.212       1.000
 5 Soft-sphere overlap restraints     :    5407       0      0   0.002   0.002      1.4610       1.000
 6 Lennard-Jones 6-12 potential       :       0       0      0   0.000   0.000      0.0000       1.000
 7 Coulomb point-point electrostatic p:       0       0      0   0.000   0.000      0.0000       1.000
 8 H-bonding potential                :       0       0      0   0.000   0.000      0.0000       1.000
 9 Distance restraints 1 (CA-CA)      :    7479       0      0   0.084   0.084      65.808       1.000
10 Distance restraints 2 (N-O)        :    7597       2      9   0.166   0.166      205.39       1.000
11 Mainchain Phi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
12 Mainchain Psi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
13 Mainchain Omega dihedral restraints:     332       0      1   3.971   3.971      61.729       1.000
14 Sidechain Chi_1 dihedral restraints:     270       0      2  53.372  53.372      14.480       1.000
15 Sidechain Chi_2 dihedral restraints:     193       0      0  64.026  64.026      58.890       1.000
16 Sidechain Chi_3 dihedral restraints:      77       0      0  58.812  58.812      42.160       1.000
17 Sidechain Chi_4 dihedral restraints:      36       0      0  97.378  97.378      22.601       1.000
18 Disulfide distance restraints      :       0       0      0   0.000   0.000      0.0000       1.000
19 Disulfide angle restraints         :       0       0      0   0.000   0.000      0.0000       1.000
20 Disulfide dihedral angle restraints:       0       0      0   0.000   0.000      0.0000       1.000
21 Lower bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
22 Upper bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
23 Distance restraints 3 (SDCH-MNCH)  :    5340       0      0   0.387   0.387      149.66       1.000
24 Sidechain Chi_5 dihedral restraints:       0       0      0   0.000   0.000      0.0000       1.000
25 Phi/Psi pair of dihedral restraints:     331      10     32  29.358  34.445      136.32       1.000
26 Distance restraints 4 (SDCH-SDCH)  :    3124       0      1   0.703   0.703      218.89       1.000
27 Distance restraints 5 (X-Y)        :       0       0      0   0.000   0.000      0.0000       1.000
28 NMR distance restraints 6 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
29 NMR distance restraints 7 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
30 Minimal distance restraints        :       0       0      0   0.000   0.000      0.0000       1.000
31 Non-bonded restraints              :       0       0      0   0.000   0.000      0.0000       1.000
32 Atomic accessibility restraints    :       0       0      0   0.000   0.000      0.0000       1.000
33 Atomic density restraints          :       0       0      0   0.000   0.000      0.0000       1.000
34 Absolute position restraints       :       0       0      0   0.000   0.000      0.0000       1.000
35 Dihedral angle difference restraint:       0       0      0   0.000   0.000      0.0000       1.000
36 GBSA implicit solvent potential    :       0       0      0   0.000   0.000      0.0000       1.000
37 EM density fitting potential       :       0       0      0   0.000   0.000      0.0000       1.000
38 SAXS restraints                    :       0       0      0   0.000   0.000      0.0000       1.000
39 Symmetry restraints                :       0       0      0   0.000   0.000      0.0000       1.000



openf___224_> Open           1U8F.V99990001
# Heavy relative violation of each residue is written to: 1U8F.V99990001
# The profile is NOT normalized by the number of restraints.
# The profiles are smoothed over a window of residues:    1
# The sum of all numbers in the file:   27056.1973



List of the violated restraints:
   A restraint is violated when the relative difference
   from the best value (RVIOL) is larger than CUTOFF.

   ICSR   ... index of a restraint in the current set.
   RESNO  ... residue numbers of the first two atoms.
   ATM    ... IUPAC atom names of the first two atoms.
   FEAT   ... the value of the feature in the model.
   restr  ... the mean of the basis restraint with the smallest
              difference from the model (local minimum).
   viol   ... difference from the local minimum.
   rviol  ... relative difference from the local minimum.
   RESTR  ... the best value (global minimum).
   VIOL   ... difference from the best value.
   RVIOL  ... relative difference from the best value.


-------------------------------------------------------------------------------------------------

Feature 25                           : Phi/Psi pair of dihedral restraints
List of the RVIOL violations larger than   :       6.5000

    #   ICSR  RESNO1/2 ATM1/2   INDATM1/2    FEAT   restr    viol   rviol   RESTR    VIOL   RVIOL
    1   8722   8G   9F C   N      54   56  -88.12  -63.20   57.74    6.65  -63.20   57.74    6.65
    1          9F   9F N   CA     56   57    7.78  -44.30                  -44.30
    2   8781  67I  68N C   N     522  524   60.27  -63.20  165.95   18.85   55.90  168.57   12.11
    2         68N  68N N   CA    524  525 -151.99  -41.10                   39.50
    3   8782  68N  69G C   N     530  532  -74.54  -62.40   24.29    3.30   82.20  159.35   11.60
    3         69G  69G N   CA    532  533  -20.16  -41.20                    8.50
    4   8813  99V 100F C   N     767  769  -89.39  -63.20   66.67    7.77  -63.20   66.67    7.77
    4        100F 100F N   CA    769  770   17.01  -44.30                  -44.30
    5   8847 133V 134N C   N    1009 1011 -146.56  -63.20  103.16   12.17  -63.20  103.16   12.17
    5        134N 134N N   CA   1011 1012   19.67  -41.10                  -41.10
    6   8860 146S 147N C   N    1118 1120 -104.54  -63.20   73.74    7.94  -63.20   73.74    7.94
    6        147N 147N N   CA   1120 1121   19.96  -41.10                  -41.10
    7   8861 147N 148A C   N    1126 1128   69.14  -68.20  147.79   14.07  -62.50  177.59   27.76
    7        148A 148A N   CA   1128 1129 -160.10  145.30                  -40.90
    8   8902 188G 189P C   N    1420 1422  -34.17  -58.70   68.82    4.13  -64.50  121.84   10.74
    8        189P 189P N   CA   1422 1423  -94.80  -30.50                  147.20
    9   8903 189P 190S C   N    1427 1429  116.02 -136.60  159.08    5.26  -64.10 -171.48   25.22
    9        190S 190S N   CA   1429 1430  -91.44  151.20                  -35.00
   10   8904 190S 191G C   N    1433 1435   84.71   82.20   96.08    4.54  -62.40  154.24   25.30
   10        191G 191G N   CA   1435 1436  -87.54    8.50                  -41.20


report______> Distribution of short non-bonded contacts:

DISTANCE1:  0.00 2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40
DISTANCE2:  2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40 3.50
FREQUENCY:     0    0    0    0    0   17   41  104  161  181  212  306  350  382  391


<< end of ENERGY.
openf___224_> Open           1U8F.B99990001.pdb
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523

>> Summary of successfully produced models:
Filename                          molpdf     DOPE score    GA341 score
----------------------------------------------------------------------
1U8F.B99990001.pdb            1902.44678   -37779.83594        1.00000

>> modelling missing residues
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainB.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534739    5405.019     5.278

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5534815    5405.093     5.278

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534986    5405.260     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5535836    5406.090     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5537094    5407.318     5.281

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5538998    5409.178     5.282

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5539038    5409.217     5.282

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5539128    5409.305     5.283

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5541984    5412.094     5.285

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5542044    5412.152     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5542179    5412.284     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546463    5416.468     5.290

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546551    5416.554     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546749    5416.747     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553175    5423.022     5.296

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5553307    5423.151     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553604    5423.441     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563226    5432.838     5.306

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5563426    5433.033     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563876    5433.473     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5578326    5447.584     5.320

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5578626    5447.877     5.320

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5579301    5448.536     5.321

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5600959    5469.687     5.341

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5601407    5470.124     5.342

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5602415    5471.108     5.343

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5634919    5502.851     5.374

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      5866791    5729.288     5.595
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  3:B  335:B     2523

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5877400    5739.648     5.605

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6067423    5925.218     5.786
openf___224_> Open           result\curated\tmp\chainB.seq
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainB.fasta

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5526104    5396.586     5.270

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5527554    5398.002     5.271

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5530454    5400.834     5.274

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536254    5406.498     5.280

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5537590    5407.803     5.281

Read the alignment from file       : result\curated\tmp\chainB.fasta

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  1U8F_1|Ch     335      1
openf___224_> Open           result\curated\tmp\chainB.pir
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib

openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5535475    5405.737     5.279

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536925    5407.153     5.280

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5539825    5409.985     5.283

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5545625    5415.649     5.289

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546953    5416.946     5.290

Read the alignment from file       : alignment.seg

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5676161    5543.126     5.413

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5677497    5544.431     5.414

Read the alignment from file       : alignment.seg

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     335      1        1U8F
openf___224_> Open           $(LIB)/as1.sim.mat
rdrrwgh_268_> Number of residue types:       20

Pairwise dynamic programming alignment (ALIGN):
  Residue-residue metric   : $(LIB)/as1.sim.mat
  Diagonal                 :          100
  Overhang                 :            0
  Local alignment          :            F
  MATRIX_OFFSET (local aln):       0.0000
  N_SUBOPT                 :            0
  SUBOPT_OFFSET            :       0.0000
  Alignment block          :            1
  Gap introduction penalty :    -600.0000
  Gap extension penalty    :    -400.0000
  Break-break bonus        :   10000.0000
  Length of alignment      :          335
  Score                    :  292963.0000
openf___224_> Open           alignment.seg.ali

Sequence identity comparison (ID_TABLE):

   Diagonal       ... number of residues;
   Upper triangle ... number of identical residues;
   Lower triangle ... % sequence identity, id/min(length).

         result@11U8F  @1
result@1      333     333
1U8F  @1      100     335
>> patching model...
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724447    5590.280     5.459

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724975    5590.796     5.460
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5773575    5638.257     5.506
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5786875    5651.245     5.519
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           trimmed_align.ali

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5798840    5662.930     5.530

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5800290    5664.346     5.532

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5803190    5667.178     5.534

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5808990    5672.842     5.540

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5938198    5799.021     5.663

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5939526    5800.318     5.664

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5940854    5801.615     5.666

Read the alignment from file       : trimmed_align.ali

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     333      1        1U8F
check_a_343_> >> BEGINNING OF COMMAND
openf___224_> Open           .\result\curated\tmp\chainB.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042650    5901.025     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6043500    5901.855     5.764

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6044758    5903.084     5.765

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046752    5905.031     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049743    5907.952     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054225    5912.329     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060948    5918.895     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6071020    5928.730     5.790

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6086145    5943.501     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6108811    5965.636     5.826

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6141315    5997.378     5.857

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6141279    5997.343     5.857

check_ali___> Checking the sequence-structure alignment.

Implied intrachain target CA(i)-CA(i+1) distances longer than  8.0 angstroms:

ALN_POS  TMPL  RID1  RID2  NAM1  NAM2     DIST
----------------------------------------------
END OF TABLE
check_a_344_> << END OF COMMAND
openf___224_> Open           ${LIB}/top_heav.lib
read_to_681_> topology.submodel read from topology file:        3

openf___224_> Open           ${LIB}/par.lib

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6280531    6133.331     5.990

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6282131    6134.894     5.991

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6286111    6138.780     5.995

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6288111    6140.733     5.997

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6291111    6143.663     6.000

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6295611    6148.058     6.004

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6301183    6153.499     6.009

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6303983    6156.233     6.012

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6308183    6160.335     6.016

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6314483    6166.487     6.022

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6317255    6169.194     6.025

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6318655    6170.562     6.026
read_pa_232_> parameters    BONDS   ANGLS  DIHEDS IMPROPS    MODE
                              227     561     661     112       0

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6370779    6221.464     6.076

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6619797    6464.646     6.313

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6657509    6501.474     6.349

mkilst______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572      0         0      1071

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6765141    6606.583     6.452

patch_______> segment topology patched using RTF:  1 ;  LYS  ;  NTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572   3481      4118      1071


Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6875637    6714.489     6.557
patch_______> segment topology patched using RTF:  333 ;  GLU  ;  CTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072

genseg______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072
transfe_506_> MODEL is an average of all templates.
transfe_511_> Number of templates for coordinate transfer:        1
              After transferring coordinates of the equivalent template atoms,
              there are defined, undefined atoms in MODEL:     2523        0
openf___224_> Open           1U8F.ini
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523
make_re_417_> Restraint type to be calculated:  stereo

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6983086    6819.420     6.660

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6991278    6827.420     6.667

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7007662    6843.420     6.683

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7040430    6875.420     6.714

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7073198    6907.420     6.746

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7138734    6971.420     6.808

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7171502    7003.420     6.839

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7204270    7035.420     6.871

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7269806    7099.420     6.933

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7400878    7227.420     7.058

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7466414    7291.420     7.121

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7531950    7355.420     7.183

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7663022    7483.420     7.308

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7925166    7739.420     7.558

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8056238    7867.420     7.683
r_stere_606_> Stereochemical restraints were constructed from RTF & PRMF.
              Added bond,angle,dihedral,improper restraints  :     2573    3483    3913    1060
              Total number of restraints before, now         :        0    11029
make_re_422_> Number of previous, current restraints         :        0    11029
make_re_423_> Number of previous, current selected restraints:        0    11029
make_re_417_> Restraint type to be calculated:  phi-psi_binormal

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243952    8050.734     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11029    11360
make_re_423_> Number of previous, current selected restraints:    11029    11360
make_re_417_> Restraint type to be calculated:  omega_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
omgdel__425_> Unselected all O C +N +CA dihedrals:      344
              (This is to avoid clashes between STEREO
              and OMEGA_DIHEDRAL restraints)
make_re_422_> Number of previous, current restraints         :    11360    11692
make_re_423_> Number of previous, current selected restraints:    11360    11348
make_re_417_> Restraint type to be calculated:  chi1_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8375040    8178.750     7.987
make_re_422_> Number of previous, current restraints         :    11692    11962
make_re_423_> Number of previous, current selected restraints:    11348    11618
make_re_417_> Restraint type to be calculated:  chi2_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi2.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11962    12155
make_re_423_> Number of previous, current selected restraints:    11618    11811
make_re_417_> Restraint type to be calculated:  chi3_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi3.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12155    12232
make_re_423_> Number of previous, current selected restraints:    11811    11888
make_re_417_> Restraint type to be calculated:  chi4_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi4.mdt
mdtrsr__446W> A potential that relies on one protein is used, yet you have at
              least one known structure available. MDT, not library, potential is used.
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12232    12268
make_re_423_> Number of previous, current selected restraints:    11888    11924
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at amaxhash_contac [B,KiB,MiB]:      9101628    8888.309     8.680

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9363772    9144.309     8.930

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9625916    9400.309     9.180

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10150204    9912.309     9.680
make_re_422_> Number of previous, current restraints         :    12268    19778
make_re_423_> Number of previous, current selected restraints:    11924    19434
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10412348   10168.309     9.930
make_re_422_> Number of previous, current restraints         :    19778    27395
make_re_423_> Number of previous, current selected restraints:    19434    27051
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    27395    32716
make_re_423_> Number of previous, current selected restraints:    27051    32372
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10936636   10680.309    10.430
make_re_422_> Number of previous, current restraints         :    32716    35877
make_re_423_> Number of previous, current selected restraints:    32372    35533
0 atoms in HETATM/BLK residues constrained
to protein atoms within 2.30 angstroms
and protein CA atoms within 10.00 angstroms
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35877    35877
make_re_423_> Number of previous, current selected restraints:    35533    35533
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35877    35877
make_re_423_> Number of previous, current selected restraints:    35533    35533
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35877    35877
make_re_423_> Number of previous, current selected restraints:    35533    35533
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35877    35877
make_re_423_> Number of previous, current selected restraints:    35533    35533
0 atoms in residues without defined topology
constrained to be rigid bodies
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35877    35877
make_re_423_> Number of previous, current selected restraints:    35533    35533
rmdupl__427_>     1971 redundant cosine dihedral restraints were unselected.
condens_443_> Restraints marked for deletion were removed.
              Total number of restraints before, now:    35877    33562
openf___224_> Open           1U8F.rsr
openf___224_> Open           1U8F.rsr

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10927372   10671.262    10.421

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11713804   11439.262    11.171
rdcsr2__307_> Number of restraints read    :    33562
              Number of excluded pairs read:        0
              Number of pseudo atoms read  :        0
rdcsrs__304_> Restraints in memory, selected restraints:    33562    33562
              Explicitly excluded atom pairs in memory :        0
              Pseudo atoms in memory                   :        0
openf___224_> Open           1U8F.ini

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:     11713836   11439.293    11.171
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  1:A  333:A     2523
randomi_498_> Atoms,selected atoms,random_seed,amplitude:     2523     2523        1        4.0000
randomi_496_> Amplitude is > 0; randomization is done.
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    16519
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    18662
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    19828
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    21215
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    23205
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    25445
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    27356
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    29658
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    31094

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12066960   11784.141    11.508
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    32520
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33123
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33562
iupac_m_487_> NH1/2 swapped:     -177.5072       14  14
iupac_m_486_> OE1/2 will be swapped:      164.4158      170  170
iupac_m_487_> NH1/2 swapped:      179.9260      198  198
iupac_m_486_> OE1/2 will be swapped:     -136.1320      221  221
iupac_m_485_> OD1/2 will be swapped:      168.0448      242  242
iupac_m_487_> NH1/2 swapped:     -177.8922      246  246
iupac_m_486_> OE1/2 will be swapped:      176.7474      248  248
iupac_m_483_> CD1/2 CE1/2 swapped:      -90.7279      316  316
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
>> Model assessment by DOPE potential
iatmcls_286W> MODEL atom not classified:  GLU:OXT  GLU

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12420284   12129.184    11.845

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12541388   12247.449    11.960

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12783596   12483.980    12.191

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     13268012   12957.043    12.653

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     14236844   13903.168    13.577

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     16174508   15795.418    15.425

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     20049836   19579.918    19.121


>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33562   33562
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):   507737
Dynamic pairs routine                             : 1, NATM x NATM double loop
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        1    9999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :   15.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       F       F       F       T
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :      -37961.3789




<< end of ENERGY.
DOPE score               : -37961.378906
>> Model assessment by GA341 potential

Surface library          : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/surf5.de
Pair library             : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/pair9.de
Chain identifier         : _
% sequence identity      :   100.000000
Sequence length          :          333
Compactness              :     0.240905
Native energy (pair)     :  -282.472000
Native energy (surface)  :   -16.291333
Native energy (combined) :    -9.169488
Z score (pair)           :   -10.125022
Z score (surface)        :    -7.321720
Z score (combined)       :   -11.650726
GA341 score              :     1.000000



>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33562   33562
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):     5342
Dynamic pairs routine                             : 2, NATM x NATM cell sorting
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        0   99999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :    4.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       T       F       F       F
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :        1680.8921





Summary of the restraint violations:

   NUM     ... number of restraints.
   NUMVI   ... number of restraints with RVIOL > VIOL_REPORT_CUT[i].
   RVIOL   ... relative difference from the best value.
   NUMVP   ... number of restraints with -Ln(pdf) > VIOL_REPORT_CUT2[i].
   RMS_1   ... RMS(feature, minimally_violated_basis_restraint, NUMB).
   RMS_2   ... RMS(feature, best_value, NUMB).
   MOL.PDF ... scaled contribution to -Ln(Molecular pdf).

 #                     RESTRAINT_GROUP      NUM   NUMVI  NUMVP   RMS_1   RMS_2         MOL.PDF     S_i
------------------------------------------------------------------------------------------------------
 1 Bond length potential              :    2573       0      0   0.005   0.005      19.612       1.000
 2 Bond angle potential               :    3483       0      7   1.901   1.901      250.76       1.000
 3 Stereochemical cosine torsion poten:    1598       0     55  48.825  48.825      607.49       1.000
 4 Stereochemical improper torsion pot:    1060       0      0   1.142   1.142      33.101       1.000
 5 Soft-sphere overlap restraints     :    5342       0      0   0.001   0.001     0.81899       1.000
 6 Lennard-Jones 6-12 potential       :       0       0      0   0.000   0.000      0.0000       1.000
 7 Coulomb point-point electrostatic p:       0       0      0   0.000   0.000      0.0000       1.000
 8 H-bonding potential                :       0       0      0   0.000   0.000      0.0000       1.000
 9 Distance restraints 1 (CA-CA)      :    7510       0      0   0.078   0.078      56.629       1.000
10 Distance restraints 2 (N-O)        :    7617       0      5   0.144   0.144      150.62       1.000
11 Mainchain Phi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
12 Mainchain Psi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
13 Mainchain Omega dihedral restraints:     332       0      2   3.823   3.823      57.215       1.000
14 Sidechain Chi_1 dihedral restraints:     270       0      0  50.107  50.107      1.9702       1.000
15 Sidechain Chi_2 dihedral restraints:     193       0      2  60.085  60.085      48.423       1.000
16 Sidechain Chi_3 dihedral restraints:      77       0      0  68.657  68.657      44.919       1.000
17 Sidechain Chi_4 dihedral restraints:      36       0      0  86.551  86.551      21.080       1.000
18 Disulfide distance restraints      :       0       0      0   0.000   0.000      0.0000       1.000
19 Disulfide angle restraints         :       0       0      0   0.000   0.000      0.0000       1.000
20 Disulfide dihedral angle restraints:       0       0      0   0.000   0.000      0.0000       1.000
21 Lower bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
22 Upper bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
23 Distance restraints 3 (SDCH-MNCH)  :    5321       0      0   0.322   0.322      105.44       1.000
24 Sidechain Chi_5 dihedral restraints:       0       0      0   0.000   0.000      0.0000       1.000
25 Phi/Psi pair of dihedral restraints:     331       7     31  26.908  31.926      109.75       1.000
26 Distance restraints 4 (SDCH-SDCH)  :    3161       0      0   0.627   0.627      173.08       1.000
27 Distance restraints 5 (X-Y)        :       0       0      0   0.000   0.000      0.0000       1.000
28 NMR distance restraints 6 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
29 NMR distance restraints 7 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
30 Minimal distance restraints        :       0       0      0   0.000   0.000      0.0000       1.000
31 Non-bonded restraints              :       0       0      0   0.000   0.000      0.0000       1.000
32 Atomic accessibility restraints    :       0       0      0   0.000   0.000      0.0000       1.000
33 Atomic density restraints          :       0       0      0   0.000   0.000      0.0000       1.000
34 Absolute position restraints       :       0       0      0   0.000   0.000      0.0000       1.000
35 Dihedral angle difference restraint:       0       0      0   0.000   0.000      0.0000       1.000
36 GBSA implicit solvent potential    :       0       0      0   0.000   0.000      0.0000       1.000
37 EM density fitting potential       :       0       0      0   0.000   0.000      0.0000       1.000
38 SAXS restraints                    :       0       0      0   0.000   0.000      0.0000       1.000
39 Symmetry restraints                :       0       0      0   0.000   0.000      0.0000       1.000



openf___224_> Open           1U8F.V99990001
# Heavy relative violation of each residue is written to: 1U8F.V99990001
# The profile is NOT normalized by the number of restraints.
# The profiles are smoothed over a window of residues:    1
# The sum of all numbers in the file:   25390.0293



List of the violated restraints:
   A restraint is violated when the relative difference
   from the best value (RVIOL) is larger than CUTOFF.

   ICSR   ... index of a restraint in the current set.
   RESNO  ... residue numbers of the first two atoms.
   ATM    ... IUPAC atom names of the first two atoms.
   FEAT   ... the value of the feature in the model.
   restr  ... the mean of the basis restraint with the smallest
              difference from the model (local minimum).
   viol   ... difference from the local minimum.
   rviol  ... relative difference from the local minimum.
   RESTR  ... the best value (global minimum).
   VIOL   ... difference from the best value.
   RVIOL  ... relative difference from the best value.


-------------------------------------------------------------------------------------------------

Feature 25                           : Phi/Psi pair of dihedral restraints
List of the RVIOL violations larger than   :       6.5000

    #   ICSR  RESNO1/2 ATM1/2   INDATM1/2    FEAT   restr    viol   rviol   RESTR    VIOL   RVIOL
    1   8722   8G   9F C   N      54   56  -77.00  -63.20   60.31    7.50  -63.20   60.31    7.50
    1          9F   9F N   CA     56   57   14.41  -44.30                  -44.30
    2   8797  83I  84K C   N     650  652  -76.21  -62.90   70.74    8.55  -62.90   70.74    8.55
    2         84K  84K N   CA    652  653   28.68  -40.80                  -40.80
    3   8809  95E  96S C   N     743  745 -125.24  -64.10   94.24    7.13  -64.10   94.24    7.13
    3         96S  96S N   CA    745  746   36.72  -35.00                  -35.00
    4   8847 133V 134N C   N    1009 1011 -152.14 -119.90  112.64    5.75  -63.20  113.29   13.17
    4        134N 134N N   CA   1011 1012   29.07  137.00                  -41.10
    5   8861 147N 148A C   N    1126 1128   86.49 -134.00  148.29    3.45  -62.50 -167.53   30.47
    5        148A 148A N   CA   1128 1129 -162.75  147.00                  -40.90
    6   8902 188G 189P C   N    1420 1422  -43.13  -58.70   53.19    3.33  -64.50  133.17   11.09
    6        189P 189P N   CA   1422 1423  -81.36  -30.50                  147.20
    7   8947 233V 234P C   N    1746 1748  -66.73  -64.50   54.56    4.19  -58.70  123.44    9.56
    7        234P 234P N   CA   1748 1749   92.68  147.20                  -30.50


report______> Distribution of short non-bonded contacts:

DISTANCE1:  0.00 2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40
DISTANCE2:  2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40 3.50
FREQUENCY:     0    0    0    0    0   10   39   92  162  191  197  284  348  397  458


<< end of ENERGY.
openf___224_> Open           1U8F.B99990001.pdb
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523

>> Summary of successfully produced models:
Filename                          molpdf     DOPE score    GA341 score
----------------------------------------------------------------------
1U8F.B99990001.pdb            1680.89209   -37961.37891        1.00000

>> modelling missing residues
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainC.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534739    5405.019     5.278

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5534815    5405.093     5.278

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534986    5405.260     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5535836    5406.090     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5537094    5407.318     5.281

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5538998    5409.178     5.282

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5539038    5409.217     5.282

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5539128    5409.305     5.283

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5541984    5412.094     5.285

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5542044    5412.152     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5542179    5412.284     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546463    5416.468     5.290

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546551    5416.554     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546749    5416.747     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553175    5423.022     5.296

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5553307    5423.151     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553604    5423.441     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563226    5432.838     5.306

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5563426    5433.033     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563876    5433.473     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5578326    5447.584     5.320

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5578626    5447.877     5.320

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5579301    5448.536     5.321

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5600959    5469.687     5.341

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5601407    5470.124     5.342

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5602415    5471.108     5.343

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5634919    5502.851     5.374

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      5866791    5729.288     5.595
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  3:C  335:C     2523

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5877400    5739.648     5.605

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6067423    5925.218     5.786
openf___224_> Open           result\curated\tmp\chainC.seq
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainC.fasta

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5526104    5396.586     5.270

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5527554    5398.002     5.271

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5530454    5400.834     5.274

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536254    5406.498     5.280

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5537590    5407.803     5.281

Read the alignment from file       : result\curated\tmp\chainC.fasta

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  1U8F_1|Ch     335      1
openf___224_> Open           result\curated\tmp\chainC.pir
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib

openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5535475    5405.737     5.279

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536925    5407.153     5.280

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5539825    5409.985     5.283

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5545625    5415.649     5.289

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546953    5416.946     5.290

Read the alignment from file       : alignment.seg

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5676161    5543.126     5.413

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5677497    5544.431     5.414

Read the alignment from file       : alignment.seg

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     335      1        1U8F
openf___224_> Open           $(LIB)/as1.sim.mat
rdrrwgh_268_> Number of residue types:       20

Pairwise dynamic programming alignment (ALIGN):
  Residue-residue metric   : $(LIB)/as1.sim.mat
  Diagonal                 :          100
  Overhang                 :            0
  Local alignment          :            F
  MATRIX_OFFSET (local aln):       0.0000
  N_SUBOPT                 :            0
  SUBOPT_OFFSET            :       0.0000
  Alignment block          :            1
  Gap introduction penalty :    -600.0000
  Gap extension penalty    :    -400.0000
  Break-break bonus        :   10000.0000
  Length of alignment      :          335
  Score                    :  292963.0000
openf___224_> Open           alignment.seg.ali

Sequence identity comparison (ID_TABLE):

   Diagonal       ... number of residues;
   Upper triangle ... number of identical residues;
   Lower triangle ... % sequence identity, id/min(length).

         result@11U8F  @1
result@1      333     333
1U8F  @1      100     335
>> patching model...
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724447    5590.280     5.459

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724975    5590.796     5.460
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5773575    5638.257     5.506
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5786875    5651.245     5.519
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           trimmed_align.ali

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5798840    5662.930     5.530

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5800290    5664.346     5.532

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5803190    5667.178     5.534

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5808990    5672.842     5.540

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5938198    5799.021     5.663

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5939526    5800.318     5.664

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5940854    5801.615     5.666

Read the alignment from file       : trimmed_align.ali

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     333      1        1U8F
check_a_343_> >> BEGINNING OF COMMAND
openf___224_> Open           .\result\curated\tmp\chainC.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042650    5901.025     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6043500    5901.855     5.764

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6044758    5903.084     5.765

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046752    5905.031     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049743    5907.952     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054225    5912.329     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060948    5918.895     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6071020    5928.730     5.790

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6086145    5943.501     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6108811    5965.636     5.826

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6141315    5997.378     5.857

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6141279    5997.343     5.857

check_ali___> Checking the sequence-structure alignment.

Implied intrachain target CA(i)-CA(i+1) distances longer than  8.0 angstroms:

ALN_POS  TMPL  RID1  RID2  NAM1  NAM2     DIST
----------------------------------------------
END OF TABLE
check_a_344_> << END OF COMMAND
openf___224_> Open           ${LIB}/top_heav.lib
read_to_681_> topology.submodel read from topology file:        3

openf___224_> Open           ${LIB}/par.lib

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6280531    6133.331     5.990

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6282131    6134.894     5.991

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6286111    6138.780     5.995

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6288111    6140.733     5.997

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6291111    6143.663     6.000

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6295611    6148.058     6.004

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6301183    6153.499     6.009

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6303983    6156.233     6.012

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6308183    6160.335     6.016

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6314483    6166.487     6.022

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6317255    6169.194     6.025

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6318655    6170.562     6.026
read_pa_232_> parameters    BONDS   ANGLS  DIHEDS IMPROPS    MODE
                              227     561     661     112       0

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6370779    6221.464     6.076

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6619797    6464.646     6.313

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6657509    6501.474     6.349

mkilst______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572      0         0      1071

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6765141    6606.583     6.452

patch_______> segment topology patched using RTF:  1 ;  LYS  ;  NTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572   3481      4118      1071


Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6875637    6714.489     6.557
patch_______> segment topology patched using RTF:  333 ;  GLU  ;  CTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072

genseg______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072
transfe_506_> MODEL is an average of all templates.
transfe_511_> Number of templates for coordinate transfer:        1
              After transferring coordinates of the equivalent template atoms,
              there are defined, undefined atoms in MODEL:     2523        0
openf___224_> Open           1U8F.ini
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523
make_re_417_> Restraint type to be calculated:  stereo

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6983086    6819.420     6.660

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6991278    6827.420     6.667

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7007662    6843.420     6.683

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7040430    6875.420     6.714

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7073198    6907.420     6.746

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7138734    6971.420     6.808

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7171502    7003.420     6.839

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7204270    7035.420     6.871

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7269806    7099.420     6.933

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7400878    7227.420     7.058

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7466414    7291.420     7.121

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7531950    7355.420     7.183

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7663022    7483.420     7.308

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7925166    7739.420     7.558

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8056238    7867.420     7.683
r_stere_606_> Stereochemical restraints were constructed from RTF & PRMF.
              Added bond,angle,dihedral,improper restraints  :     2573    3483    3913    1060
              Total number of restraints before, now         :        0    11029
make_re_422_> Number of previous, current restraints         :        0    11029
make_re_423_> Number of previous, current selected restraints:        0    11029
make_re_417_> Restraint type to be calculated:  phi-psi_binormal

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243952    8050.734     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainC
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11029    11360
make_re_423_> Number of previous, current selected restraints:    11029    11360
make_re_417_> Restraint type to be calculated:  omega_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainC
getdata_289_> Proteins (all/accepted):        1        1
omgdel__425_> Unselected all O C +N +CA dihedrals:      344
              (This is to avoid clashes between STEREO
              and OMEGA_DIHEDRAL restraints)
make_re_422_> Number of previous, current restraints         :    11360    11692
make_re_423_> Number of previous, current selected restraints:    11360    11348
make_re_417_> Restraint type to be calculated:  chi1_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainC
getdata_289_> Proteins (all/accepted):        1        1

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8375040    8178.750     7.987
make_re_422_> Number of previous, current restraints         :    11692    11962
make_re_423_> Number of previous, current selected restraints:    11348    11618
make_re_417_> Restraint type to be calculated:  chi2_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi2.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainC
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11962    12155
make_re_423_> Number of previous, current selected restraints:    11618    11811
make_re_417_> Restraint type to be calculated:  chi3_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi3.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainC
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12155    12232
make_re_423_> Number of previous, current selected restraints:    11811    11888
make_re_417_> Restraint type to be calculated:  chi4_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi4.mdt
mdtrsr__446W> A potential that relies on one protein is used, yet you have at
              least one known structure available. MDT, not library, potential is used.
getdata_643_> Protein accepted:  result\curated\tmp\chainC
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12232    12268
make_re_423_> Number of previous, current selected restraints:    11888    11924
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at amaxhash_contac [B,KiB,MiB]:      9101628    8888.309     8.680

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9363772    9144.309     8.930

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9625916    9400.309     9.180

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10150204    9912.309     9.680
make_re_422_> Number of previous, current restraints         :    12268    19765
make_re_423_> Number of previous, current selected restraints:    11924    19421
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10412348   10168.309     9.930
make_re_422_> Number of previous, current restraints         :    19765    27367
make_re_423_> Number of previous, current selected restraints:    19421    27023
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    27367    32701
make_re_423_> Number of previous, current selected restraints:    27023    32357
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10936636   10680.309    10.430
make_re_422_> Number of previous, current restraints         :    32701    35891
make_re_423_> Number of previous, current selected restraints:    32357    35547
0 atoms in HETATM/BLK residues constrained
to protein atoms within 2.30 angstroms
and protein CA atoms within 10.00 angstroms
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35891    35891
make_re_423_> Number of previous, current selected restraints:    35547    35547
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35891    35891
make_re_423_> Number of previous, current selected restraints:    35547    35547
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35891    35891
make_re_423_> Number of previous, current selected restraints:    35547    35547
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35891    35891
make_re_423_> Number of previous, current selected restraints:    35547    35547
0 atoms in residues without defined topology
constrained to be rigid bodies
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35891    35891
make_re_423_> Number of previous, current selected restraints:    35547    35547
rmdupl__427_>     1971 redundant cosine dihedral restraints were unselected.
condens_443_> Restraints marked for deletion were removed.
              Total number of restraints before, now:    35891    33576
openf___224_> Open           1U8F.rsr
openf___224_> Open           1U8F.rsr

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10927372   10671.262    10.421

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11713804   11439.262    11.171
rdcsr2__307_> Number of restraints read    :    33576
              Number of excluded pairs read:        0
              Number of pseudo atoms read  :        0
rdcsrs__304_> Restraints in memory, selected restraints:    33576    33576
              Explicitly excluded atom pairs in memory :        0
              Pseudo atoms in memory                   :        0
openf___224_> Open           1U8F.ini

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:     11713836   11439.293    11.171
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  1:A  333:A     2523
randomi_498_> Atoms,selected atoms,random_seed,amplitude:     2523     2523        1        4.0000
randomi_496_> Amplitude is > 0; randomization is done.
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    16544
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    18709
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    19871
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    21259
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    23271
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    25501
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    27397
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    29702
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    31135

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12066960   11784.141    11.508
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    32544
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33148
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33576
iupac_m_487_> NH1/2 swapped:      175.9389       14  14
iupac_m_485_> OD1/2 will be swapped:     -131.9404       37  37
iupac_m_487_> NH1/2 swapped:     -179.8322       78  78
iupac_m_486_> OE1/2 will be swapped:      -92.2121      104  104
iupac_m_487_> NH1/2 swapped:     -179.5062      195  195
iupac_m_486_> OE1/2 will be swapped:      104.4572      221  221
iupac_m_487_> NH1/2 swapped:      170.6409      232  232
iupac_m_485_> OD1/2 will be swapped:      146.7378      242  242
iupac_m_486_> OE1/2 will be swapped:      -95.1482      248  248
iupac_m_483_> CD1/2 CE1/2 swapped:      102.0009      312  312
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_483_> CD1/2 CE1/2 swapped:      -90.6017      316  316
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
>> Model assessment by DOPE potential
iatmcls_286W> MODEL atom not classified:  GLU:OXT  GLU

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12420284   12129.184    11.845

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12541388   12247.449    11.960

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12783596   12483.980    12.191

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     13268012   12957.043    12.653

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     14236844   13903.168    13.577

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     16174508   15795.418    15.425

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     20049836   19579.918    19.121


>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33576   33576
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):   507702
Dynamic pairs routine                             : 1, NATM x NATM double loop
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        1    9999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :   15.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       F       F       F       T
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :      -38175.6992




<< end of ENERGY.
DOPE score               : -38175.699219
>> Model assessment by GA341 potential

Surface library          : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/surf5.de
Pair library             : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/pair9.de
Chain identifier         : _
% sequence identity      :   100.000000
Sequence length          :          333
Compactness              :     0.241745
Native energy (pair)     :  -302.433965
Native energy (surface)  :   -16.890126
Native energy (combined) :    -9.460616
Z score (pair)           :   -10.106106
Z score (surface)        :    -7.313187
Z score (combined)       :   -11.704280
GA341 score              :     1.000000



>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33576   33576
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):     5269
Dynamic pairs routine                             : 2, NATM x NATM cell sorting
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        0   99999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :    4.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       T       F       F       F
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :        1702.9047





Summary of the restraint violations:

   NUM     ... number of restraints.
   NUMVI   ... number of restraints with RVIOL > VIOL_REPORT_CUT[i].
   RVIOL   ... relative difference from the best value.
   NUMVP   ... number of restraints with -Ln(pdf) > VIOL_REPORT_CUT2[i].
   RMS_1   ... RMS(feature, minimally_violated_basis_restraint, NUMB).
   RMS_2   ... RMS(feature, best_value, NUMB).
   MOL.PDF ... scaled contribution to -Ln(Molecular pdf).

 #                     RESTRAINT_GROUP      NUM   NUMVI  NUMVP   RMS_1   RMS_2         MOL.PDF     S_i
------------------------------------------------------------------------------------------------------
 1 Bond length potential              :    2573       0      0   0.005   0.005      21.399       1.000
 2 Bond angle potential               :    3483       0      8   1.925   1.925      259.37       1.000
 3 Stereochemical cosine torsion poten:    1598       0     52  48.807  48.807      612.02       1.000
 4 Stereochemical improper torsion pot:    1060       0      0   1.168   1.168      34.464       1.000
 5 Soft-sphere overlap restraints     :    5269       0      0   0.001   0.001     0.78706       1.000
 6 Lennard-Jones 6-12 potential       :       0       0      0   0.000   0.000      0.0000       1.000
 7 Coulomb point-point electrostatic p:       0       0      0   0.000   0.000      0.0000       1.000
 8 H-bonding potential                :       0       0      0   0.000   0.000      0.0000       1.000
 9 Distance restraints 1 (CA-CA)      :    7497       0      0   0.082   0.082      61.585       1.000
10 Distance restraints 2 (N-O)        :    7602       0      0   0.132   0.132      133.45       1.000
11 Mainchain Phi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
12 Mainchain Psi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
13 Mainchain Omega dihedral restraints:     332       0      1   3.916   3.916      60.040       1.000
14 Sidechain Chi_1 dihedral restraints:     270       0      0  45.275  45.275      1.4352       1.000
15 Sidechain Chi_2 dihedral restraints:     193       0      0  58.084  58.084      49.117       1.000
16 Sidechain Chi_3 dihedral restraints:      77       0      0  54.200  54.200      41.347       1.000
17 Sidechain Chi_4 dihedral restraints:      36       0      0  78.195  78.195      24.608       1.000
18 Disulfide distance restraints      :       0       0      0   0.000   0.000      0.0000       1.000
19 Disulfide angle restraints         :       0       0      0   0.000   0.000      0.0000       1.000
20 Disulfide dihedral angle restraints:       0       0      0   0.000   0.000      0.0000       1.000
21 Lower bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
22 Upper bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
23 Distance restraints 3 (SDCH-MNCH)  :    5334       0      0   0.355   0.355      127.18       1.000
24 Sidechain Chi_5 dihedral restraints:       0       0      0   0.000   0.000      0.0000       1.000
25 Phi/Psi pair of dihedral restraints:     331       6     29  25.970  28.325      97.733       1.000
26 Distance restraints 4 (SDCH-SDCH)  :    3190       0      2   0.633   0.633      178.37       1.000
27 Distance restraints 5 (X-Y)        :       0       0      0   0.000   0.000      0.0000       1.000
28 NMR distance restraints 6 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
29 NMR distance restraints 7 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
30 Minimal distance restraints        :       0       0      0   0.000   0.000      0.0000       1.000
31 Non-bonded restraints              :       0       0      0   0.000   0.000      0.0000       1.000
32 Atomic accessibility restraints    :       0       0      0   0.000   0.000      0.0000       1.000
33 Atomic density restraints          :       0       0      0   0.000   0.000      0.0000       1.000
34 Absolute position restraints       :       0       0      0   0.000   0.000      0.0000       1.000
35 Dihedral angle difference restraint:       0       0      0   0.000   0.000      0.0000       1.000
36 GBSA implicit solvent potential    :       0       0      0   0.000   0.000      0.0000       1.000
37 EM density fitting potential       :       0       0      0   0.000   0.000      0.0000       1.000
38 SAXS restraints                    :       0       0      0   0.000   0.000      0.0000       1.000
39 Symmetry restraints                :       0       0      0   0.000   0.000      0.0000       1.000



openf___224_> Open           1U8F.V99990001
# Heavy relative violation of each residue is written to: 1U8F.V99990001
# The profile is NOT normalized by the number of restraints.
# The profiles are smoothed over a window of residues:    1
# The sum of all numbers in the file:   25129.1895



List of the violated restraints:
   A restraint is violated when the relative difference
   from the best value (RVIOL) is larger than CUTOFF.

   ICSR   ... index of a restraint in the current set.
   RESNO  ... residue numbers of the first two atoms.
   ATM    ... IUPAC atom names of the first two atoms.
   FEAT   ... the value of the feature in the model.
   restr  ... the mean of the basis restraint with the smallest
              difference from the model (local minimum).
   viol   ... difference from the local minimum.
   rviol  ... relative difference from the local minimum.
   RESTR  ... the best value (global minimum).
   VIOL   ... difference from the best value.
   RVIOL  ... relative difference from the best value.


-------------------------------------------------------------------------------------------------

Feature 25                           : Phi/Psi pair of dihedral restraints
List of the RVIOL violations larger than   :       6.5000

    #   ICSR  RESNO1/2 ATM1/2   INDATM1/2    FEAT   restr    viol   rviol   RESTR    VIOL   RVIOL
    1   8722   8G   9F C   N      54   56  -78.86  -63.20   59.06    7.23  -63.20   59.06    7.23
    1          9F   9F N   CA     56   57   12.64  -44.30                  -44.30
    2   8809  95E  96S C   N     743  745 -126.71  -64.10   92.68    7.23  -64.10   92.68    7.23
    2         96S  96S N   CA    745  746   33.34  -35.00                  -35.00
    3   8813  99V 100F C   N     767  769  -89.79  -63.20   67.71    7.89  -63.20   67.71    7.89
    3        100F 100F N   CA    769  770   17.97  -44.30                  -44.30
    4   8847 133V 134N C   N    1009 1011 -151.04  -63.20  110.97   12.95  -63.20  110.97   12.95
    4        134N 134N N   CA   1011 1012   26.71  -41.10                  -41.10
    5   8860 146S 147N C   N    1118 1120 -103.74  -63.20   72.59    7.82  -63.20   72.59    7.82
    5        147N 147N N   CA   1120 1121   19.12  -41.10                  -41.10
    6   8861 147N 148A C   N    1126 1128   66.92  -68.20  144.33   13.68  -62.50  178.60   27.76
    6        148A 148A N   CA   1128 1129 -163.98  145.30                  -40.90

report______> Distribution of short non-bonded contacts:


DISTANCE1:  0.00 2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40
DISTANCE2:  2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40 3.50
FREQUENCY:     0    0    0    0    0    8   34   99  144  191  218  291  330  382  431


<< end of ENERGY.
openf___224_> Open           1U8F.B99990001.pdb
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523

>> Summary of successfully produced models:
Filename                          molpdf     DOPE score    GA341 score
----------------------------------------------------------------------
1U8F.B99990001.pdb            1702.90466   -38175.69922        1.00000

>> modelling missing residues
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainD.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534739    5405.019     5.278

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5534815    5405.093     5.278

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534986    5405.260     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5535836    5406.090     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5537094    5407.318     5.281

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5538998    5409.178     5.282

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5539038    5409.217     5.282

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5539128    5409.305     5.283

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5541984    5412.094     5.285

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5542044    5412.152     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5542179    5412.284     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546463    5416.468     5.290

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546551    5416.554     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546749    5416.747     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553175    5423.022     5.296

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5553307    5423.151     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553604    5423.441     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563226    5432.838     5.306

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5563426    5433.033     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563876    5433.473     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5578326    5447.584     5.320

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5578626    5447.877     5.320

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5579301    5448.536     5.321

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5600959    5469.687     5.341

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5601407    5470.124     5.342

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5602415    5471.108     5.343

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5634919    5502.851     5.374

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      5866791    5729.288     5.595
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  3:D  335:D     2523

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5877400    5739.648     5.605

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6067423    5925.218     5.786
openf___224_> Open           result\curated\tmp\chainD.seq
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainD.fasta

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5526104    5396.586     5.270

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5527554    5398.002     5.271

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5530454    5400.834     5.274

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536254    5406.498     5.280

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5537590    5407.803     5.281

Read the alignment from file       : result\curated\tmp\chainD.fasta

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  1U8F_1|Ch     335      1
openf___224_> Open           result\curated\tmp\chainD.pir
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib

openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5535475    5405.737     5.279

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536925    5407.153     5.280

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5539825    5409.985     5.283

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5545625    5415.649     5.289

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546953    5416.946     5.290

Read the alignment from file       : alignment.seg

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5676161    5543.126     5.413

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5677497    5544.431     5.414

Read the alignment from file       : alignment.seg

Total number of alignment positions:   335

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     335      1        1U8F
openf___224_> Open           $(LIB)/as1.sim.mat
rdrrwgh_268_> Number of residue types:       20

Pairwise dynamic programming alignment (ALIGN):
  Residue-residue metric   : $(LIB)/as1.sim.mat
  Diagonal                 :          100
  Overhang                 :            0
  Local alignment          :            F
  MATRIX_OFFSET (local aln):       0.0000
  N_SUBOPT                 :            0
  SUBOPT_OFFSET            :       0.0000
  Alignment block          :            1
  Gap introduction penalty :    -600.0000
  Gap extension penalty    :    -400.0000
  Break-break bonus        :   10000.0000
  Length of alignment      :          335
  Score                    :  292963.0000
openf___224_> Open           alignment.seg.ali

Sequence identity comparison (ID_TABLE):

   Diagonal       ... number of residues;
   Upper triangle ... number of identical residues;
   Lower triangle ... % sequence identity, id/min(length).

         result@11U8F  @1
result@1      333     333
1U8F  @1      100     335
>> patching model...
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724447    5590.280     5.459

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724975    5590.796     5.460
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5773575    5638.257     5.506
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5786875    5651.245     5.519
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           trimmed_align.ali

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5798840    5662.930     5.530

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5800290    5664.346     5.532

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5803190    5667.178     5.534

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5808990    5672.842     5.540

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5938198    5799.021     5.663

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5939526    5800.318     5.664

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5940854    5801.615     5.666

Read the alignment from file       : trimmed_align.ali

Total number of alignment positions:   333

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     333      1 result\cura
  2       1U8F     333      1        1U8F
check_a_343_> >> BEGINNING OF COMMAND
openf___224_> Open           .\result\curated\tmp\chainD.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6042479    5900.858     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042650    5901.025     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6043500    5901.855     5.764

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6044758    5903.084     5.765

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6046662    5904.943     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6046752    5905.031     5.767

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6049608    5907.820     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049743    5907.952     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6054027    5912.136     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6054225    5912.329     5.774

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6060651    5918.604     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6060948    5918.895     5.780

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6070570    5928.291     5.789

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6071020    5928.730     5.790

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6085470    5942.842     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6086145    5943.501     5.804

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6107803    5964.651     5.825

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6108811    5965.636     5.826

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6141315    5997.378     5.857

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6141279    5997.343     5.857

check_ali___> Checking the sequence-structure alignment.

Implied intrachain target CA(i)-CA(i+1) distances longer than  8.0 angstroms:

ALN_POS  TMPL  RID1  RID2  NAM1  NAM2     DIST
----------------------------------------------
END OF TABLE
check_a_344_> << END OF COMMAND
openf___224_> Open           ${LIB}/top_heav.lib
read_to_681_> topology.submodel read from topology file:        3

openf___224_> Open           ${LIB}/par.lib

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6280531    6133.331     5.990

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6282131    6134.894     5.991

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6286111    6138.780     5.995

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6288111    6140.733     5.997

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6291111    6143.663     6.000

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6295611    6148.058     6.004

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6301183    6153.499     6.009

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6303983    6156.233     6.012

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6308183    6160.335     6.016

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6314483    6166.487     6.022

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6317255    6169.194     6.025

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6318655    6170.562     6.026
read_pa_232_> parameters    BONDS   ANGLS  DIHEDS IMPROPS    MODE
                              227     561     661     112       0

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6370779    6221.464     6.076

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6619797    6464.646     6.313

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6657509    6501.474     6.349

mkilst______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572      0         0      1071

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6765141    6606.583     6.452

patch_______> segment topology patched using RTF:  1 ;  LYS  ;  NTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2522   2572   3481      4118      1071


Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6875637    6714.489     6.557
patch_______> segment topology patched using RTF:  333 ;  GLU  ;  CTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072

genseg______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      333   2523   2573   3483      4120      1072
transfe_506_> MODEL is an average of all templates.
transfe_511_> Number of templates for coordinate transfer:        1
              After transferring coordinates of the equivalent template atoms,
              there are defined, undefined atoms in MODEL:     2523        0
openf___224_> Open           1U8F.ini
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523
make_re_417_> Restraint type to be calculated:  stereo

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6983086    6819.420     6.660

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6991278    6827.420     6.667

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7007662    6843.420     6.683

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7040430    6875.420     6.714

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7073198    6907.420     6.746

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7138734    6971.420     6.808

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7171502    7003.420     6.839

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7204270    7035.420     6.871

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7269806    7099.420     6.933

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7400878    7227.420     7.058

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7466414    7291.420     7.121

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7531950    7355.420     7.183

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7663022    7483.420     7.308

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7925166    7739.420     7.558

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8056238    7867.420     7.683
r_stere_606_> Stereochemical restraints were constructed from RTF & PRMF.
              Added bond,angle,dihedral,improper restraints  :     2573    3483    3913    1060
              Total number of restraints before, now         :        0    11029
make_re_422_> Number of previous, current restraints         :        0    11029
make_re_423_> Number of previous, current selected restraints:        0    11029
make_re_417_> Restraint type to be calculated:  phi-psi_binormal

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243952    8050.734     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainD
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11029    11360
make_re_423_> Number of previous, current selected restraints:    11029    11360
make_re_417_> Restraint type to be calculated:  omega_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainD
getdata_289_> Proteins (all/accepted):        1        1
omgdel__425_> Unselected all O C +N +CA dihedrals:      344
              (This is to avoid clashes between STEREO
              and OMEGA_DIHEDRAL restraints)
make_re_422_> Number of previous, current restraints         :    11360    11692
make_re_423_> Number of previous, current selected restraints:    11360    11348
make_re_417_> Restraint type to be calculated:  chi1_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8243968    8050.750     7.862
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainD
getdata_289_> Proteins (all/accepted):        1        1

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8375040    8178.750     7.987
make_re_422_> Number of previous, current restraints         :    11692    11962
make_re_423_> Number of previous, current selected restraints:    11348    11618
make_re_417_> Restraint type to be calculated:  chi2_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi2.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainD
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11962    12155
make_re_423_> Number of previous, current selected restraints:    11618    11811
make_re_417_> Restraint type to be calculated:  chi3_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi3.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainD
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12155    12232
make_re_423_> Number of previous, current selected restraints:    11811    11888
make_re_417_> Restraint type to be calculated:  chi4_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8375040    8178.750     7.987
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi4.mdt
mdtrsr__446W> A potential that relies on one protein is used, yet you have at
              least one known structure available. MDT, not library, potential is used.
getdata_643_> Protein accepted:  result\curated\tmp\chainD
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12232    12268
make_re_423_> Number of previous, current selected restraints:    11888    11924
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at amaxhash_contac [B,KiB,MiB]:      9101628    8888.309     8.680

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9363772    9144.309     8.930

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9625916    9400.309     9.180

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10150204    9912.309     9.680
make_re_422_> Number of previous, current restraints         :    12268    19742
make_re_423_> Number of previous, current selected restraints:    11924    19398
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10412348   10168.309     9.930
make_re_422_> Number of previous, current restraints         :    19742    27323
make_re_423_> Number of previous, current selected restraints:    19398    26979
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    27323    32653
make_re_423_> Number of previous, current selected restraints:    26979    32309
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10936636   10680.309    10.430
make_re_422_> Number of previous, current restraints         :    32653    35775
make_re_423_> Number of previous, current selected restraints:    32309    35431
0 atoms in HETATM/BLK residues constrained
to protein atoms within 2.30 angstroms
and protein CA atoms within 10.00 angstroms
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35775    35775
make_re_423_> Number of previous, current selected restraints:    35431    35431
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35775    35775
make_re_423_> Number of previous, current selected restraints:    35431    35431
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35775    35775
make_re_423_> Number of previous, current selected restraints:    35431    35431
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35775    35775
make_re_423_> Number of previous, current selected restraints:    35431    35431
0 atoms in residues without defined topology
constrained to be rigid bodies
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    35775    35775
make_re_423_> Number of previous, current selected restraints:    35431    35431
rmdupl__427_>     1971 redundant cosine dihedral restraints were unselected.
condens_443_> Restraints marked for deletion were removed.
              Total number of restraints before, now:    35775    33460
openf___224_> Open           1U8F.rsr
openf___224_> Open           1U8F.rsr

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10927372   10671.262    10.421

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11713804   11439.262    11.171
rdcsr2__307_> Number of restraints read    :    33460
              Number of excluded pairs read:        0
              Number of pseudo atoms read  :        0
rdcsrs__304_> Restraints in memory, selected restraints:    33460    33460
              Explicitly excluded atom pairs in memory :        0
              Pseudo atoms in memory                   :        0
openf___224_> Open           1U8F.ini

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:     11713836   11439.293    11.171
read_mo_297_> Segments, residues, atoms:        1      333     2523
read_mo_298_> Segment:        1  1:A  333:A     2523
randomi_498_> Atoms,selected atoms,random_seed,amplitude:     2523     2523        1        4.0000
randomi_496_> Amplitude is > 0; randomization is done.
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    16516
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    18696
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    19847
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    21218
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    23214
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    25432
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    27310
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    29605
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    31019

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12066960   11784.141    11.508
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    32427
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33016
pick_re_612_> Number of MODEL atoms, selected restraints;     2523    33460
iupac_m_487_> NH1/2 swapped:      177.7113       14  14
iupac_m_485_> OD1/2 will be swapped:     -167.4757       27  27
iupac_m_485_> OD1/2 will be swapped:      103.4066       37  37
iupac_m_483_> CD1/2 CE1/2 swapped:      -95.3692       45  45
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_486_> OE1/2 will be swapped:       96.7416       95  95
iupac_m_486_> OE1/2 will be swapped:     -175.4149      221  221
iupac_m_487_> NH1/2 swapped:      170.7988      232  232
iupac_m_485_> OD1/2 will be swapped:      149.7225      242  242
iupac_m_486_> OE1/2 will be swapped:      179.8673      248  248
iupac_m_483_> CD1/2 CE1/2 swapped:       97.9020      312  312
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_486_> OE1/2 will be swapped:     -161.4249      315  315
iupac_m_483_> CD1/2 CE1/2 swapped:     -102.3345      316  316
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
>> Model assessment by DOPE potential
iatmcls_286W> MODEL atom not classified:  GLU:OXT  GLU

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12420284   12129.184    11.845

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12541388   12247.449    11.960

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12783596   12483.980    12.191

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     13268012   12957.043    12.653

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     14236844   13903.168    13.577

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     16174508   15795.418    15.425

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     20049836   19579.918    19.121


>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33460   33460
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):   506013
Dynamic pairs routine                             : 1, NATM x NATM double loop
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        1    9999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :   15.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       F       F       F       T
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :      -38168.3320




<< end of ENERGY.
DOPE score               : -38168.332031
>> Model assessment by GA341 potential

Surface library          : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/surf5.de
Pair library             : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/pair9.de
Chain identifier         : _
% sequence identity      :   100.000000
Sequence length          :          333
Compactness              :     0.241360
Native energy (pair)     :  -312.570954
Native energy (surface)  :   -17.385930
Native energy (combined) :   -10.028801
Z score (pair)           :   -10.487349
Z score (surface)        :    -7.720951
Z score (combined)       :   -12.249223
GA341 score              :     1.000000



>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      333
Number of all, selected real atoms                :     2523    2523
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    33460   33460
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):     5252
Dynamic pairs routine                             : 2, NATM x NATM cell sorting
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        0   99999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :    4.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       T       F       F       F
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :        1786.5005





Summary of the restraint violations:

   NUM     ... number of restraints.
   NUMVI   ... number of restraints with RVIOL > VIOL_REPORT_CUT[i].
   RVIOL   ... relative difference from the best value.
   NUMVP   ... number of restraints with -Ln(pdf) > VIOL_REPORT_CUT2[i].
   RMS_1   ... RMS(feature, minimally_violated_basis_restraint, NUMB).
   RMS_2   ... RMS(feature, best_value, NUMB).
   MOL.PDF ... scaled contribution to -Ln(Molecular pdf).

 #                     RESTRAINT_GROUP      NUM   NUMVI  NUMVP   RMS_1   RMS_2         MOL.PDF     S_i
------------------------------------------------------------------------------------------------------
 1 Bond length potential              :    2573       0      0   0.005   0.005      21.557       1.000
 2 Bond angle potential               :    3483       0      9   1.954   1.954      267.53       1.000
 3 Stereochemical cosine torsion poten:    1598       0     53  48.669  48.669      606.47       1.000
 4 Stereochemical improper torsion pot:    1060       0      0   1.191   1.191      36.534       1.000
 5 Soft-sphere overlap restraints     :    5252       0      0   0.001   0.001     0.57263       1.000
 6 Lennard-Jones 6-12 potential       :       0       0      0   0.000   0.000      0.0000       1.000
 7 Coulomb point-point electrostatic p:       0       0      0   0.000   0.000      0.0000       1.000
 8 H-bonding potential                :       0       0      0   0.000   0.000      0.0000       1.000
 9 Distance restraints 1 (CA-CA)      :    7474       0      0   0.085   0.085      66.263       1.000
10 Distance restraints 2 (N-O)        :    7581       1      3   0.156   0.156      177.33       1.000
11 Mainchain Phi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
12 Mainchain Psi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
13 Mainchain Omega dihedral restraints:     332       0      3   3.867   3.867      58.541       1.000
14 Sidechain Chi_1 dihedral restraints:     270       0      1  42.899  42.899     -9.8092       1.000
15 Sidechain Chi_2 dihedral restraints:     193       0      2  58.964  58.964      54.976       1.000
16 Sidechain Chi_3 dihedral restraints:      77       0      0  60.502  60.502      43.249       1.000
17 Sidechain Chi_4 dihedral restraints:      36       0      0  86.398  86.398      23.676       1.000
18 Disulfide distance restraints      :       0       0      0   0.000   0.000      0.0000       1.000
19 Disulfide angle restraints         :       0       0      0   0.000   0.000      0.0000       1.000
20 Disulfide dihedral angle restraints:       0       0      0   0.000   0.000      0.0000       1.000
21 Lower bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
22 Upper bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
23 Distance restraints 3 (SDCH-MNCH)  :    5330       0      0   0.366   0.366      135.25       1.000
24 Sidechain Chi_5 dihedral restraints:       0       0      0   0.000   0.000      0.0000       1.000
25 Phi/Psi pair of dihedral restraints:     331       7     33  27.009  31.943      121.81       1.000
26 Distance restraints 4 (SDCH-SDCH)  :    3122       0      0   0.642   0.642      182.56       1.000
27 Distance restraints 5 (X-Y)        :       0       0      0   0.000   0.000      0.0000       1.000
28 NMR distance restraints 6 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
29 NMR distance restraints 7 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
30 Minimal distance restraints        :       0       0      0   0.000   0.000      0.0000       1.000
31 Non-bonded restraints              :       0       0      0   0.000   0.000      0.0000       1.000
32 Atomic accessibility restraints    :       0       0      0   0.000   0.000      0.0000       1.000
33 Atomic density restraints          :       0       0      0   0.000   0.000      0.0000       1.000
34 Absolute position restraints       :       0       0      0   0.000   0.000      0.0000       1.000
35 Dihedral angle difference restraint:       0       0      0   0.000   0.000      0.0000       1.000
36 GBSA implicit solvent potential    :       0       0      0   0.000   0.000      0.0000       1.000
37 EM density fitting potential       :       0       0      0   0.000   0.000      0.0000       1.000
38 SAXS restraints                    :       0       0      0   0.000   0.000      0.0000       1.000
39 Symmetry restraints                :       0       0      0   0.000   0.000      0.0000       1.000



openf___224_> Open           1U8F.V99990001
# Heavy relative violation of each residue is written to: 1U8F.V99990001
# The profile is NOT normalized by the number of restraints.
# The profiles are smoothed over a window of residues:    1
# The sum of all numbers in the file:   25448.6250



List of the violated restraints:
   A restraint is violated when the relative difference
   from the best value (RVIOL) is larger than CUTOFF.

   ICSR   ... index of a restraint in the current set.
   RESNO  ... residue numbers of the first two atoms.
   ATM    ... IUPAC atom names of the first two atoms.
   FEAT   ... the value of the feature in the model.
   restr  ... the mean of the basis restraint with the smallest
              difference from the model (local minimum).
   viol   ... difference from the local minimum.
   rviol  ... relative difference from the local minimum.
   RESTR  ... the best value (global minimum).
   VIOL   ... difference from the best value.
   RVIOL  ... relative difference from the best value.


-------------------------------------------------------------------------------------------------

Feature 25                           : Phi/Psi pair of dihedral restraints
List of the RVIOL violations larger than   :       6.5000

    #   ICSR  RESNO1/2 ATM1/2   INDATM1/2    FEAT   restr    viol   rviol   RESTR    VIOL   RVIOL
    1   8775  61E  62N C   N     478  480   59.11  -63.20  165.57   18.76   55.90  167.83   11.98
    1         62N  62N N   CA    480  481 -152.70  -41.10                   39.50
    2   8776  62N  63G C   N     486  488  -70.44  -62.40   25.19    3.46   82.20  154.82   11.22
    2         63G  63G N   CA    488  489  -17.33  -41.20                    8.50
    3   8813  99V 100F C   N     767  769  -87.74  -63.20   64.54    7.55  -63.20   64.54    7.55
    3        100F 100F N   CA    769  770   15.40  -44.30                  -44.30
    4   8847 133V 134N C   N    1009 1011 -151.42 -119.90  110.70    5.65  -63.20  113.86   13.15
    4        134N 134N N   CA   1011 1012   30.88  137.00                  -41.10
    5   8861 147N 148A C   N    1126 1128   83.74 -134.00  150.97    3.52  -62.50 -169.82   30.04
    5        148A 148A N   CA   1128 1129 -162.48  147.00                  -40.90
    6   8903 189P 190S C   N    1427 1429 -149.28 -136.60   63.68    3.45  -64.10  150.27   10.45
    6        190S 190S N   CA   1429 1430   88.80  151.20                  -35.00
    7   8979 265E 266G C   N    1993 1995  -83.67  -62.40   50.77    8.71  -62.40   50.77    8.71
    7        266G 266G N   CA   1995 1996  -87.30  -41.20                  -41.20


report______> Distribution of short non-bonded contacts:

DISTANCE1:  0.00 2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40
DISTANCE2:  2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40 3.50
FREQUENCY:     0    0    0    0    0   13   30   80  144  184  213  305  325  377  423


<< end of ENERGY.
openf___224_> Open           1U8F.B99990001.pdb
wrpdb___568_> Residues, atoms, selected atoms:      333     2523     2523

>> Summary of successfully produced models:
Filename                          molpdf     DOPE score    GA341 score
----------------------------------------------------------------------
1U8F.B99990001.pdb            1786.50049   -38168.33203        1.00000


UNIPROT: Q9HB71, PDB: AF-Q9HB71-F1-model_v1
> downloading AlphaFold structure AF-Q9HB71-F1-model_v1

UNIPROT: P15311, PDB: 1NI2
> downloading PDB 1NI2
> downloading FASTA for 1NI2
>> modelling missing residues
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainA.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534739    5405.019     5.278

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5534815    5405.093     5.278

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534986    5405.260     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5535836    5406.090     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5537094    5407.318     5.281

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5538998    5409.178     5.282

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5539038    5409.217     5.282

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5539128    5409.305     5.283

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5541984    5412.094     5.285

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5542044    5412.152     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5542179    5412.284     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546463    5416.468     5.290

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546551    5416.554     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546749    5416.747     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553175    5423.022     5.296

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5553307    5423.151     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553604    5423.441     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563226    5432.838     5.306

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5563426    5433.033     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563876    5433.473     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5578326    5447.584     5.320

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5578626    5447.877     5.320

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5579301    5448.536     5.321

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5600959    5469.687     5.341

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5601407    5470.124     5.342

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5602415    5471.108     5.343

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5634919    5502.851     5.374

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      5866791    5729.288     5.595
read_mo_297_> Segments, residues, atoms:        1      296     2451
read_mo_298_> Segment:        1  2:A  297:A     2451

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5876327    5738.601     5.604

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6052321    5910.470     5.772
openf___224_> Open           result\curated\tmp\chainA.seq
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainA.fasta

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5526104    5396.586     5.270

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5527554    5398.002     5.271

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5530454    5400.834     5.274

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536254    5406.498     5.280

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5537434    5407.650     5.281

Read the alignment from file       : result\curated\tmp\chainA.fasta

Total number of alignment positions:   296

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  1NI2_1|Ch     296      1
openf___224_> Open           result\curated\tmp\chainA.pir
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib

openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5535475    5405.737     5.279

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536925    5407.153     5.280

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5539825    5409.985     5.283

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5545625    5415.649     5.289

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546805    5416.802     5.290

Read the alignment from file       : alignment.seg

Total number of alignment positions:   296

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     296      1 result\cura
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5676013    5542.981     5.413

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5677193    5544.134     5.414

Read the alignment from file       : alignment.seg

Total number of alignment positions:   296

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     296      1 result\cura
  2       1NI2     296      1        1NI2
openf___224_> Open           $(LIB)/as1.sim.mat
rdrrwgh_268_> Number of residue types:       20

Pairwise dynamic programming alignment (ALIGN):
  Residue-residue metric   : $(LIB)/as1.sim.mat
  Diagonal                 :          100
  Overhang                 :            0
  Local alignment          :            F
  MATRIX_OFFSET (local aln):       0.0000
  N_SUBOPT                 :            0
  SUBOPT_OFFSET            :       0.0000
  Alignment block          :            1
  Gap introduction penalty :    -600.0000
  Gap extension penalty    :    -400.0000
  Break-break bonus        :   10000.0000
  Length of alignment      :          296
  Score                    :  261572.0000
openf___224_> Open           alignment.seg.ali

Sequence identity comparison (ID_TABLE):

   Diagonal       ... number of residues;
   Upper triangle ... number of identical residues;
   Lower triangle ... % sequence identity, id/min(length).

         result@11NI2  @1
result@1      296     296
1NI2  @1      100     296
>> patching model...
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724447    5590.280     5.459

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724975    5590.796     5.460
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5773575    5638.257     5.506
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5786875    5651.245     5.519
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           trimmed_align.ali

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5798840    5662.930     5.530

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5800290    5664.346     5.532

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5803190    5667.178     5.534

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5808990    5672.842     5.540

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5938198    5799.021     5.663

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5939378    5800.174     5.664

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5940558    5801.326     5.665

Read the alignment from file       : trimmed_align.ali

Total number of alignment positions:   296

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     296      1 result\cura
  2       1NI2     296      1        1NI2
check_a_343_> >> BEGINNING OF COMMAND
openf___224_> Open           .\result\curated\tmp\chainA.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6031083    5889.729     5.752

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6031083    5889.729     5.752

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6031254    5889.896     5.752

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6032104    5890.727     5.753

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6033362    5891.955     5.754

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6035266    5893.814     5.756

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6035266    5893.814     5.756

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6035356    5893.902     5.756

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6038212    5896.691     5.758

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6038212    5896.691     5.758

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6038347    5896.823     5.759

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042631    5901.007     5.763

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6042631    5901.007     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042829    5901.200     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049255    5907.476     5.769

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6049255    5907.476     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049552    5907.766     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6059174    5917.162     5.778

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6059174    5917.162     5.778

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6059624    5917.602     5.779

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6074074    5931.713     5.793

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6074074    5931.713     5.793

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6074749    5932.372     5.793

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6096407    5953.522     5.814

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6096407    5953.522     5.814

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6097415    5954.507     5.815

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6129919    5986.249     5.846

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6129550    5985.889     5.846

check_ali___> Checking the sequence-structure alignment.

Implied intrachain target CA(i)-CA(i+1) distances longer than  8.0 angstroms:

ALN_POS  TMPL  RID1  RID2  NAM1  NAM2     DIST
----------------------------------------------
END OF TABLE
check_a_344_> << END OF COMMAND
openf___224_> Open           ${LIB}/top_heav.lib
read_to_681_> topology.submodel read from topology file:        3

openf___224_> Open           ${LIB}/par.lib

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6268802    6121.877     5.978

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6270402    6123.439     5.980

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6274382    6127.326     5.984

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6276382    6129.279     5.986

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6279382    6132.209     5.988

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6283882    6136.604     5.993

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6289454    6142.045     5.998

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6292254    6144.779     6.001

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6296454    6148.881     6.005

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6302754    6155.033     6.011

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6305526    6157.740     6.013

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6306926    6159.107     6.015
read_pa_232_> parameters    BONDS   ANGLS  DIHEDS IMPROPS    MODE
                              227     561     661     112       0

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6353241    6204.337     6.059

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6596673    6442.063     6.291

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6633841    6478.360     6.327

getf_______W> RTF restraint not found in the atoms list:
              residue type, indices:    13     1
              atom names           : N     -C    CA    CD
              atom indices         :     1     0     2     3

mkilst______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      296   2465   2526      0         0      1059

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6739117    6581.169     6.427

patch_______> segment topology patched using RTF:  1 ;  PRO  ;  PROP
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      296   2465   2526   3406      4027      1059


Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6849613    6689.075     6.532
patch_______> segment topology patched using RTF:  296 ;  PRO  ;  CTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      296   2466   2527   3408      4029      1060

genseg______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      296   2466   2527   3408      4029      1060
transfe_506_> MODEL is an average of all templates.
transfe_511_> Number of templates for coordinate transfer:        1
              After transferring coordinates of the equivalent template atoms,
              there are defined, undefined atoms in MODEL:     2451       15
openf___224_> Open           1NI2.ini
wrpdb___568_> Residues, atoms, selected atoms:      296     2466     2466
make_re_417_> Restraint type to be calculated:  stereo

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6957062    6794.006     6.635

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6965254    6802.006     6.643

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6981638    6818.006     6.658

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7014406    6850.006     6.689

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7047174    6882.006     6.721

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7112710    6946.006     6.783

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7145478    6978.006     6.814

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7178246    7010.006     6.846

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7243782    7074.006     6.908

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7374854    7202.006     7.033

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7440390    7266.006     7.096

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7505926    7330.006     7.158

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7636998    7458.006     7.283

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7899142    7714.006     7.533

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8030214    7842.006     7.658
r_stere_606_> Stereochemical restraints were constructed from RTF & PRMF.
              Added bond,angle,dihedral,improper restraints  :     2527    3408    3842    1046
              Total number of restraints before, now         :        0    10823
make_re_422_> Number of previous, current restraints         :        0    10823
make_re_423_> Number of previous, current selected restraints:        0    10823
make_re_417_> Restraint type to be calculated:  phi-psi_binormal

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8204557    8012.263     7.824
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.mdt
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        5      147  SER
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        5      150  ARG
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        5      161  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        5      257  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        6      150  ARG
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        6      161  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        6      257  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        7      150  ARG
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        7      161  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        7      257  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        8      150  ARG
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        8      161  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        8      257  LYS
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    10823    11117
make_re_423_> Number of previous, current selected restraints:    10823    11117
make_re_417_> Restraint type to be calculated:  omega_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8204573    8012.278     7.824
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
omgdel__425_> Unselected all O C +N +CA dihedrals:      309
              (This is to avoid clashes between STEREO
              and OMEGA_DIHEDRAL restraints)
make_re_422_> Number of previous, current restraints         :    11117    11412
make_re_423_> Number of previous, current selected restraints:    11117    11103
make_re_417_> Restraint type to be calculated:  chi1_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8204573    8012.278     7.824
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8335645    8140.278     7.949
make_re_422_> Number of previous, current restraints         :    11412    11679
make_re_423_> Number of previous, current selected restraints:    11103    11370
make_re_417_> Restraint type to be calculated:  chi2_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8335645    8140.278     7.949
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi2.mdt

getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11679    11907
make_re_423_> Number of previous, current selected restraints:    11370    11598
make_re_417_> Restraint type to be calculated:  chi3_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8335645    8140.278     7.949
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi3.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11907    12012
make_re_423_> Number of previous, current selected restraints:    11598    11703
make_re_417_> Restraint type to be calculated:  chi4_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8335645    8140.278     7.949
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi4.mdt
mdtrsr__446W> A potential that relies on one protein is used, yet you have at
              least one known structure available. MDT, not library, potential is used.
getdata_643_> Protein accepted:  result\curated\tmp\chainA
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12012    12059
make_re_423_> Number of previous, current selected restraints:    11703    11750
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at amaxhash_contac [B,KiB,MiB]:      9045817    8833.806     8.627

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9307961    9089.806     8.877

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9570105    9345.806     9.127
make_re_422_> Number of previous, current restraints         :    12059    17552
make_re_423_> Number of previous, current selected restraints:    11750    17243
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10094393    9857.806     9.627
make_re_422_> Number of previous, current restraints         :    17552    23040
make_re_423_> Number of previous, current selected restraints:    17243    22731
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10356537   10113.806     9.877
make_re_422_> Number of previous, current restraints         :    23040    28290
make_re_423_> Number of previous, current selected restraints:    22731    27981
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    28290    31532
make_re_423_> Number of previous, current selected restraints:    27981    31223
0 atoms in HETATM/BLK residues constrained
to protein atoms within 2.30 angstroms
and protein CA atoms within 10.00 angstroms
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    31532    31532
make_re_423_> Number of previous, current selected restraints:    31223    31223
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    31532    31532
make_re_423_> Number of previous, current selected restraints:    31223    31223
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    31532    31532
make_re_423_> Number of previous, current selected restraints:    31223    31223
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    31532    31532
make_re_423_> Number of previous, current selected restraints:    31223    31223
0 atoms in residues without defined topology
constrained to be rigid bodies
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    31532    31532
make_re_423_> Number of previous, current selected restraints:    31223    31223
rmdupl__427_>     1891 redundant cosine dihedral restraints were unselected.
condens_443_> Restraints marked for deletion were removed.
              Total number of restraints before, now:    31532    29332
openf___224_> Open           1NI2.rsr
openf___224_> Open           1NI2.rsr

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10372373   10129.271     9.892

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11158805   10897.271    10.642
rdcsr2__307_> Number of restraints read    :    29332
              Number of excluded pairs read:        0
              Number of pseudo atoms read  :        0
rdcsrs__304_> Restraints in memory, selected restraints:    29332    29332
              Explicitly excluded atom pairs in memory :        0
              Pseudo atoms in memory                   :        0
openf___224_> Open           1NI2.ini

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:     11158837   10897.302    10.642
read_mo_297_> Segments, residues, atoms:        1      296     2466
read_mo_298_> Segment:        1  1:A  296:A     2466
randomi_498_> Atoms,selected atoms,random_seed,amplitude:     2466     2466        1        4.0000
randomi_496_> Amplitude is > 0; randomization is done.
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    16260
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    18358
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    19475
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    20755
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    22734
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    23932
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    25945
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    27844

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11510593   11240.813    10.977
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    28811
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    28964
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    29332
iupac_m_486_> OE1/2 will be swapped:      178.5606       16  16
iupac_m_485_> OD1/2 will be swapped:      137.3723       30  30
iupac_m_483_> CD1/2 CE1/2 swapped:      100.5141       43  43
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_485_> OD1/2 will be swapped:      113.0247       61  61
iupac_m_486_> OE1/2 will be swapped:     -101.4016       72  72
iupac_m_483_> CD1/2 CE1/2 swapped:       96.6394       83  83
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_486_> OE1/2 will be swapped:     -168.4118       86  86
iupac_m_486_> OE1/2 will be swapped:     -122.8298       91  91
iupac_m_483_> CD1/2 CE1/2 swapped:      -90.0659      102  102
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_484W> Dihedral still outside +-90:       90.4863
iupac_m_486_> OE1/2 will be swapped:      -96.3194      107  107
iupac_m_483_> CD1/2 CE1/2 swapped:       98.5740      127  127
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_485_> OD1/2 will be swapped:      104.0653      135  135
iupac_m_486_> OE1/2 will be swapped:      165.4639      149  149
iupac_m_487_> NH1/2 swapped:      175.9534      164  164
iupac_m_485_> OD1/2 will be swapped:      172.3516      165  165
iupac_m_485_> OD1/2 will be swapped:       97.8703      220  220
iupac_m_485_> OD1/2 will be swapped:      117.3726      230  230
iupac_m_483_> CD1/2 CE1/2 swapped:       97.0304      239  239
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_483_> CD1/2 CE1/2 swapped:      114.8542      249  249
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_485_> OD1/2 will be swapped:      136.7239      260  260
iupac_m_487_> NH1/2 swapped:     -173.2932      272  272
iupac_m_486_> OE1/2 will be swapped:       96.6955      288  288
iupac_m_487_> NH1/2 swapped:      179.1755      292  292
>> Model assessment by DOPE potential
iatmcls_286W> MODEL atom not classified:  PRO:OXT  PRO

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11862549   11584.521    11.313

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11980917   11700.114    11.426

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12217653   11931.302    11.652

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12691125   12393.677    12.103

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     13638069   13318.427    13.006

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     15531957   15167.927    14.812

>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      296
Number of all, selected real atoms                :     2466    2466
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    29332   29332
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):   454678
Dynamic pairs routine                             : 1, NATM x NATM double loop
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        1    9999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :   15.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       F       F       F       T
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :      -35088.0273




<< end of ENERGY.
DOPE score               : -35088.027344
>> Model assessment by GA341 potential

Surface library          : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/surf5.de
Pair library             : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/pair9.de
Chain identifier         : _
% sequence identity      :   100.000000
Sequence length          :          296
Compactness              :     0.218228
Native energy (pair)     :  -291.819118
Native energy (surface)  :   -25.473425
Native energy (combined) :   -11.298546
Z score (pair)           :    -7.797451
Z score (surface)        :    -8.414513
Z score (combined)       :   -12.156604
GA341 score              :     1.000000



>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      296
Number of all, selected real atoms                :     2466    2466
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    29332   29332
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):     5102
Dynamic pairs routine                             : 2, NATM x NATM cell sorting
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        0   99999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :    4.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       T       F       F       F
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :        1534.1250





Summary of the restraint violations:

   NUM     ... number of restraints.
   NUMVI   ... number of restraints with RVIOL > VIOL_REPORT_CUT[i].
   RVIOL   ... relative difference from the best value.
   NUMVP   ... number of restraints with -Ln(pdf) > VIOL_REPORT_CUT2[i].
   RMS_1   ... RMS(feature, minimally_violated_basis_restraint, NUMB).
   RMS_2   ... RMS(feature, best_value, NUMB).
   MOL.PDF ... scaled contribution to -Ln(Molecular pdf).

 #                     RESTRAINT_GROUP      NUM   NUMVI  NUMVP   RMS_1   RMS_2         MOL.PDF     S_i
------------------------------------------------------------------------------------------------------
 1 Bond length potential              :    2527       0      0   0.005   0.005      16.790       1.000
 2 Bond angle potential               :    3408       0      4   1.810   1.810      219.71       1.000
 3 Stereochemical cosine torsion poten:    1642       0     33  45.545  45.545      533.27       1.000
 4 Stereochemical improper torsion pot:    1046       0      0   1.169   1.169      29.931       1.000
 5 Soft-sphere overlap restraints     :    5102       0      0   0.002   0.002      1.5929       1.000
 6 Lennard-Jones 6-12 potential       :       0       0      0   0.000   0.000      0.0000       1.000
 7 Coulomb point-point electrostatic p:       0       0      0   0.000   0.000      0.0000       1.000
 8 H-bonding potential                :       0       0      0   0.000   0.000      0.0000       1.000
 9 Distance restraints 1 (CA-CA)      :    5493       0      0   0.098   0.098      62.413       1.000
10 Distance restraints 2 (N-O)        :    5488       0      3   0.148   0.148      111.27       1.000
11 Mainchain Phi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
12 Mainchain Psi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
13 Mainchain Omega dihedral restraints:     295       0      2   3.812   3.812      48.976       1.000
14 Sidechain Chi_1 dihedral restraints:     267       0      2  45.884  45.884      10.205       1.000
15 Sidechain Chi_2 dihedral restraints:     228       0      2  57.662  57.662      54.415       1.000
16 Sidechain Chi_3 dihedral restraints:     105       0      0  65.843  65.843      62.836       1.000
17 Sidechain Chi_4 dihedral restraints:      47       0      0  78.915  78.915      33.033       1.000
18 Disulfide distance restraints      :       0       0      0   0.000   0.000      0.0000       1.000
19 Disulfide angle restraints         :       0       0      0   0.000   0.000      0.0000       1.000
20 Disulfide dihedral angle restraints:       0       0      0   0.000   0.000      0.0000       1.000
21 Lower bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
22 Upper bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
23 Distance restraints 3 (SDCH-MNCH)  :    5250       0      0   0.385   0.385      141.12       1.000
24 Sidechain Chi_5 dihedral restraints:       0       0      0   0.000   0.000      0.0000       1.000
25 Phi/Psi pair of dihedral restraints:     294       5     15  25.231  28.844     -23.592       1.000
26 Distance restraints 4 (SDCH-SDCH)  :    3242       0      2   0.717   0.717      232.16       1.000
27 Distance restraints 5 (X-Y)        :       0       0      0   0.000   0.000      0.0000       1.000
28 NMR distance restraints 6 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
29 NMR distance restraints 7 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
30 Minimal distance restraints        :       0       0      0   0.000   0.000      0.0000       1.000
31 Non-bonded restraints              :       0       0      0   0.000   0.000      0.0000       1.000
32 Atomic accessibility restraints    :       0       0      0   0.000   0.000      0.0000       1.000
33 Atomic density restraints          :       0       0      0   0.000   0.000      0.0000       1.000
34 Absolute position restraints       :       0       0      0   0.000   0.000      0.0000       1.000
35 Dihedral angle difference restraint:       0       0      0   0.000   0.000      0.0000       1.000
36 GBSA implicit solvent potential    :       0       0      0   0.000   0.000      0.0000       1.000
37 EM density fitting potential       :       0       0      0   0.000   0.000      0.0000       1.000
38 SAXS restraints                    :       0       0      0   0.000   0.000      0.0000       1.000
39 Symmetry restraints                :       0       0      0   0.000   0.000      0.0000       1.000



openf___224_> Open           1NI2.V99990001
# Heavy relative violation of each residue is written to: 1NI2.V99990001
# The profile is NOT normalized by the number of restraints.
# The profiles are smoothed over a window of residues:    1
# The sum of all numbers in the file:   23975.7500



List of the violated restraints:
   A restraint is violated when the relative difference
   from the best value (RVIOL) is larger than CUTOFF.

   ICSR   ... index of a restraint in the current set.
   RESNO  ... residue numbers of the first two atoms.
   ATM    ... IUPAC atom names of the first two atoms.
   FEAT   ... the value of the feature in the model.
   restr  ... the mean of the basis restraint with the smallest
              difference from the model (local minimum).
   viol   ... difference from the local minimum.
   rviol  ... relative difference from the local minimum.
   RESTR  ... the best value (global minimum).
   VIOL   ... difference from the best value.
   RVIOL  ... relative difference from the best value.


-------------------------------------------------------------------------------------------------

Feature 25                           : Phi/Psi pair of dihedral restraints
List of the RVIOL violations larger than   :       6.5000

    #   ICSR  RESNO1/2 ATM1/2   INDATM1/2    FEAT   restr    viol   rviol   RESTR    VIOL   RVIOL
    1   8758 135D 136Y C   N    1100 1102  110.05   55.90   93.68   10.42   55.90   93.68   10.42
    1        136Y 136Y N   CA   1102 1103  115.94   39.50                   39.50
    2   8872 249F 250N C   N    2060 2062 -131.41 -119.90   51.44    2.57  -63.20  145.01   15.61
    2        250N 250N N   CA   2062 2063   86.86  137.00                  -41.10
    3   8873 250N 251D C   N    2068 2070   74.08  -70.90  165.42    8.90  -96.50  176.05    7.23
    3        251D 251D N   CA   2070 2071   70.63  150.30                  114.20
    4   8884 261K 262K C   N    2161 2163  177.09  -62.90  120.05   19.80   56.60  146.01   11.32
    4        262K 262K N   CA   2163 2164  -43.87  -40.80                   38.60
    5   8887 264P 265D C   N    2182 2184   93.44   54.50   93.29    9.93  -70.90  166.17   11.69
    5        265D 265D N   CA   2184 2185  125.67   40.90                  150.30


report______> Distribution of short non-bonded contacts:

DISTANCE1:  0.00 2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40
DISTANCE2:  2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40 3.50
FREQUENCY:     0    0    0    0    0    6   32  104  115  171  228  285  330  367  420


<< end of ENERGY.
openf___224_> Open           1NI2.B99990001.pdb
wrpdb___568_> Residues, atoms, selected atoms:      296     2466     2466

>> Summary of successfully produced models:
Filename                          molpdf     DOPE score    GA341 score
----------------------------------------------------------------------
1NI2.B99990001.pdb            1534.12500   -35088.02734        1.00000

>> modelling missing residues
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainB.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534739    5405.019     5.278

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5534815    5405.093     5.278

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5534986    5405.260     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5535836    5406.090     5.279

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5537094    5407.318     5.281

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5538998    5409.178     5.282

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5539038    5409.217     5.282

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5539128    5409.305     5.283

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5541984    5412.094     5.285

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5542044    5412.152     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5542179    5412.284     5.285

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546463    5416.468     5.290

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546551    5416.554     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5546749    5416.747     5.290

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553175    5423.022     5.296

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5553307    5423.151     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5553604    5423.441     5.296

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563226    5432.838     5.306

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5563426    5433.033     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5563876    5433.473     5.306

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5578326    5447.584     5.320

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5578626    5447.877     5.320

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5579301    5448.536     5.321

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5600959    5469.687     5.341

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5601407    5470.124     5.342

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5602415    5471.108     5.343

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      5634919    5502.851     5.374

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      5866791    5729.288     5.595
read_mo_297_> Segments, residues, atoms:        1      296     2457
read_mo_298_> Segment:        1  2:B  297:B     2457

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5876327    5738.601     5.604

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6052525    5910.669     5.772
openf___224_> Open           result\curated\tmp\chainB.seq
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           result\curated\tmp\chainB.fasta

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5526104    5396.586     5.270

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5527554    5398.002     5.271

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5530454    5400.834     5.274

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536254    5406.498     5.280

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5537434    5407.650     5.281

Read the alignment from file       : result\curated\tmp\chainB.fasta

Total number of alignment positions:   296

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  1NI2_1|Ch     296      1
openf___224_> Open           result\curated\tmp\chainB.pir
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461082    5333.088     5.208

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5461610    5333.604     5.209
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5510210    5381.064     5.255
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5523510    5394.053     5.268
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib

openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5535475    5405.737     5.279

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5536925    5407.153     5.280

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5539825    5409.985     5.283

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5545625    5415.649     5.289

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5546805    5416.802     5.290

Read the alignment from file       : alignment.seg

Total number of alignment positions:   296

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     296      1 result\cura
openf___224_> Open           alignment.seg

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5676013    5542.981     5.413

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5677193    5544.134     5.414

Read the alignment from file       : alignment.seg

Total number of alignment positions:   296

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     296      1 result\cura
  2       1NI2     296      1        1NI2
openf___224_> Open           $(LIB)/as1.sim.mat
rdrrwgh_268_> Number of residue types:       20

Pairwise dynamic programming alignment (ALIGN):
  Residue-residue metric   : $(LIB)/as1.sim.mat
  Diagonal                 :          100
  Overhang                 :            0
  Local alignment          :            F
  MATRIX_OFFSET (local aln):       0.0000
  N_SUBOPT                 :            0
  SUBOPT_OFFSET            :       0.0000
  Alignment block          :            1
  Gap introduction penalty :    -600.0000
  Gap extension penalty    :    -400.0000
  Break-break bonus        :   10000.0000
  Length of alignment      :          296
  Score                    :  261572.0000
openf___224_> Open           alignment.seg.ali

Sequence identity comparison (ID_TABLE):

   Diagonal       ... number of residues;
   Upper triangle ... number of identical residues;
   Lower triangle ... % sequence identity, id/min(length).

         result@11NI2  @1
result@1      296     296
1NI2  @1      100     296
>> patching model...
openf___224_> Open           $(LIB)/restyp.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/resgrp.lib
rdresgr_266_> Number of residue groups:        2
openf___224_> Open           ${MODINSTALL10v2}/modlib/sstruc.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724447    5590.280     5.459

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5724975    5590.796     5.460
openf___224_> Open           ${MODINSTALL10v2}/modlib/resdih.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5773575    5638.257     5.506
rdrdih__263_> Number of dihedral angle types         :        9
              Maximal number of dihedral angle optima:        3
              Dihedral angle names                   :  Alph Phi Psi Omeg chi1 chi2 chi3 chi4 chi5
openf___224_> Open           ${MODINSTALL10v2}/modlib/radii.lib

Dynamically allocated memory at   amaxlibraries [B,KiB,MiB]:      5786875    5651.245     5.519
openf___224_> Open           ${MODINSTALL10v2}/modlib/af_mnchdef.lib
rdwilmo_274_> Mainchain residue conformation classes:  APBLE
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch.lib
rdclass_257_> Number of classes:        5
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch2.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch3.lib
openf___224_> Open           ${MODINSTALL10v2}/modlib/xs4.mat
rdrrwgh_268_> Number of residue types:       21
openf___224_> Open           trimmed_align.ali

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5798840    5662.930     5.530

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5800290    5664.346     5.532

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5803190    5667.178     5.534

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5808990    5672.842     5.540

Dynamically allocated memory at   amaxalignment [B,KiB,MiB]:      5938198    5799.021     5.663

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5939378    5800.174     5.664

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      5940558    5801.326     5.665

Read the alignment from file       : trimmed_align.ali

Total number of alignment positions:   296

  #  Code        #_Res #_Segm PDB_code    Name
-------------------------------------------------------------------------------
  1  result\cu     296      1 result\cura
  2       1NI2     296      1        1NI2
check_a_343_> >> BEGINNING OF COMMAND
openf___224_> Open           .\result\curated\tmp\chainB.pdb

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6031083    5889.729     5.752

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6031083    5889.729     5.752

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6031254    5889.896     5.752

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6032104    5890.727     5.753

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6033362    5891.955     5.754

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6035266    5893.814     5.756

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6035266    5893.814     5.756

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6035356    5893.902     5.756

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6038212    5896.691     5.758

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6038212    5896.691     5.758

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6038347    5896.823     5.759

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042631    5901.007     5.763

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6042631    5901.007     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6042829    5901.200     5.763

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049255    5907.476     5.769

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6049255    5907.476     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6049552    5907.766     5.769

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6059174    5917.162     5.778

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6059174    5917.162     5.778

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6059624    5917.602     5.779

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6074074    5931.713     5.793

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6074074    5931.713     5.793

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6074749    5932.372     5.793

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6096407    5953.522     5.814

Dynamically allocated memory at    amaxsequence [B,KiB,MiB]:      6096407    5953.522     5.814

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6097415    5954.507     5.815

Dynamically allocated memory at amaxcoordinates [B,KiB,MiB]:      6129919    5986.249     5.846

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      6129550    5985.889     5.846

check_ali___> Checking the sequence-structure alignment.

Implied intrachain target CA(i)-CA(i+1) distances longer than  8.0 angstroms:

ALN_POS  TMPL  RID1  RID2  NAM1  NAM2     DIST
----------------------------------------------
END OF TABLE
check_a_344_> << END OF COMMAND
openf___224_> Open           ${LIB}/top_heav.lib
read_to_681_> topology.submodel read from topology file:        3

openf___224_> Open           ${LIB}/par.lib

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6268802    6121.877     5.978

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6270402    6123.439     5.980

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6274382    6127.326     5.984

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6276382    6129.279     5.986

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6279382    6132.209     5.988

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6283882    6136.604     5.993

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6289454    6142.045     5.998

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6292254    6144.779     6.001

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6296454    6148.881     6.005

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6302754    6155.033     6.011

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6305526    6157.740     6.013

Dynamically allocated memory at  amaxparameters [B,KiB,MiB]:      6306926    6159.107     6.015
read_pa_232_> parameters    BONDS   ANGLS  DIHEDS IMPROPS    MODE
                              227     561     661     112       0

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6353241    6204.337     6.059

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6596673    6442.063     6.291

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6633841    6478.360     6.327

getf_______W> RTF restraint not found in the atoms list:
              residue type, indices:    13     1
              atom names           : N     -C    CA    CD
              atom indices         :     1     0     2     3

mkilst______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      296   2465   2526      0         0      1059

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6739117    6581.169     6.427

patch_______> segment topology patched using RTF:  1 ;  PRO  ;  PROP
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      296   2465   2526   3406      4027      1059


Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:      6849613    6689.075     6.532
patch_______> segment topology patched using RTF:  296 ;  PRO  ;  CTER
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      296   2466   2527   3408      4029      1060

genseg______> segment topology constructed from sequence and RTF:
              segments residues  atoms  bonds angles dihedrals impropers:
                     1      296   2466   2527   3408      4029      1060
transfe_506_> MODEL is an average of all templates.
transfe_511_> Number of templates for coordinate transfer:        1
              After transferring coordinates of the equivalent template atoms,
              there are defined, undefined atoms in MODEL:     2457        9
openf___224_> Open           1NI2.ini
wrpdb___568_> Residues, atoms, selected atoms:      296     2466     2466
make_re_417_> Restraint type to be calculated:  stereo

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6957062    6794.006     6.635

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6965254    6802.006     6.643

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      6981638    6818.006     6.658

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7014406    6850.006     6.689

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7047174    6882.006     6.721

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7112710    6946.006     6.783

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7145478    6978.006     6.814

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7178246    7010.006     6.846

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7243782    7074.006     6.908

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7374854    7202.006     7.033

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7440390    7266.006     7.096

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7505926    7330.006     7.158

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7636998    7458.006     7.283

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      7899142    7714.006     7.533

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8030214    7842.006     7.658
r_stere_606_> Stereochemical restraints were constructed from RTF & PRMF.
              Added bond,angle,dihedral,improper restraints  :     2527    3408    3842    1046
              Total number of restraints before, now         :        0    10823
make_re_422_> Number of previous, current restraints         :        0    10823
make_re_423_> Number of previous, current selected restraints:        0    10823
make_re_417_> Restraint type to be calculated:  phi-psi_binormal

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8204557    8012.263     7.824
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/mnch1.mdt
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        5      147  SER
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        5      161  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        5      257  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        6      161  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        6      257  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        7      161  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        7      257  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        8      161  LYS
errdih__638_> Missing atoms in a dihedral, residue index, residue type:        8      257  LYS
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    10823    11117
make_re_423_> Number of previous, current selected restraints:    10823    11117
make_re_417_> Restraint type to be calculated:  omega_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8204573    8012.278     7.824
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/omega.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
omgdel__425_> Unselected all O C +N +CA dihedrals:      309
              (This is to avoid clashes between STEREO
              and OMEGA_DIHEDRAL restraints)
make_re_422_> Number of previous, current restraints         :    11117    11412
make_re_423_> Number of previous, current selected restraints:    11117    11103
make_re_417_> Restraint type to be calculated:  chi1_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8204573    8012.278     7.824
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      8335645    8140.278     7.949
make_re_422_> Number of previous, current restraints         :    11412    11679
make_re_423_> Number of previous, current selected restraints:    11103    11370
make_re_417_> Restraint type to be calculated:  chi2_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8335645    8140.278     7.949
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi2.mdt
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11679    11907
make_re_423_> Number of previous, current selected restraints:    11370    11598
make_re_417_> Restraint type to be calculated:  chi3_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8335645    8140.278     7.949
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi3.mdt

getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    11907    12012
make_re_423_> Number of previous, current selected restraints:    11598    11703
make_re_417_> Restraint type to be calculated:  chi4_dihedral

Dynamically allocated memory at   amaxstructure [B,KiB,MiB]:      8335645    8140.278     7.949
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi1234.bin
openf___224_> Open           ${MODINSTALL10v2}/modlib/chi4.mdt
mdtrsr__446W> A potential that relies on one protein is used, yet you have at
              least one known structure available. MDT, not library, potential is used.
getdata_643_> Protein accepted:  result\curated\tmp\chainB
getdata_289_> Proteins (all/accepted):        1        1
make_re_422_> Number of previous, current restraints         :    12012    12059
make_re_423_> Number of previous, current selected restraints:    11703    11750
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at amaxhash_contac [B,KiB,MiB]:      9045817    8833.806     8.627

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9307961    9089.806     8.877

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:      9570105    9345.806     9.127
make_re_422_> Number of previous, current restraints         :    12059    17574
make_re_423_> Number of previous, current selected restraints:    11750    17265
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10094393    9857.806     9.627
make_re_422_> Number of previous, current restraints         :    17574    23076
make_re_423_> Number of previous, current selected restraints:    17265    22767
make_re_417_> Restraint type to be calculated:  DISTANCE

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10356537   10113.806     9.877
make_re_422_> Number of previous, current restraints         :    23076    28298
make_re_423_> Number of previous, current selected restraints:    22767    27989
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    28298    31640
make_re_423_> Number of previous, current selected restraints:    27989    31331
0 atoms in HETATM/BLK residues constrained
to protein atoms within 2.30 angstroms
and protein CA atoms within 10.00 angstroms
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    31640    31640
make_re_423_> Number of previous, current selected restraints:    31331    31331
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    31640    31640
make_re_423_> Number of previous, current selected restraints:    31331    31331
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    31640    31640
make_re_423_> Number of previous, current selected restraints:    31331    31331
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    31640    31640
make_re_423_> Number of previous, current selected restraints:    31331    31331
0 atoms in residues without defined topology
constrained to be rigid bodies
make_re_417_> Restraint type to be calculated:  DISTANCE
make_re_422_> Number of previous, current restraints         :    31640    31640
make_re_423_> Number of previous, current selected restraints:    31331    31331
rmdupl__427_>     1891 redundant cosine dihedral restraints were unselected.
condens_443_> Restraints marked for deletion were removed.
              Total number of restraints before, now:    31640    29440
openf___224_> Open           1NI2.rsr
openf___224_> Open           1NI2.rsr

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     10372373   10129.271     9.892

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11158805   10897.271    10.642
rdcsr2__307_> Number of restraints read    :    29440
              Number of excluded pairs read:        0
              Number of pseudo atoms read  :        0
rdcsrs__304_> Restraints in memory, selected restraints:    29440    29440
              Explicitly excluded atom pairs in memory :        0
              Pseudo atoms in memory                   :        0
openf___224_> Open           1NI2.ini

Dynamically allocated memory at       amaxmodel [B,KiB,MiB]:     11158837   10897.302    10.642
read_mo_297_> Segments, residues, atoms:        1      296     2466
read_mo_298_> Segment:        1  1:A  296:A     2466
randomi_498_> Atoms,selected atoms,random_seed,amplitude:     2466     2466        1        4.0000
randomi_496_> Amplitude is > 0; randomization is done.
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    16248
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    18376
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    19518
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    20805
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    22822
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    24043
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    26049
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    27948

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11510593   11240.813    10.977
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    28918
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    29075
pick_re_612_> Number of MODEL atoms, selected restraints;     2466    29440
iupac_m_483_> CD1/2 CE1/2 swapped:      -90.5999       17  17
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_486_> OE1/2 will be swapped:      -98.1993       40  40
iupac_m_483_> CD1/2 CE1/2 swapped:       97.9860       43  43
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_483_> CD1/2 CE1/2 swapped:       90.8919       54  54
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_486_> OE1/2 will be swapped:     -164.7348       72  72
iupac_m_483_> CD1/2 CE1/2 swapped:       90.5624       77  77
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_486_> OE1/2 will be swapped:      163.4775       86  86
iupac_m_486_> OE1/2 will be swapped:      165.9454       90  90
iupac_m_486_> OE1/2 will be swapped:      162.7962       91  91
iupac_m_483_> CD1/2 CE1/2 swapped:      -90.7220      102  102
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_486_> OE1/2 will be swapped:     -126.3849      119  119
iupac_m_483_> CD1/2 CE1/2 swapped:      105.6427      127  127
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_485_> OD1/2 will be swapped:      128.5518      135  135
iupac_m_485_> OD1/2 will be swapped:      126.2274      158  158
iupac_m_485_> OD1/2 will be swapped:      147.6487      165  165
iupac_m_485_> OD1/2 will be swapped:      150.2337      169  169
iupac_m_487_> NH1/2 swapped:      178.9419      170  170
iupac_m_485_> OD1/2 will be swapped:      157.9584      196  196
iupac_m_483_> CD1/2 CE1/2 swapped:       93.1038      205  205
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_485_> OD1/2 will be swapped:     -116.0024      220  220
iupac_m_483_> CD1/2 CE1/2 swapped:       91.1430      239  239
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_483_> CD1/2 CE1/2 swapped:      102.9985      249  249
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_485_> OD1/2 will be swapped:      107.7065      265  265
iupac_m_483_> CD1/2 CE1/2 swapped:      106.8154      266  266
iupac_m_397W> Atoms were not swapped because of the uncertainty of how to handle the H atom.
iupac_m_487_> NH1/2 swapped:      178.5102      272  272
iupac_m_486_> OE1/2 will be swapped:      171.9266      288  288
iupac_m_487_> NH1/2 swapped:     -177.5000      294  294
>> Model assessment by DOPE potential
iatmcls_286W> MODEL atom not classified:  PRO:OXT  PRO

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11862549   11584.521    11.313

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     11980917   11700.114    11.426

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12217653   11931.302    11.652

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     12691125   12393.677    12.103

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     13638069   13318.427    13.006

Dynamically allocated memory at  amaxrestraints [B,KiB,MiB]:     15531957   15167.927    14.812

>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      296
Number of all, selected real atoms                :     2466    2466
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    29440   29440
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):   454506
Dynamic pairs routine                             : 1, NATM x NATM double loop
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        1    9999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :   15.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       F       F       F       T
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :      -35255.1172




<< end of ENERGY.
DOPE score               : -35255.117188
>> Model assessment by GA341 potential

Surface library          : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/surf5.de
Pair library             : C:/Users/xdzl45/Anaconda3\Library\modeller/modlib/pair9.de
Chain identifier         : _
% sequence identity      :   100.000000
Sequence length          :          296
Compactness              :     0.215425
Native energy (pair)     :  -272.080784
Native energy (surface)  :   -26.821868
Native energy (combined) :   -11.428016
Z score (pair)           :    -7.450438
Z score (surface)        :    -9.037894
Z score (combined)       :   -10.529051
GA341 score              :     1.000000



>> ENERGY; Differences between the model's features and restraints:
Number of all residues in MODEL                   :      296
Number of all, selected real atoms                :     2466    2466
Number of all, selected pseudo atoms              :        0       0
Number of all static, selected restraints         :    29440   29440
COVALENT_CYS                                      :        F
NONBONDED_SEL_ATOMS                               :        1
Number of non-bonded pairs (excluding 1-2,1-3,1-4):     5032
Dynamic pairs routine                             : 2, NATM x NATM cell sorting
Atomic shift for contacts update (UPDATE_DYNAMIC) :    0.390
LENNARD_JONES_SWITCH                              :    6.500   7.500
COULOMB_JONES_SWITCH                              :    6.500   7.500
RESIDUE_SPAN_RANGE                                :        0   99999
NLOGN_USE                                         :       15
CONTACT_SHELL                                     :    4.000
DYNAMIC_PAIRS,_SPHERE,_COULOMB,_LENNARD,_MODELLER :        T       T       F       F       F
SPHERE_STDV                                       :    0.050
RADII_FACTOR                                      :    0.820
Current energy                                    :        1536.1069





Summary of the restraint violations:

   NUM     ... number of restraints.
   NUMVI   ... number of restraints with RVIOL > VIOL_REPORT_CUT[i].
   RVIOL   ... relative difference from the best value.
   NUMVP   ... number of restraints with -Ln(pdf) > VIOL_REPORT_CUT2[i].
   RMS_1   ... RMS(feature, minimally_violated_basis_restraint, NUMB).
   RMS_2   ... RMS(feature, best_value, NUMB).
   MOL.PDF ... scaled contribution to -Ln(Molecular pdf).

 #                     RESTRAINT_GROUP      NUM   NUMVI  NUMVP   RMS_1   RMS_2         MOL.PDF     S_i
------------------------------------------------------------------------------------------------------
 1 Bond length potential              :    2527       0      0   0.005   0.005      15.460       1.000
 2 Bond angle potential               :    3408       0      6   1.800   1.800      218.26       1.000
 3 Stereochemical cosine torsion poten:    1642       0     28  44.674  44.674      516.96       1.000
 4 Stereochemical improper torsion pot:    1046       0      0   1.093   1.093      27.208       1.000
 5 Soft-sphere overlap restraints     :    5032       0      0   0.002   0.002      1.7065       1.000
 6 Lennard-Jones 6-12 potential       :       0       0      0   0.000   0.000      0.0000       1.000
 7 Coulomb point-point electrostatic p:       0       0      0   0.000   0.000      0.0000       1.000
 8 H-bonding potential                :       0       0      0   0.000   0.000      0.0000       1.000
 9 Distance restraints 1 (CA-CA)      :    5515       0      1   0.100   0.100      59.783       1.000
10 Distance restraints 2 (N-O)        :    5502       0      0   0.147   0.147      105.44       1.000
11 Mainchain Phi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
12 Mainchain Psi dihedral restraints  :       0       0      0   0.000   0.000      0.0000       1.000
13 Mainchain Omega dihedral restraints:     295       0      2   3.889   3.889      51.850       1.000
14 Sidechain Chi_1 dihedral restraints:     267       0      0  42.579  42.579     0.47251       1.000
15 Sidechain Chi_2 dihedral restraints:     228       0      1  60.877  60.877      51.977       1.000
16 Sidechain Chi_3 dihedral restraints:     105       0      0  63.915  63.915      60.555       1.000
17 Sidechain Chi_4 dihedral restraints:      47       0      0  83.956  83.956      28.083       1.000
18 Disulfide distance restraints      :       0       0      0   0.000   0.000      0.0000       1.000
19 Disulfide angle restraints         :       0       0      0   0.000   0.000      0.0000       1.000
20 Disulfide dihedral angle restraints:       0       0      0   0.000   0.000      0.0000       1.000
21 Lower bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
22 Upper bound distance restraints    :       0       0      0   0.000   0.000      0.0000       1.000
23 Distance restraints 3 (SDCH-MNCH)  :    5222       0      0   0.421   0.421      169.94       1.000
24 Sidechain Chi_5 dihedral restraints:       0       0      0   0.000   0.000      0.0000       1.000
25 Phi/Psi pair of dihedral restraints:     294       2     18  22.947  24.285     -23.689       1.000
26 Distance restraints 4 (SDCH-SDCH)  :    3342       0      2   0.728   0.728      252.10       1.000
27 Distance restraints 5 (X-Y)        :       0       0      0   0.000   0.000      0.0000       1.000
28 NMR distance restraints 6 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
29 NMR distance restraints 7 (X-Y)    :       0       0      0   0.000   0.000      0.0000       1.000
30 Minimal distance restraints        :       0       0      0   0.000   0.000      0.0000       1.000
31 Non-bonded restraints              :       0       0      0   0.000   0.000      0.0000       1.000
32 Atomic accessibility restraints    :       0       0      0   0.000   0.000      0.0000       1.000
33 Atomic density restraints          :       0       0      0   0.000   0.000      0.0000       1.000
34 Absolute position restraints       :       0       0      0   0.000   0.000      0.0000       1.000
35 Dihedral angle difference restraint:       0       0      0   0.000   0.000      0.0000       1.000
36 GBSA implicit solvent potential    :       0       0      0   0.000   0.000      0.0000       1.000
37 EM density fitting potential       :       0       0      0   0.000   0.000      0.0000       1.000
38 SAXS restraints                    :       0       0      0   0.000   0.000      0.0000       1.000
39 Symmetry restraints                :       0       0      0   0.000   0.000      0.0000       1.000



openf___224_> Open           1NI2.V99990001
# Heavy relative violation of each residue is written to: 1NI2.V99990001
# The profile is NOT normalized by the number of restraints.
# The profiles are smoothed over a window of residues:    1
# The sum of all numbers in the file:   23570.8027



List of the violated restraints:
   A restraint is violated when the relative difference
   from the best value (RVIOL) is larger than CUTOFF.

   ICSR   ... index of a restraint in the current set.
   RESNO  ... residue numbers of the first two atoms.
   ATM    ... IUPAC atom names of the first two atoms.
   FEAT   ... the value of the feature in the model.
   restr  ... the mean of the basis restraint with the smallest
              difference from the model (local minimum).
   viol   ... difference from the local minimum.
   rviol  ... relative difference from the local minimum.
   RESTR  ... the best value (global minimum).
   VIOL   ... difference from the best value.
   RVIOL  ... relative difference from the best value.


-------------------------------------------------------------------------------------------------

Feature 25                           : Phi/Psi pair of dihedral restraints
List of the RVIOL violations larger than   :       6.5000

    #   ICSR  RESNO1/2 ATM1/2   INDATM1/2    FEAT   restr    viol   rviol   RESTR    VIOL   RVIOL
    1   8872 249F 250N C   N    2060 2062  -87.43  -63.20   95.22   13.28  -63.20   95.22   13.28
    1        250N 250N N   CA   2062 2063 -133.18  -41.10                  -41.10
    2   8885 262K 263A C   N    2170 2172  145.19 -134.00   90.66    4.58   55.40  112.46   13.11
    2        263A 263A N   CA   2172 2173  105.91  147.00                   38.20


report______> Distribution of short non-bonded contacts:

DISTANCE1:  0.00 2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40
DISTANCE2:  2.10 2.20 2.30 2.40 2.50 2.60 2.70 2.80 2.90 3.00 3.10 3.20 3.30 3.40 3.50
FREQUENCY:     0    0    0    0    0    4   27   86  132  194  231  269  335  367  412


<< end of ENERGY.
openf___224_> Open           1NI2.B99990001.pdb
wrpdb___568_> Residues, atoms, selected atoms:      296     2466     2466

>> Summary of successfully produced models:
Filename                          molpdf     DOPE score    GA341 score
----------------------------------------------------------------------
1NI2.B99990001.pdb            1536.10693   -35255.11719        1.00000

Show the DataFrame reporting on structures successfully downloaded and curated.

In [4]:
pdb.df

  Uniprot Entry               PDB Code     Method Resolution   Chains
0        P04406                   1U8F      X-ray       1.75  O/P/Q/R
1        Q9HB71  AF-Q9HB71-F1-model_v1  Predicted        NaN        A
2        P15311                   1NI2      X-ray       2.30      A/B

### 2. Feature Extraction  <a class="anchor" id="measure"></a>

For all structures correctly curated in the previous step, calculate pKa and Solvent Accessible Surface Area (SASA).

<div class="alert alert-warning">
<b>Warning:</b> calculations typically take ~1 min per curated protein structure (depending on their size and number of lysines).
</div>

In [5]:
M = Measure(pdb.df, "result")
M.measure_dataframe()

#TODO: Measure object saves DataFrame in a csv within its designated results folder

# UNIPROT: P04406 PDB: 1U8F, chain(s): O P Q R

> File: result\curated\1U8F-alt1A.pdb
>> 104 lysines of interest found
>> evaluating pKa...
>> evaluating sasa...

> File: result\curated\1U8F-alt1B.pdb
>> 104 lysines of interest found
>> evaluating pKa...
>> evaluating sasa...

# UNIPROT: Q9HB71 PDB: AF-Q9HB71-F1-model_v1, chain(s): A

> File: result\curated\AF-Q9HB71-F1-model_v1.pdb
>> 33 lysines of interest found
>> evaluating pKa...
>> evaluating sasa...

# UNIPROT: P15311 PDB: 1NI2, chain(s): A B

> File: result\curated\1NI2-alt-1.pdb
>> 62 lysines of interest found
>> evaluating pKa...
>> evaluating sasa...

Print the final measures output, sorted by UNIPROT entry first, and then by resid.

In [9]:
result = M.df.dropna()
result.sort_values(['Uniprot Entry', 'Resid'])

,Uniprot Entry,PDB Code,Method,Resolution,Chain,Resid,pKa,sasa
0,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,3,10.48,82.738980
26,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,3,10.65,54.270751
52,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,3,10.22,52.025331
78,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,3,10.45,90.119727
104,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,3,10.67,74.643980
130,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,3,10.45,84.062703
156,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,3,10.28,81.608956
182,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,3,10.45,90.119727
1,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,5,10.27,39.882028
27,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,5,10.93,47.108967
53,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,5,10.53,56.803660
79,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,5,10.37,56.602337
105,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,5,10.59,41.738186
131,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,5,10.53,63.807023
157,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,5,10.56,38.960952
183,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,5,10.37,56.602337
2,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,27,10.47,44.651849
28,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,27,10.53,33.119881
54,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,27,10.70,39.125133
80,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,27,10.99,43.423159
106,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,27,10.92,43.337878
132,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,27,10.88,31.376133
158,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,27,10.94,43.577588
184,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,27,10.97,43.423159
3,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,55,9.95,55.384904
29,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,55,10.01,53.406322
55,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,55,10.25,40.029454
107,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,55,6.07,17.233861
133,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,55,9.77,54.932613
159,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,55,11.04,39.152884
4,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,61,10.51,48.366913
30,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,61,10.84,54.857967
56,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,61,10.78,57.359853
82,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,61,10.34,46.777595
108,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,61,10.50,47.398943
134,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,61,10.75,41.095206
160,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,61,11.32,55.601478
186,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,61,10.32,46.777595
5,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,66,9.77,37.366758
31,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,66,10.17,49.787175
57,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,66,10.27,47.490605
83,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,66,10.31,50.250462
109,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,66,10.18,35.685416
135,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,66,10.28,49.664129
161,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,66,10.28,42.848084
187,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,66,10.31,50.250462
6,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,84,10.68,46.505880
32,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,84,10.64,48.603253
58,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,84,10.65,60.615263
84,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,84,11.47,47.107462
110,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,84,11.26,54.968250
136,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,84,10.69,48.905729
162,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,84,10.63,58.889776
188,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,84,11.47,47.107462
7,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,86,10.53,56.004747
33,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,86,10.46,59.872375
59,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,86,10.43,63.226810
85,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,86,10.54,58.909280
111,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,86,11.21,45.790120
137,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,86,10.62,59.122483
163,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,86,10.47,67.071301
189,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,86,10.54,58.909280
8,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,107,10.43,46.024332
34,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,107,10.39,58.085365
60,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,107,10.54,64.256304
86,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,107,10.33,53.353308
112,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,107,10.74,47.345928
138,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,107,10.59,62.706255
164,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,107,10.23,51.119767
190,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,107,10.33,53.353308
9,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,117,9.81,39.391972
35,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,117,10.23,50.481663
61,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,117,10.39,60.340537
87,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,117,10.30,59.204132
113,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,117,10.11,59.637279
139,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,117,10.40,69.397127
165,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,117,10.36,49.230720
191,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,117,10.30,59.204132
10,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,139,10.35,61.119063
36,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,139,9.65,45.764235
62,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,139,10.65,51.089627
88,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,139,9.90,58.741467
114,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,139,10.47,63.504285
140,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,139,9.79,47.325541
166,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,139,10.48,69.283212
192,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,139,9.90,58.741467
11,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,145,10.34,65.937023
37,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,145,10.25,68.389265
63,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,145,10.07,52.717954
89,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,145,9.93,45.303697
115,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,145,10.30,57.594687
141,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,145,10.07,44.140784
167,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,145,10.03,45.379226
193,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,145,9.93,45.303697
12,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,162,10.18,38.531798
38,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,162,9.96,32.701983
64,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,162,10.95,54.808945
90,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,162,10.08,37.024389
116,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,162,10.48,39.922541
142,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,162,10.01,30.065794
168,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,162,10.41,42.995510
194,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,162,10.08,37.024389
13,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,186,9.64,37.111798
39,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,186,10.06,61.932605
65,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,186,9.32,33.481753
91,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,186,10.29,46.365457
117,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,186,9.59,41.911497
169,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,186,9.28,50.223071
195,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,186,10.29,46.365457
14,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,194,10.41,74.880319
40,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,194,10.45,79.705282
66,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,194,10.56,85.073936
92,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,194,10.44,80.830430
118,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,194,10.46,71.061091
144,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,194,10.44,81.604080
196,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,194,10.44,80.830430
15,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,215,10.32,54.765061
41,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,215,10.14,62.235703
67,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,215,10.07,47.728188
93,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,215,10.34,64.913911
119,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,215,10.20,54.341404
145,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,215,10.24,59.508113
171,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,215,9.39,47.016683
197,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,215,10.34,64.913911
16,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,219,9.88,55.269483
42,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,219,10.29,54.131834
68,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,219,9.21,45.420361
94,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,219,10.12,46.848248
120,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,219,9.81,44.493788
146,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,219,10.13,61.356024
172,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,219,10.27,65.340938
198,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,219,10.12,46.848248
17,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,227,10.31,34.328183
43,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,227,10.30,37.714885
95,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,227,10.25,25.048638
121,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,227,10.39,34.543513
147,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,227,10.35,41.567001
199,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,227,10.24,25.048638
18,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,251,10.57,53.894251
44,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,251,10.50,61.947233
70,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,251,10.49,72.298028
96,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,251,10.47,66.819712
122,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,251,10.45,61.057540
148,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,251,10.50,60.396301
174,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,251,10.52,74.799292
200,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,251,10.47,66.819712
19,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,254,10.86,56.353496
45,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,254,10.90,63.813143
71,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,254,11.53,57.656832
97,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,254,10.92,68.953966
123,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,254,11.55,53.081331
149,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,254,10.95,56.261212
175,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,254,10.78,63.340726
201,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,254,10.92,68.953966
20,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,259,10.76,28.410960
46,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,259,10.34,30.018278
72,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,259,10.57,35.324166
98,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,259,10.40,43.941227
124,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,259,10.65,35.691798
150,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,259,10.55,37.350886
176,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,259,10.50,38.065140
202,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,259,10.34,39.384609
21,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,260,10.23,75.449896
47,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,260,11.61,58.408851
73,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,260,10.63,74.156313
99,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,260,10.39,69.227187
125,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,260,10.43,64.130509
151,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,260,10.68,69.667599
177,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,260,10.64,70.975810
203,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,260,10.39,69.227187
22,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,263,10.74,53.245774
48,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,263,10.73,56.979099
74,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,263,11.01,43.576083
100,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,263,11.02,36.887959
126,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,263,10.72,53.124855
152,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,263,10.47,50.787150
178,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,263,11.34,46.896386
204,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,263,10.63,36.887959
23,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,271,10.42,68.061525
49,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,271,10.39,60.214743
75,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,271,10.40,65.260533
101,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,271,10.36,68.300613
127,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,271,10.44,68.616474
153,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,271,10.42,68.028015
179,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,271,10.37,67.137700
205,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,271,10.11,68.300613
24,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,309,9.81,1.713608
50,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,309,8.15,8.287816
76,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,309,5.26,1.257946
102,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,309,7.27,3.396454
128,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,309,11.55,14.425866
154,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,309,8.28,15.408465
180,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,309,6.54,7.805647
206,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,309,7.08,3.498491
25,P04406,result\curated\1U8F-alt1A,X-ray,1.75,O,334,10.54,53.416958
51,P04406,result\curated\1U8F-alt1A,X-ray,1.75,P,334,10.07,19.379372
77,P04406,result\curated\1U8F-alt1A,X-ray,1.75,Q,334,10.33,38.063013
103,P04406,result\curated\1U8F-alt1A,X-ray,1.75,R,334,10.54,52.466626
129,P04406,result\curated\1U8F-alt1B,X-ray,1.75,O,334,10.47,30.724907
155,P04406,result\curated\1U8F-alt1B,X-ray,1.75,P,334,10.12,22.536117
181,P04406,result\curated\1U8F-alt1B,X-ray,1.75,Q,334,10.29,26.622445
207,P04406,result\curated\1U8F-alt1B,X-ray,1.75,R,334,10.54,52.466626
241,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,3,10.42,80.084793
272,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,3,10.44,79.221607
242,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,27,10.95,53.866239
273,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,27,10.63,60.838840
243,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,35,10.38,65.725064
274,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,35,10.47,64.043101
244,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,53,10.70,57.347352
275,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,53,10.61,40.794595
245,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,60,9.42,44.119775
276,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,60,10.55,40.561266
246,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,63,10.40,54.670028
277,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,63,10.19,46.040466
247,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,64,10.36,56.658983
278,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,64,10.16,47.195492
248,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,72,10.34,86.194209
279,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,72,10.38,69.429754
249,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,79,9.70,53.381321
280,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,79,9.88,51.741115
250,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,83,7.67,9.633792
281,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,83,8.36,18.041905
251,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,100,10.61,40.631298
282,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,100,11.01,40.695569
252,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,107,9.19,30.461439
283,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,107,8.89,27.530398
253,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,133,11.03,50.797524
284,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,133,10.58,49.289494
254,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,139,10.40,83.384709
285,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,139,10.07,64.366587
255,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,143,10.44,73.859334
286,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,143,10.42,69.712988
256,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,162,10.42,82.959186
287,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,162,10.46,78.139100
257,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,184,10.52,68.222335
288,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,184,10.50,55.505823
258,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,193,10.89,43.085667
289,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,193,10.97,36.735036
259,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,209,11.41,54.233870
290,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,209,11.30,52.801108
260,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,211,10.35,76.185160
291,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,211,10.50,82.648201
261,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,212,10.13,57.905050
292,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,212,10.37,70.790620
262,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,230,10.67,42.634881
293,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,230,10.51,30.478816
263,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,233,9.68,42.244996
294,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,233,9.72,39.285322
264,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,237,10.50,70.393732
295,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,237,10.76,60.340537
265,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,253,10.43,54.729424
296,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,253,10.36,56.329116
266,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,254,11.21,42.453061
297,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,254,10.47,53.628034
267,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,258,10.29,61.723656
298,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,258,9.92,47.797958
268,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,262,10.58,65.524002
299,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,262,10.14,60.128578
269,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,263,10.50,73.397291
300,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,263,10.59,75.827280
270,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,278,10.22,54.938994
301,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,278,10.06,46.233903
271,P15311,result\curated\1NI2-alt-1,X-ray,2.30,A,296,10.36,57.661086
302,P15311,result\curated\1NI2-alt-1,X-ray,2.30,B,296,10.43,72.205744

### 3. Data Analysis  <a class="anchor" id="analysis"></a>

The Analysis class is resonsible of interpreting data stored in the DataFrame `Measures.df`. Data is saved in `Analysis.df` and  automatically aggregated in `Analysis.df_aggregate`. Aggregation involves calculating min, max, mean and standard deviation for each feature (a single lysine may features multiple measurements in the input dataframe).
Here, the ground truth (i.e. known carbamylated lysines) can also be loaded. Ground truth is appended as an extra column to `Analysis.df` and `Analysis.df_aggregate`.

Start by initializing `Analysis` either via a previously saved logfile, or from a DataFrame in a `Measure` instance.

In [ ]:
if True: # is a Measures instance was produced above
    df = M.df
else: # if a logfile storing a Measures DataFrame calculated in a previous session 
    df = pd.read_csv("results\\results_2608\\results.csv")

#TODO 1: aggregate data according to the selection below (extract mean and std of each measure)
#entries = result.drop_duplicates(subset=["Uniprot Entry", "Resid"])[["Uniprot Entry", "Resid"]]
#entries
#
#TODO 2: load experimental evidence (ground truth, i.e. what is carbamylated) into an Analysis class.
#        The class stores both aggregated and raw data. Ground truth appended as extra column.


# A = Analysis(df)

Plot data on interactive plot. Gray points represent the aggregated data, featuring one point per uniprot code. Clicking on any point will show additional points in red. These points are the measures performed on every protein structure associated with the uniprot code selected by clicking.

In [ ]:
#ISSUE: hovering always looks as if the aggregate plot is selected, although focus items are clicked

df_data = M.df

def update_point(trace, points, selector):
          
    #print(trace, points)    
    
    # only work with gray points
    if len(points.point_inds) == 0:
        return  
    
    # gather uniprot and chain ID from full dataset clicked point
    idx = points.point_inds[0]
    my_uniprot = df_data.loc[idx, "Uniprot Entry"]
    my_resid = df_data.loc[idx, "Resid"]
    my_label = "%s(%i)"%(my_uniprot, my_resid)
    df_query = df.query('`Uniprot Entry` == "%s" and resid == %s'%(my_uniprot, my_resid))

    #plot data associated with selection
    #labels = ["UNIPROT: %s<br>resid: %i"%(df_query["Uniprot Entry"].values[i], df_query["resid"].values[i]) for i in range(len(df_query))]
    labels = ["PDB: %s"%(df_query["PDB Code"].values[i]) for i in range(len(df_query))]
    if len(f.data)>1:
        f.data = [f.data[0]]

    f.add_scatter(x=df_query["sasa"], y=df_query["pKa"],
                  mode='markers', showlegend=False, name=my_label,
                  text = labels, hovertemplate='%{text}<br>SASA: %{x:.2f}<br>pKa: %{y:.2f}')

    
    #identify clicked point and mark it differently (e.g. different colour or size)
    #c = list(scatter.marker.color)
    #for i in points.point_inds:
    #    c[i] = '#ffffff'
    #    with f.batch_update():
    #        scatter.marker.color = c

# create scatter plot
labels = ["UNIPROT: %s<br>resid: %i"%(df_data["Uniprot Entry"].values[i], df_data ["Resid"].values[i]) for i in range(len(df_data))]
f = go.FigureWidget([go.Scatter(x=df_data["sasa"], y=df_data["pKa"],
                                mode='markers', name="aggregate", showlegend=False, opacity=0.75,
                                text = labels, hovertemplate='%{text}<br>SASA: %{x:.2f}<br>pKa: %{y:.2f}'
                               )
                    ])

# add labels
f.update_layout(
    xaxis_title="SASA (A2)",
    yaxis_title="pKa")

#set axes properties
f.update_xaxes(range=[0, 130])
f.update_yaxes(range=[-2, 20])
f.update_xaxes(showspikes=True)
f.update_yaxes(showspikes=True)

#parameterize colours and triggers
scatter = f.data[0]
colors = ['#aaaaaa'] * len(df_data)
scatter.marker.color = colors
f.layout.hovermode = 'closest'
scatter.on_click(update_point)
f

Select desired uniprot entry and resid from the logfile, based on observation of the plot above.

In [ ]:
uniprot = "P15531" #insert uniprot code here
resid = 85 #insert resid here

Display all lysine entries matching the uniprot code and resid provided above, and provide statistics(this is useful if more than one lysine conformation was analysed).

In [ ]:
df_query = df.query('`Uniprot Entry` == "%s" and resid == %s'%(uniprot, resid))
pKa = df_query["pKa"]
sasa = df_query["sasa"]
print("uniprot %s, resid %s\n%s measures\npKa %4.2f pm %4.2f [%4.2f %4.2f]\nsasa %4.2f pm %4.2f [%4.2f %4.2f] A2"%
      (uniprot, resid, len(pKa),
       np.mean(pKa), np.std(pKa), np.min(pKa), np.max(pKa),
       np.mean(sasa), np.std(sasa), np.min(sasa), np.max(sasa)))


df.query('`Uniprot Entry` == "%s" and resid == %s'%(uniprot, resid))

Select index of an entry of interest, to be visualized in 3D

In [ ]:
idx = 8699

Display the structure of interest

In [ ]:
resid = df.loc[idx, "resid"]
chain = df.loc[idx, "chain"]
PDB = "%s%s%s.pdb"%(folder_path, os.sep, df.loc[idx, "PDB Code"])
print("file: %s, chain: %s, resid: %s"%(PDB, chain, resid))

#u = mda.Universe(PDB)
#protein = u.select_atoms('protein')
#view = nv.show_mdanalysis(protein)
view

In [ ]:
# SCATCH AREA, EXAMPLE CODES FOR DIFFERENT USAGES #

# example: show data visible through hovering over points
#
#fig = px.scatter(df_datae, x="sasa", y="pKa", opacity=0.5,
#                 #error_x="sasa stdev", error_y="pKa stdev",
#                 hover_data=["PDB Code", "resid", "chain", "Uniprot Entry"])
#fig.show()

In [ ]:
import plotly.graph_objects as go
from ipywidgets import HBox, VBox

import numpy as np
np.random.seed(1)

x = np.random.rand(100)
y = np.random.rand(100)

e = go.FigureWidget([go.Scatter(x=x, y=y, mode='markers')])#, go.Scatter(x=x, y=y, mode='markers')])
g = go.FigureWidget([go.Scatter(x=x, y=y, mode='markers')])#, go.Scatter(x=x, y=y, mode='markers')])

scattere = e.data[0]
colors = ['#a3a7e4'] * 100
scattere.marker.color = colors
scattere.marker.size = [10] * 100
e.layout.hovermode = 'closest'

scatterg = g.data[0]
colors = ['#a3a7e4'] * 100
scatterg.marker.color = colors
scatterg.marker.size = [10] * 100
g.layout.hovermode = 'closest'

# create our callback function
def update_pointe(trace, points, selector):
    c = list(scattere.marker.color)
    s = list(scattere.marker.size)
    for i in points.point_inds:
        c[i] = '#bae2be'
        s[i] = 20
        with e.batch_update():
            scattere.marker.color = c
            scattere.marker.size = s
            
# create our callback function
def update_pointg(trace, points, selector):
    c = list(scatterg.marker.color)
    s = list(scatterg.marker.size)
    for i in points.point_inds:
        c[i] = '#bae2be'
        s[i] = 20
        with g.batch_update():
            scatterg.marker.color = c
            scatterg.marker.size = s



scattere.on_click(update_pointg)
scatterg.on_click(update_pointe)


VBox([e,g])

In [ ]:
def set_opacity(opacity, size):
    scattere.marker.opacity = opacity
    scattere.marker.size = size

from ipywidgets import interactive
opacity_slider = interactive(set_opacity,
                            opacity=(0.0, 1.0, 0.01),
                            size=(1,10,0.25))


opacity_slider.children[0].layout.width = '400px'
opacity_slider.children[1].layout.width = '400px'

VBox([e,g, opacity_slider])